### ISSUE TITLE
Menu looks weird on mobile devices

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero-site#1]
I can't get the menu to be full width on mobile devices (testing on an iPhone 6), and I also hate that it's half-length.

Ideally I think the mobile menu (under 768px) should be full width, full height.

**Comment by SkepticalHippo** [comment]
Fixed the width of the menu. As for the height, do you mean you'd like it to look like this?:

![](http://i.imgur.com/wvPfUhp.png)

**Comment by fluffypony** [comment]
Yes exactly

**Comment by SkepticalHippo** [comment]
Changes added to the main.css on the forums.

**Comment by stefioan** [comment]
is this resolved?

**Comment by rehrar** [comment]
@fluffypony let's close this issue with the new redesign.
