### ISSUE TITLE
Replace 'Recent News' menu and submenus with one single 'Blog' tab

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1001]
At the moment we have a "Recent News" tab in the navigation menu and when we hover on it, we will see 5 submenus (Urgent, Releases,Community, Meeting logs, all posts).

I propose to replace the "Recent Nnews" menu and submenus in a single "Blog" tab, without submenus. This way people will just need to click on "Blog" and all posts will show up (same effect of clicking "All posts") then we can give people the possibility to filter all blog posts according to the categories we already have (Urgent, Releases,Community, Meeting logs, all posts), using something like the "polular tags" box, but containing the 5 present menu categories.

This will save some clicks to the visitors and will declog the navigation menu, which is already quite dense.

**Comment by erciccione** [comment]
If there are no objections i will start working on this soon.

**Comment by Samuel-Pedraza** [comment]
I think this sounds great. My request is that we make the filtering methodology prominent enough so that it is obvious to visitors to use. But, it sounds like a great way to reduce complexity.

**Comment by erciccione** [comment]
> search functionality

@Samuel-Pedraza I'm not a big fan of the idea, since it adds vulnerabilities, but if you are interested in adding a search field, please open a new issue, so the proposal can be discussed there.

**Comment by erciccione** [comment]
#1027
