### ISSUE TITLE
Rewrite pool mining guide

### ISSUE THREAD

**Issue by 00-matt** [monero-project/monero-site#1005]
The [pooled mining guide](https://web.getmonero.org/resources/user-guides/mine-to-pool.html) needs to be updated after the PoW changed to RandomX.

xmr-stak-cpu does not support RandomX, so instructions for configuring another miner (like XMRig or xmr-stak-rx) should be written instead.

Also the number of hugepages reserved should be increased too.

**Comment by 00-matt** [comment]
Also #999 - moneropools.com is dead.

**Comment by Sunray-Nucleon** [comment]
Can i suggest to also have a hint about mining to .onion address? It should include the steps install tor relay (https://community.torproject.org/relay/setup/guard/) set "Limiting bandwidth usage" (https://support.torproject.org/operators/bandwidth-shaping/) to avoid congestion cause of traffic (or link to tor-post-install good practices https://community.torproject.org/relay/setup/post-install/)  and than set in /etc/tor/torrc the SocksPort 9050 - than also start Tor (systemctl restart tor) - and than set comfig of xMrig the same "socks5": 9150 and wallet address - than start xmRig mining - https://xmrig.com/docs/miner/tor

**Comment by 00-matt** [comment]
Yes I think that telling people that they have the option to mine to a
hidden service pool (or to a clearnet pool via an exit mode) with Tor is
a good thing. But I don't think that we should be showing people how to
set up relay nodes in a mining article.

**Comment by Sunray-Nucleon** [comment]
Can you maybe write it so, that it is incentivizing the reader to use i2p or Tor? I would even call it 'preferred' or 'to prefer' to mine via hidden service or i2p in the rewritten mining guide. Maybe you can write it somehow like:

"Because it is hiding the origin (the miners IP) a miner should utilize i2p or set up a tor relay and mine to a .onion address via socks5. For some people and in some areas its not possible to use Tor or i2p; so it is also possible to mine without, but than you reveal the IP of the minier to the pool operator. It is only a few more steps to set up a Tor relay."

**Comment by 00-matt** [comment]
Yes I think this is a good idea.

Miners should be made aware that mining reveals that they use Monero,
that the pool operator can link their IP address and wallet address, and
that if they do not use TLS when mining their wallet address is visible
for all to see.

**Comment by Sunray-Nucleon** [comment]
i would **avoid** calling it dangerous (or so) but **propagate good behavior** in the first place

also we should call it preferred to use of 8... subaddress

"When mining to a pool use a pool that supports mining to subaddresses and mine to a subaddress. Usually pools can do this, however its possible that a pool are still did not enable the support of subaddresses; so its also possible to mine to integrated 4... addresses but this would reveal your main wallet address to the pool which a miner would usually want to avoid."

**Comment by erciccione** [comment]
Please keep in mind this should be a simple guide aimed to the average user. I don't think would be wise to overcomplicate it by suggesting people to use tor/i2p to mine. I think would be great to mention the possibility, but keep in mind that this guide is not aimed to expert miners.

We could create an advanced guide for mining if we want to, with references to Tor/I2P and more, but the basic "mining to a pool" guide should be as minimal and simple as possible.

Monero it's already perceived as difficult to use, let's not scare miners away with documentation they cannot fully understand :)

**Comment by 00-matt** [comment]
What about just a footnote that links to Tor's documentation explaining
that you might want to consider using it?

**Comment by erciccione** [comment]
Sure, we could mention that it's possible to mine through Tor for increased anonimity and then link to the foot notes for more details and links.

**Comment by Sunray-Nucleon** [comment]
Yes, bad idea scare or overwhelm new arriving users. A foot note or link to 'mining good practices' for use of Tor and subaddress seems reasonable imo.

**Comment by Sunray-Nucleon** [comment]
Agree, we don't want to overwhelm (or even scare) new arriving users. A foot note or link to 'mining good practices' for use of Tor (as well subaddress for mining) seems reasonable.
