### ISSUE TITLE
Add Merchant: Capsul.org 

### ISSUE THREAD

**Issue by castormaster** [monero-project/monero-site#1006]
#### What's the name of your business?

Capsul

#### What's the URL of the website?

https://capsul.org

#### Write a brief description of your business/service (max 50 characters)

Simple, Fast, Private Virtual Machines

#### Enter the URL where a Monero mention can be found

https://capsul.org/payment

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x ] Other payment gateaway (BTCPay Server)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [x ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

A service of https://cyberia.club

**Comment by erciccione** [comment]
Looks legit.

**Comment by castormaster** [comment]
> Looks legit.

We are Very Legit.
