### ISSUE TITLE
Clicking homepage video to pause will not pause

### ISSUE THREAD

**Issue by Samuel-Pedraza** [monero-project/monero-site#1007]
When I click "Play" on the video on the homepage, it will play.

However, if I click the body of the video in order to pause it, it will not pause. It only pauses when I click the pause button.

I could see how this could be determined as "expected behavior", but I thought I would bring it someone's attention as it surprised me.

I am using Chrome Version 81 on Windows 10.

I reproduced using Chrome, Version 81 on Windows 10 on browserstack.

Would this project be open to using an open source media player for videos? I've found the HTML5 video element to be quite buggy in it's implementation throughout browsers and that might be a more simplistic solution in the long run.

**Comment by erciccione** [comment]
I could reproduce this on the live version using chromium, but not locally. Actually, the video doesn't really work locally on chromium. I tried with #994 but i didn't notice any difference.

**Comment by Samuel-Pedraza** [comment]
I think this bug can be closed, as I just tested this after the most recent Chrome update (version 83), and it seems to be working fine now.
