### ISSUE TITLE
blockchain download obsolete?

### ISSUE THREAD

**Issue by Sunray-Nucleon** [monero-project/monero-site#1011]
It's a while ago i've been trying to download the blockchain at https://web.getmonero.org/downloads/#blockchain (https://downloads.getmonero.org/blockchain.raw) - I could never successfully download the whole file. It did not work (abort at some random point) with Firefox nor Chromium and also not with download-manager. I am the only one who can not download this whole file? If not, can we disable this option and save resources?

**Comment by erciccione** [comment]
There were some problems when downloading anything from the website not long ago, but the issue was fixed. Could you try to download the raw blockchain now and see if it fails?

**Comment by Sunray-Nucleon** [comment]
1 try failed pretty soon

**Comment by Sunray-Nucleon** [comment]
It is still breaking.

**Comment by erciccione** [comment]
Seems to be working fine for me. Are you sure it's not a connection problem? or something related to your browser? The file it's big and can be that it fails during the download, especially on slow connections.

**Comment by Sunray-Nucleon** [comment]
I am on wired connection and more than 50 mBit connection, there was no connection abort, i am using internet/streaming paralell. Still i am surprised how fast it was breaking today already after 4GB. The last times, several month ago on a raspi it was usually breaking after more than 70%

**Comment by Sunray-Nucleon** [comment]
I am on wired connection and more than 50 mBit connection, there was no connection abort, i am using internet/streaming parallel. Still i am surprised how fast it was breaking today already after 4GB. The last times, several month ago on a raspi it was usually breaking after more than 70%

**Comment by Samuel-Pedraza** [comment]
Just to jump in here - I saw this issue yesterday and tested by downloading the entire blockchain from the provided link, and it downloaded completely over the period of about 12 hrs.

**Comment by Sunray-Nucleon** [comment]
Thank you for this feedback, whats your location? Can maybe someone try from central europe? I get repeatedly abortion and could never successful download the whole file.

**Comment by Samuel-Pedraza** [comment]
Yes, I am US based, West Coast.

**Comment by erciccione** [comment]
I tried multiple tests and they all succeeded with no issues. I used two VPS from central europe. @Sunray-Nucleon I think the problem is on your side.

**Comment by Sunray-Nucleon** [comment]
True, after installing a amplifier (house-distributor) in my room between wall and modem i could download it. (Data over cable - Docsis 3.1) Thanks for your efforts, glad to have it resolved. It was my end witch i could'nt imagine after many attempts.
