### ISSUE TITLE
Request to be added to 'Merchants' page

### ISSUE THREAD

**Issue by rzel** [monero-project/monero-site#1022]
#### What's the name of your business?

**bitni.com**

#### What's the URL of the website?

[https://bitni.com](https://bitni.com)

#### Write a brief description of your business/service (max 50 characters)

The Anonymous Cryptocurrency Exchange • Trade 100+ Coins

#### Enter the URL where a Monero mention can be found

(There are dozens of pages like this on the site, this is only a sample.)

https://bitni.com/swap/btc/xmr

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [* ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [* ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

We are a exchange that is fully invested in supporting Monero currency. We would really appreciate if you could add us to your list of exchanges that support Monero. You can find us at https://bitni.com.

**Comment by erciccione** [comment]
Looks ok.
