### ISSUE TITLE
_config.yml baseurl differs from live URL

### ISSUE THREAD

**Issue by Samuel-Pedraza** [monero-project/monero-site#1023]
The baseurl defined in _config.yml differs from the live URL, which causes all the links in the navbar to be formatted:

`https://getmonero.org/example-url/
`

instead of

`https://web.getmonero.org/example-url/
`

This causes every link to return a 301 status code, instead of a 200 status code.

Is it a good idea to change it? Or is there a better reason to just leave it?

Thanks

**Comment by erciccione** [comment]
IIRC that's on purpose. `web.getmonero` was confusing and looked scammy to some people (like `ww.getmonero`). I dont see a reason to change it.

**Comment by Samuel-Pedraza** [comment]
Eric - I'm just having some trouble understanding what the original intent of having web.getmonero.com on the main website if it looks scammy?

Additionally, I know that from an SEO perspective on web.getmonero.org, it would be considered best practice to link to the place that these pages exist, not rely on 301 redirects to get there.

I apologize if this isn't the medium to ask these questions - I'm not really sure where else to go with them.

Thanks

**Comment by erciccione** [comment]
Honestly i don't remember why we were using web.getmonero.org, but iirc it was related to cloudflare.

I suggest you to join `#monero-site` on Freenode, matrix and other platforms. That's a better place for questions than this issue tracker :)

**Comment by Samuel-Pedraza** [comment]
Great, thanks!
