### ISSUE TITLE
Update version number to v0.16.0.0 in 'Verify binaries on Windows (beginner)' guide

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-site#1025]
The guide currently uses v0.11.1.0 twice in this paragraph:

>Calculate the hash of the Monero binary with the command: certUtil -hashfile monero-gui-win-x64-v0.11.1.0.zip SHA256 (if you downloaded a command-line only version, replace monero-gui-win-x64-v0.11.1.0.zip accordingly).

In order to streamline user experience, we ought to update it to the current version (i.e. v0.16.0.0). Accordingly, the screenshot also ought to be updated.

**Comment by erciccione** [comment]
> the screenshot also ought to be updated.

#920. I created a Win VM for Monero stuff few days ago. I'll take care of adding the screenshots when i have some time (if nobody else does before), but it's not high in my priorities.

**Comment by erciccione** [comment]
#1083
