### ISSUE TITLE
Request to be added to 'Merchants' page

### ISSUE THREAD

**Issue by kaspotz** [monero-project/monero-site#1026]
#### What's the name of your business?

Cryptocurrency Posters

#### What's the URL of the website?

https://www.cryptocurrencyposters.com/

#### Write a brief description of your business/service (max 50 characters)

We're a crypto merchandise website that also publishes educational blogs and interviews. 

#### Enter the URL where a Monero mention can be found

Our Monero specific merchandise URL can be found here: 

https://www.cryptocurrencyposters.com/coins/monero-merch/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [X] Other payment gateaway ("Cryptocurrency" Option at Checkout)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

#### Comment

Monero was one of the first coins we accepted and one of our first blogs was an interview with Fluffypony: https://www.cryptocurrencyposters.com/riccardo-spagni-sneaker-crypto-culture/

We would highly appreciate an add to the list as we believe Monero is one of the most important projects in the crypto space.

**Comment by erciccione** [comment]
Looks legit.
