### ISSUE TITLE
Request to be added as a new merchant

### ISSUE THREAD

**Issue by DreamTrims** [monero-project/monero-site#1029]
#### What's the name of your business?

Drippin Junkies

#### What's the URL of the website?

https://drippinjunkies.co.uk/

#### Write a brief description of your business/service (max 50 characters)

Drippin Junkies is an innovative brand of E Liquids.

#### Enter the URL where a Monero mention can be found

In footer and on payment screen:
https://drippinjunkies.co.uk/

#### How do you accept Monero? *(choose only one option)*

- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)
Nomiddleman crypto payments plugin

#### How would you categorize your business? *(choose only one option)*

- [ ] Goods

#### Comment

Your project is excellent, wishing you the best of luck

**Comment by erciccione** [comment]
Looks legit.
