### ISSUE TITLE
Create 'Beginner guide to verify binaries' for Mac

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1034]
[From reddit](https://www.reddit.com/r/Monero/comments/gxnqmf/lets_improve_the_monero_faq_page_on_getmonero/ft49k07/):

> a Beginners Guide and process (if possible) for Mac users to verify binaries.
The beginners guide is only available for Windows.

**Comment by erciccione** [comment]
We need a Mac user willing to create this guide. I'm completely unfamiliar with that environment.

**Comment by x86txt** [comment]
I'll handle this. I can get the content with screenshots, can someone format it and make it pretty?

**Comment by erciccione** [comment]
@x86txt That would be great, thanks. I can take care of the format.

**Comment by searsaw** [comment]
@x86txt any progress on this? If not, I can tackle this as well.

**Comment by erciccione** [comment]
@searsaw no progresses as far as i know. Feel free to get to it and contact me if you need any help :)

**Comment by erciccione** [comment]
Closing as there seems to be no interest. Can be reopened if needed.
