### ISSUE TITLE
AltCoinPostage

### ISSUE THREAD

**Issue by johnmeek37830** [monero-project/monero-site#1041]
#### What's the name of your business?

altcoinpostage

#### What's the URL of the website?

https://www.altcoinpostage.com

#### Write a brief description of your business/service (max 50 characters)

You can buy US Postage with Monero

https://www.altcoinpostage.com

https://www.altcoinpostage.com

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ X] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)Coinpayments

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ X] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Purchase postage with Monero

**Comment by erciccione** [comment]
Looks good.
