### ISSUE TITLE
RTL support for Arabic language

### ISSUE THREAD

**Issue by Daniel-Leedan** [monero-project/monero-site#1043]
Any plans for RTL support? based on the issues search, it wasn't mentioned since [#800](https://github.com/monero-project/monero-site/pull/800#issuecomment-405259760).

I'm willing to spend some time looking into it.

LTR:
![monero-ltr](https://user-images.githubusercontent.com/8020386/84570752-0f4a2700-adc2-11ea-8c85-f7f0d20968c8.png)

RTL:
![monero-rtl](https://user-images.githubusercontent.com/8020386/84570681-8f23c180-adc1-11ea-85bb-a4d8a0ac1857.png)

**Comment by erciccione** [comment]
Would be good to have RTL support, but to my knowledge the plugin we use to make the website multilingual (https://github.com/kurtsson/jekyll-multiple-languages-plugin) doesn't support it. Would be good to investigate though, so thanks if you are willing to do it :)

**Comment by erciccione** [comment]
Resolved
