### ISSUE TITLE
Please consider adding monerocardgames.com

### ISSUE THREAD

**Issue by MoneroGamer** [monero-project/monero-site#1047]
#### What's the name of your business?

Monero Card Games

#### What's the URL of the website?

https://monerocardgames.com

#### Write a brief description of your business/service (max 50 characters)

Provably fair Monero card games.

#### Enter the URL where a Monero mention can be found

https://monerocardgames.com

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [x] Entertainment

**Comment by erciccione** [comment]
Looks ok.
