### ISSUE TITLE
Add MRL SVG logo to 'press kit' page

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1052]
I have an SVG version of the MRL logo that could be included in the press kit page. The layout of the page needs to be slighlty edited and the logo will have to be added to the `monero-press-kit.zip` archive as well.

Thanks to @SarangNoether  for the suggestion and to @Fluffypony for the logo.

**Comment by SarangNoether** [comment]
@erciccione my GitHub username is @SarangNoether!

**Comment by erciccione** [comment]
#1134
