### ISSUE TITLE
Update the link format for MRL preprints

### ISSUE THREAD

**Issue by SarangNoether** [monero-project/monero-site#1053]
Some preprints on the [MRL](https://web.getmonero.org/resources/research-lab/) page are hosted on the site, while others link to the [IACR preprint archive](https://eprint.iacr.org/), which is a generally trusted source for hosted cryptography preprints. I recommend the links to preprints be updated in two ways:
1. For external links, identify the destination: `Read paper (on IACR)`
2. For all preprints, link to the corresponding GitHub page for the TeX source: `View source (on GitHub)`

**Comment by erciccione** [comment]
@SarangNoether If we want to go ahead with this, we should have the TeX sources updated to a repository, as we discussed. How to move forward? IIRC one option was to create a "publishing" repository inside "monero-project" where to load all the sources, i think that could be a good option.

**Comment by erciccione** [comment]
Closing as there seems to be no interest. Can be reopened if needed.
