### ISSUE TITLE
Exchange listing Request

### ISSUE THREAD

**Issue by Ella-park** [monero-project/monero-site#1055]
#### What's the name of your business?

HollaEx

#### What's the URL of the website?

https://www.hollaex.com/

#### Write a brief description of your business/service (max 50 characters)

HollaEx is an open digital asset exchange built by cryptocurrency veterans and professionals for traders and businesses. 

#### Enter the URL where a Monero mention can be found

https://pro.hollaex.com/trade/xmr-usdt
https://info.hollaex.com/hc/en-us/articles/360039604114-What-are-the-coin-supported-in-HollaEx-

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Hi, I am Ella Business Development Associate at bitHolla. 
I would like to request adding the support for our exchange, hollaex.com on the Monero website. We currently support Monero on our exchange as mentioned above.
 Looking forward to hearing from you. 
Thanks in advance.

**Comment by erciccione** [comment]
Looks OK.
