### ISSUE TITLE
Exchange listing Request

### ISSUE THREAD

**Issue by antonegorov** [monero-project/monero-site#1059]
#### What's the name of your business?

SwapSwop

#### What's the URL of the website?

https://swapswop.io/

#### Write a brief description of your business/service (max 50 characters)

SwapSwop is an instant anonymous crypto exchange with a high level of security.

#### Enter the URL where a Monero mention can be found

https://swapswop.io/ (Monero can be found in the drop-down list of all currencies)

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Hello, I am Anthony E. CEO at SwapSwop. I would like to request adding the link our instant exchange, 
swapswop.io on your site.

Thanks in advance.

**Comment by erciccione** [comment]
Looks OK.
