### ISSUE TITLE
Make media files deterministically reproducible

### ISSUE THREAD

**Issue by garlicgambit** [monero-project/monero-site#1064]
Where applicable make media files deterministically reproducible. This applies to pdf and epub files that are available for download on the website.  
  
Motivation: same reasons as with reproducible builds for the binaries. Independent verification and trust minimization.

**Comment by erciccione** [comment]
This will be probably unnecessary soon. See #1053. The idea is to replace our self hosted PDFs with links to an external source (IACR) and the LaTex source.

**Comment by erciccione** [comment]
Closing as not planned.
