### ISSUE TITLE
Update Hangouts to include icon/link for Discord, Matrix

### ISSUE THREAD

**Issue by sanecito** [monero-project/monero-site#1077]
[Hangouts](https://web.getmonero.org/community/hangouts/) should be updated to include links to both Discord (https://discordapp.com/invite/XVKK6hX) which is bridged to IRC and a link to the Matrix bundle ('Community') of bridged Monero IRC channels (https://matrix.to/#/+monero:matrix.org). This is to make it easier join and engage with the Monero community.

Logos for reference for adding to the spritesheet:

https://en.wikipedia.org/wiki/Matrix_(protocol)#/media/File:Matrix_logo.svg

https://discord.com/new/branding

**Comment by erciccione** [comment]
The Hangouts page needs to be updated and probably restyled. This is in my todo list.

**Comment by SamsungGalaxyPlayer** [comment]
I will also add the Discord and Matrix links to the Community Meeting invite templates.

**Comment by sanecito** [comment]
Updated issue to reference logo resource for Matrix. I was originally skeptical this was the logo/icon to use, but I've seen it used multiple notable places this past week like Mobian's website so this is what we should use

**Comment by erciccione** [comment]
I opened #1125, but it doesn't include Discord, only Mattermost and Matrix, which are FOSS.
