### ISSUE TITLE
Exchange listing Request

### ISSUE THREAD

**Issue by bitvape** [monero-project/monero-site#1088]
#### What's the name of your business?

Bitvape

#### What's the URL of the website?

https://bitvape.com.au

#### Write a brief description of your business/service (max 50 characters)

Australia's top rated JUUL store. 

#### Enter the URL where a Monero mention can be found

https://bitvape.com.au/we-are-now-accepting-monero-xmr/

#### How do you accept Monero? *(choose only one option)*

MyCryptoCheckout

#### How would you categorize your business? *(choose only one option)*

Goods

#### Comment

I would like to request adding the support for our merchant store. We currently support Monero on our store as mentioned above. Thanks in advance

**Comment by erciccione** [comment]
Looks legit.

@bitvape would be cool if you could add a "Monero accepted" sticker at the bottom of the page, like you already do for Bitcoin :)

See https://www.themonera.art/2017/09/22/monero-promotional-graphics-badges-and-stickers-for-websites/
