### ISSUE TITLE
Implement pagination in the forums

### ISSUE THREAD

**Issue by antanst** [monero-project/monero-site#109]
In my humble opinion paginated threads are much more usable than the "infinite scroll" behaviour, and helps following and resuming forum visits. I believe this will also help newcomers that are used to how other forums function.

**Comment by fluffypony** [comment]
We already have pagination, but it only enables when you have JS disabled.

There was an open task to provide a setting for this on the user control panel, not sure if @skepticalhippo ever got around to it?

**Comment by rehrar** [comment]
@fluffypony this issue should be closed. The forums will be shutting down soon.
