### ISSUE TITLE
Mobile design issue on 'Downloads' page

### ISSUE THREAD

**Issue by Daniel-Leedan** [monero-project/monero-site#1099]
I found a issue viewing the downloads page when browsing from mobile. I checked it on Galaxy s10, Iphone 8 and Iphone 6.

The rest of the pages displayed perfectly.

## Screenshot:
![image](https://user-images.githubusercontent.com/8020386/88469886-97c2f800-cf28-11ea-8bdd-f0c3dba4b198.png)

## Zoom-in:
![image](https://user-images.githubusercontent.com/8020386/88469889-a5787d80-cf28-11ea-947d-20c5f41b76e2.png)

**Comment by erciccione** [comment]
Fixed in #1099, thanks for reporting the problem :)

**Comment by Daniel-Leedan** [comment]
It looks great. Thanks! 
I planned to work on it today but you was faster than me :)

**Comment by erciccione** [comment]
No problem, it was fun to debug.

If you can, please test and review the PR, so we can merge it soon :)
