### ISSUE TITLE
Exchange listing Request

### ISSUE THREAD

**Issue by ElenaIncognito** [monero-project/monero-site#1103]
#### What's the name of your business?

Incognito

#### What's the URL of the website?

https://incscan.io/pdex/overview

#### Write a brief description of your business/service (max 50 characters)

Completely anonymous decentralized exchange

#### Enter the URL where a Monero mention can be found

https://incscan.io/pdex/markets/PRV-pXMR
https://incscan.io/shielded-coins/evolution/pXMR
https://we.incognito.org/t/buy-and-sell-monero-xmr-confidentially-without-kyc/415

#### How do you accept Monero? *(choose only one option)*

Native wallet

#### How would you categorize your business? *(choose only one option)*

Exchange

#### Comment

Hello, I would like to request adding Incognito DEX to the getmonero website. We are focused on privacy and working on privacy swap for Monero also we offers 9% APY for liquidity providers. Thanks in advance.

**Comment by erciccione** [comment]
Briefly discussed in #monero-community. Legit.
