### ISSUE TITLE
New Merchant: monerojobs.com

### ISSUE THREAD

**Issue by ocotopdf** [monero-project/monero-site#1113]
#### What's the name of your business?

monerojobs.com

#### What's the URL of the website?

monerojobs.com

#### Write a brief description of your business/service (max 50 characters)

The goal of Monero Jobs is to provide a platform for genuine commerce in Monero. Monero Jobs is a job posting service companies can use to hire talent and pay them in Monero.

#### Enter the URL where a Monero mention can be found

https://www.monerojobs.com/donations/donate

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

A job website for the Monero community. Looking forward to working with you.

**Comment by erciccione** [comment]
Looks legit.

**Comment by ocotopdf** [comment]
@erciccione Can we get this in?

**Comment by erciccione** [comment]
I will make a new PR to add some new merchants shortly. You could also open the PR yourself referencing this issue.
