### ISSUE TITLE
Add NOWNodes to the list of merchants

### ISSUE THREAD

**Issue by wintermut9** [monero-project/monero-site#1130]
#### What's the name of your business?

NOWNodes

#### What's the URL of the website?

nownodes.io

#### Write a brief description of your business/service (max 50 characters)

NOWNodes is Explorer & Node API provider. It is meant for start-up entrepreneurs and crypto enthusiasts who would like to gain access to major blockchain networks without having to invest their time and money into establishing their own nodes.

#### Enter the URL where a Monero mention can be found

https://nownodes.io/connect-xmr-node

#### How do you accept Monero? *(choose only one option)*

- [x] Other payment gateaway (NOWPayments)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [x] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

We provide access to Monero explorer & node for everyone. Looking forward to working with you.

**Comment by erciccione** [comment]
Looks ok. PR already opened: #1129
