### ISSUE TITLE
Add Cockbox to the list of merchants

### ISSUE THREAD

**Issue by cohcho** [monero-project/monero-site#1137]
#### What's the name of your business?

Cockbox

#### What's the URL of the website?

https://cockbox.org/

#### Write a brief description of your business/service (max 50 characters)

It's a Tor-friendly, privacy-oriented VPS provider.

#### Enter the URL where a Monero mention can be found

https://cockbox.org/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment
![.](https://cockbox.org/img/cock.svg)
Cockbox is a small, Tor-friendly, privacy-oriented Bitcoin VPS provider. Due to its small size, customers have immediate access to 24/7 phone support (lie) and things are pretty relaxed in general (true). Cockbox's servers are in Bucharest, Romania, and 950 Gbit DDoS protection is automatically included on every server.

**Comment by erciccione** [comment]
Looks OK.

**Comment by erciccione** [comment]
#1159
