### ISSUE TITLE
Xchange.me - "new" merchant

### ISSUE THREAD

**Issue by wiktorglowacki** [monero-project/monero-site#1139]
#### What's the name of your business?

xChange.me

https://xchange.me http://xchangen24yn24b6.onion/

Fully anonymous cryptocurrency exchanger with only one time, small fixed fee. We do not collect any data and have fully native Tor mirror available.

https://xchange.me

https://xchange.me

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks ok.

**Comment by erciccione** [comment]
#1159
