### ISSUE TITLE
Add AUGET to the list of merchants

### ISSUE THREAD

**Issue by fouzkov** [monero-project/monero-site#1143]
#### What's the name of your business?

AUGET

#### What's the URL of the website?

https://auget.paris/en/

#### Write a brief description of your business/service (max 50 characters)

AUGET is a new French brand of scented candles. 100% made in France : designed in Paris & made in Grasse.

#### Enter the URL where a Monero mention can be found

https://auget.paris/en/faq/#1567853531584-4bafee09-2c75

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [x ] Goods
- [ ] Entertainment

#### Comment

Thank you !

**Comment by erciccione** [comment]
Looks ok.
