### ISSUE TITLE
Add DV Chain to the list of merchants

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#1147]
#### What's the name of your business?

DV Chain (OTC)

#### What's the URL of the website?

https://dvchain.co

#### Write a brief description of your business/service (max 50 characters)

DV Chain is a cryptocurrency OTC desk that offers buying and selling of Monero.

#### Enter the URL where a Monero mention can be found

Monero logo in the "deep global liquidity" icon.

https://dvchain.co

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*): third party custodian

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

No further comments

**Comment by erciccione** [comment]
#1159
