### ISSUE TITLE
Add Newton to the list of merchants

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#1148]
#### What's the name of your business?

Newton

#### What's the URL of the website?

https://newton.co

#### Write a brief description of your business/service (max 50 characters)

Newton is a Canadian cryptocurrency exchange.

#### Enter the URL where a Monero mention can be found

https://www.newton.co/coin/buy-monero

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*): third party custodian Balance

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Newton is the simplest way to buy and sell XMR in Canada.

**Comment by erciccione** [comment]
#1159
