### ISSUE TITLE
Add CryptoWoo to the list of gateways

### ISSUE THREAD

**Issue by Wegerich** [monero-project/monero-site#1156]
#### What's the name of your business?

CryptoWoo Monero Plugin

#### What's the URL of the website?

https://www.cryptowoo.com/

#### Write a brief description of your business/service (max 50 characters)

Cryptowoo is a gateway that allows WooCommerce users to accept payments in Monero directly to their private wallet with no intermediary.

#### Enter the URL where a Monero mention can be found

https://www.cryptowoo.com/shop/monero-add-on/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [x] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Not my business.

**Comment by erciccione** [comment]
Looks ok.

**Comment by erciccione** [comment]
#1159
