### ISSUE TITLE
Duplicate link URL in feed.xml

### ISSUE THREAD

**Issue by azuchi** [monero-project/monero-site#1162]
URL in feed.xml is duplicated as below.

```
<link href="https://www.getmonero.org/https://www.getmonero.org/2020/08/22/triptych.html" rel="alternate" type="text/html" title=" Triptych accepted for publication"/>
```

https://web.getmonero.org/feed.xml

Maybe you need to modify the `baseurl` setting in `_config.xml`?

**Comment by erciccione** [comment]
Looks like the plugin for the feed is using both `url` and `baseurl`. Will check.

**Comment by erciccione** [comment]
This was actually symptom of a deeper problem: we enforce a baseurl with a wrong structure and that conflicts with jekyll's structure and consequently, most of the plugins, like `jekyll-feed`, which we use to generate the feed.xml file. We are looking into solutions.

**Comment by erciccione** [comment]
#1164
