### ISSUE TITLE
Add "Inputs" Moneropedia entry

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1172]

**Comment by moneroguides** [comment]
"Monero uses the unspent transaction output (UTXO) model for handling transaction verification.

Each transaction requires one or more outputs to be used as inputs. The term input is only relevant in the context of a transaction. Outside the context of a transaction all moneroj is considered as 'owned outputs'.

Inputs, represent some amount of Moneroj which is required to satisfy the intended outputs of a new transaction.

Using multiple outputs to satisfy a new transaction is called 'input mixing'."

![transaction-diagram](https://user-images.githubusercontent.com/93890007/167261933-672cf33a-1385-43cf-8478-931cdf9538b2.png)
