### ISSUE TITLE
Add "Outputs" Moneropedia entry

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1173]

**Comment by ZRFLDF** [comment]
add  "Median block"?

**Comment by erciccione** [comment]
@ZRFLDF If you are suggesting a new Moneropedia entry, please open a dedicated issue.

**Comment by moneroguides** [comment]
"Monero uses the unspent transaction output (UTXO) model for handling transaction verification.
 
UTXOs aka owned outputs use public key cryptography to identify and transfer ownership between holders of public/private key pairs.

Outputs, represent some amount of Moneroj which has been authorised by one key pair to be spent by another."

Is there a more correct way to suggest this wording?
