### ISSUE TITLE
Add XenPods to the list of merchants

### ISSUE THREAD

**Issue by xenpods** [monero-project/monero-site#1179]
#### What's the name of your business?

XenPods

#### What's the URL of the website?

https://xenpods.com.au

#### Write a brief description of your business/service (max 50 characters)

E-cigarette supplier

#### Enter the URL where a Monero mention can be found

https://xenpods.com.au/2020/09/07/we-are-now-accepting-monero-xmr/

#### How do you accept Monero? *(choose only one option)*

MyCryptoCheckout

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by dEBRUYNE-1** [comment]
Perhaps worthwhile to post on our subreddit (https://www.reddit.com/r/Monero/) too such that our community can provide feedback?

**Comment by erciccione** [comment]
Looks legit.

yeah posting on reddit for visibility is always a good idea.
