### ISSUE TITLE
Edit Moneropedia entry 'Coinbase' to clarify it has nothing to do with the exchange

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1184]
Many confuse it with the exchange.

**Comment by viperperidot** [comment]
I was going to start working on this but it looks like there is already a coinbase entry in Moneropedia. Or were you looking for one with more detail than this?

https://www.getmonero.org/resources/moneropedia/coinbase.html

**Comment by erciccione** [comment]
You are right. I think would be good to specify that it's something difference from the exchange. I'm gonna edit the title.

Better to not work on user guides and moneropedia for now. We will change the way they are localized soon (#1270)

**Comment by wildwestrom** [comment]
I came here because I thought it was talking about coinbase the exchange, and I was going to make an issue saying somebody screwed up the definition.
