### ISSUE TITLE
Improve visibility of the videos in the "What is Monero?" page

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1187]
Some [users report](https://www.reddit.com/r/Monero/comments/iaww0p/getmoneroorg_updated_improved_rss_feed_new/g57j2xq/) they are easy to miss. We could move them somewhere else or make them more visible.

**Comment by erciccione** [comment]
#1190 

Note that 1190 doesn't address the problems reported in the reddit post about videos not playing. I tried to reproduce but i wasn't able to. The structure of our videos should be supported by all browsers. @selsta reported he doesn't have any problems with Chrome, but i am having issues playing videos on chromium. I couldn't find an obvious explanation. I'm creating a dedicated Windows system to test this and will keep inspecting the issue.

**Comment by selsta** [comment]
It does also not show up with Chrome, I didn’t understand the issue initially. There is still the problems that videos keep playing if you click on next.

**Comment by erciccione** [comment]
> It does also not show up with Chrome

I created #1191 to keep track of the problem.

> There is still the problems that videos keep playing if you click on next.

That's related to the way the videos are displayed (the carousel thing), which is removed by #1190.
