### ISSUE TITLE
Add menu option for "merchants" into the "Get Started" menu

### ISSUE THREAD

**Issue by Wegerich** [monero-project/monero-site#1189]
I am looking at the homepage, wanting to find the "merchants" page to share with someone. Only I can't see the option because I instinctively looked under "Get Started" for information on how to spend monero. 

If I was new to monero then I would not consider myself part of the "community" so I would not look there for information about the merchants. Also, I think many stores accepting monero are not deep parts of the community on an indivdiual level. 

Therefore I propose that the menu item "Spending" is added to the "Get started" page, just underneath "accepting".

**Comment by erciccione** [comment]
> If I was new to monero then I would not consider myself part of the "community" so I would not look there for information about the merchants. Also, I think many stores accepting monero are not deep parts of the community on an indivdiual level.

I would argue that if you accept Monero, you are actually part of the community, so the current placement makes sense IMO. I don't have a strong opinion about moving the tab under "Get Started", beside the fact that people might be used to find it under "community" and i don't see a strong reason to move it. Let's see what others think about it.

**Comment by Wegerich** [comment]
I do agree that a justification could be made for the current location of this menu item. However, thinking about the purpose of a menu (to help people find the information they are looking for), I am wondering if putting it in an alternative, also justified location would make navigation more intuitive. 

At the end of the day I'm _not_ new to the topic so I can't truly approach from the perspective of someone who is, only think about what I _think_ their perspective would be. So it's possible I'm straight-up wrong. 

Hypothetically, could such a menu item appear in both dropdowns if it was felt that it belonged equally to each category? Perhaps even temporarily, for those who are used to finding it there...?

**Comment by erciccione** [comment]
> Hypothetically, could such a menu item appear in both dropdowns if it was felt that it belonged equally to each category? Perhaps even temporarily, for those who are used to finding it there...?

In any case i would avoid this option. It would just create confusion. A redirect to the new page would do it.

**Comment by erciccione** [comment]
FYI i added the Merchants page to the footer with #1292. That should give it more visibility.

**Comment by erciccione** [comment]
If there are no further comments i would be inclined to close this PR.

**Comment by Wegerich** [comment]
I do still think there should be a shortcut to "spend monero" in the "Get Started" menu but am happy for this to be closed unactioned as it's not popular. Thanks for your consideration.

**Comment by erciccione** [comment]
I don't think makes sense to move the menu option, but anyway there are several issues proposing more action buttons on various pages of the website. Closing this.
