### ISSUE TITLE
Add <LyraHosting> to the list of merchants

### ISSUE THREAD

**Issue by LyraHosting** [monero-project/monero-site#1194]
#### What's the name of your business?

LyraHosting

#### What's the URL of the website?

https://lyrahosting.com/

#### Write a brief description of your business/service (max 50 characters)

LyraHosting is a solid offshore hosting company.

#### Enter the URL where a Monero mention can be found

https://lyrahosting.com/ (on footer)

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*) Coinpayments

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [x] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
> What's the name of your business?
What's the URL of the website?
Write a brief description of your business/service (max 50 characters)
Enter the URL where a Monero mention can be found
How do you accept Monero? (choose only one option)

You need to fill up all fields if you want the merchant to be listed.

**Comment by LyraHosting** [comment]
> > What's the name of your business?
> > What's the URL of the website?
> > Write a brief description of your business/service (max 50 characters)
> > Enter the URL where a Monero mention can be found
> > How do you accept Monero? (choose only one option)
> 
> You need to fill up all fields if you want the merchant to be listed.

I think that i misswrote the format above

What's the name of your business? 
- LyraHosting

What's the URL of the website? 
- https://lyrahosting.com/

Write a brief description of your business/service (max 50 characters)
- LyraHosting is an Offshore hosting company with own infrastructure and dedicated network.  Selling from virtual to dedicated servers. Costumers privacy is our main goal!

Enter the URL where a Monero mention can be found
- https://lyrahosting.com/ (on footer)

How do you accept Monero? (choose only one option)
- Coinpayments gateway

**Comment by LyraHosting** [comment]
> > What's the name of your business?
> > What's the URL of the website?
> > Write a brief description of your business/service (max 50 characters)
> > Enter the URL where a Monero mention can be found
> > How do you accept Monero? (choose only one option)
> 
> You need to fill up all fields if you want the merchant to be listed.

Just a friendly reminder that message has been updated.
Best regards

**Comment by erciccione** [comment]
Looks. Ok.

@LyraHosting please also edit the content of the original issue with the deails.

**Comment by LyraHosting** [comment]
> Looks. Ok.
> 
> @LyraHosting please also edit the content of the original issue with the deails.

Hello,
Also edited main post.
Best regards

**Comment by l33d4n** [comment]
@LyraHosting The brief description of your service is longer than the max 50 characters.

**Comment by LyraHosting** [comment]
> @LyraHosting The brief description of your service is longer than the max 50 characters.

Hi,
Thank you for let me know that.
I've edited it.
Best regards

**Comment by LyraHosting** [comment]
Hi mate,
Have you approved my listening?

**Comment by SamsungGalaxyPlayer** [comment]
@LyraHosting yes, it has been approved and will go out with the next website update
