### ISSUE TITLE
Rename "Downloads" page to "Wallets"

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-site#1197]
I suggest to rename the Downloads page to Wallets:
- This page is focused in wallets in general
- It also includes hardware wallets, which cannot be downloaded
- Changing the name, we could add additional items like paper wallets and metal wallets to store seed

**Comment by erciccione** [comment]
I'm not sure if it worth the change. We have a ton of documentation pointing to the "Downloads" page. We should consider if it really worth the possible confusion. Also, consider that we offer the blockchain boostrap in that page, which is not a "Wallet".

**Comment by erciccione** [comment]
If there are no further comments/opinions, i would be inclined to close this issue.

**Comment by SamsungGalaxyPlayer** [comment]
I believe "Downloads" is more appropriate at this time. My 2c

**Comment by erciccione** [comment]
Closing this. Thanks for everybody's input.
