### ISSUE TITLE
Reduce interparagraph spacing

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#12]
Too large a space, see [The Value of Privacy](https://forum.getmonero.org/1/news-announcements-and-editorials/191/the-value-of-privacy)

Example code and explanation: <http://david.latapie.name/blog/css-code-recipes/#line-height> and <http://webtypography.net/2.2.2>

**Comment by fluffypony** [comment]
This is meant to go on the forum project, I think? Reopen if you meant to apply this to the site.
