### ISSUE TITLE
Add <Crypto Cove> to the list of merchants

### ISSUE THREAD

**Issue by cryptocove** [monero-project/monero-site#1229]
#### What's the name of your business?

Crypto Cove

#### What's the URL of the website?

<https://cryptocove.io/>

#### Write a brief description of your business/service (max 50 characters)

Crypto Cove - Crypto merch and apparel store

#### Enter the URL where a Monero mention can be found

https://cryptocove.io/collections/Monero_Merchandise_and_Apparel

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Coinpayments

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

#### Comment

Our second main header banner on the home page is the Monero bull t shirt. We have the monero Icon on the front page under the banner. We have unique monero designs, we have done sticker giveaways on r/monero. We love XMR

Our favorite : https://cryptocove.io/collections/monero_merchandise_and_apparel/products/monero-bull-crypto-t-shirt

**Comment by erciccione** [comment]
Looks good.

Just a personal comment: Monero is not bitcoin. The HODL meme is usually not well seen in the community. For the technology to work and efficiently protect people's privacy, users have to *spend* Monero, not accumulate it. More people use Monero, better will be the protection offered by the technology. Your designs seem to be of high quality, would be cool to see at least some designs being about privacy, digital cash or whatever, but technology-related and not only bitcoin-style memes about speculation (bull and moon).

**Comment by cryptocove** [comment]
> Looks good.
> 
> Just a personal comment: Monero is not bitcoin. The HODL meme is usually not well seen in the community. For the technology to work and efficiently protect people's privacy, users have to _spend_ Monero, not accumulate it. More people use Monero, better will be the protection offered by the technology. Your designs seem to be of high quality, would be cool to see at least some designs being about privacy, digital cash or whatever, but technology-related and not only bitcoin-style memes about speculation (bull and moon).
> 
> Eidt: Ok, ok, nevermind. I just noticed the bitconnect merchandise -_-

Well noted. I will add some more privacy themed designs. The monero masks give you some nice irl privacy. The I accept Monero desings would be then more in line with your comment. We actually get alot of payments in monero because of presence on r/monero. 

Glad you liked the bitconnect section. Its completely unironic :P
