### ISSUE TITLE
Add Codify Global to the list of merchants

### ISSUE THREAD

**Issue by moderniz** [monero-project/monero-site#1231]
#### What's the name of your business?

Codify Global

#### What's the URL of the website?

https://codify.global/

#### Write a brief description of your business/service (max 50 characters)

AWS consulting and technology stack modernization

#### Enter the URL where a Monero mention can be found

https://codify.global/help-center/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Ok.
