### ISSUE TITLE
Add ClientVPS Hosting to the list of merchants

### ISSUE THREAD

**Issue by Clientvps** [monero-project/monero-site#1237]
#### What's the name of your business?

ClientVPS

#### What's the URL of the website?

https://www.clientvps.com/

#### Write a brief description of your business/service (max 50 characters)

ClientVPS Offshore Hosting 

https://www.clientvps.com/payment-methods

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Coinpayments*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [x] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks Ok.

**Comment by Clientvps** [comment]
Hi
i can't see my website on your list, something is wrong ?

**Comment by erciccione** [comment]
Hi @Clientvps, we haven't added your website yet. We will first add it to the website then the server will need to be updated. It usually takes between few days and a couple of weeks
