### ISSUE TITLE
Add Bitgear Australia to the list of merchants

### ISSUE THREAD

**Issue by bitgearau** [monero-project/monero-site#1238]
#### What's the name of your business?

Bitgear Australia

#### What's the URL of the website?

https://www.bitgear.com.au/

#### Write a brief description of your business/service (max 50 characters)

Australian hardware wallet retailer

#### Enter the URL where a Monero mention can be found

https://www.bitgear.com.au/ (footer accepted payment methods)

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*) Cryptowoo

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks ok.
