### ISSUE TITLE
Issue with the 'downloads' page link

### ISSUE THREAD

**Issue by l33d4n** [monero-project/monero-site#1239]
There seems to be an issue with the link to the 'Downloads' page:
https://www.getmonero.org/get-started/faq/#import-blockchain

`<a href="{{ site.baseurl }}/downloads/#blockchain">the 'Downloads' page</a>`

https://github.com/monero-project/monero-site/blob/693eab2bf30fcdd3a6a0e8fe3385fd308c3995d1/_i18n/en.yml#L385

![image](https://user-images.githubusercontent.com/8020386/95824025-32c9b200-0d61-11eb-844d-29be7ae59a14.png)

**Comment by erciccione** [comment]
Thanks :)

Fixed in #1240
