### ISSUE TITLE
Fix website serving outdated version "v0.17.0.1" of the Linux 64-bit CLI Monero software

### ISSUE THREAD

**Issue by timetherewere** [monero-project/monero-site#1268]
https://downloads.getmonero.org/cli/linux64

**Comment by erciccione** [comment]
This is a problem of caching. Try cleaning your browser cache or opening an incognito window and then use that link again. The correct version will be downloaded. We are aware of the issue and will be fixed soon.

**Comment by erciccione** [comment]
Links are ok. Closing this and #1267
