### ISSUE TITLE
Add <symbolika.com> to the list of merchants

### ISSUE THREAD

**Issue by fabatmo** [monero-project/monero-site#1271]
#### What's the name of your business? symbolika.com

symbolika.com

#### What's the URL of the website?

https://symbolika.com

#### Write a brief description of your business/service (max 50 characters)

Psychedelic Apparel and accessories Brand
#### Enter the URL where a Monero mention can be found

https://symbolika.com/pages/terms-of-service

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [* ] Globee *
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*) 

- [ ] Globee

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ *] Goods
- [ ] Entertainment

#### Comment

Monero and Bitcoin are our proffered form of payment, Get 10% off when paying with Crypto :)

**Comment by l33d4n** [comment]
@fabatmo The brief description of your service is longer than the max 50 characters.

**Comment by fabatmo** [comment]
Hi
Thanks for letting mr know I have updated it.
Cheers
Fabian

**Comment by erciccione** [comment]
@fabatmo i see the mention of Monero in the terms of service, but i also see you add the logos of the currencies you accept there. Would be nice to see Monero as well (bitcoin is present). [Take a look at these](https://www.themonera.art/2017/09/22/monero-promotional-graphics-badges-and-stickers-for-websites/).

Beside, looks OK.

**Comment by fabatmo** [comment]
Hi 
Ok yes I see it automatically appears in my new web theme  which I will publish in a few days.
Attached is a picture. I can also add it here for sure its just really a matter of days before the new shop is published.
I am totally for crypto and I intend to offer a discount to anyone who pays with crypto on my site I just need to figure out the tech.
Many thanks
Fabian

**Comment by fabatmo** [comment]
Hi 
I still dont see symbolika listed in the list of merchants, is there an issue
please let me know

**Comment by erciccione** [comment]
@fabatmo This is a pull request to add your service to the list. As you can see the PR is still 'open' not 'merged'. After it will be merged the website will be updated and your service will show up.
