### ISSUE TITLE
Update the blockchain.raw download

### ISSUE THREAD

**Issue by viperperidot** [monero-project/monero-site#1273]
Would it be possible to get the blockchain.raw download updated at https://downloads.getmonero.org/blockchain.raw?

It is currently under the 2 million block height mark so it is a bit outdated.

This would be much appreciated.

Thank you

Edit: If this is better suited as a pull request please let me know and I can move it.

**Comment by viperperidot** [comment]
Didn't realize there was a Downloads repo so I made an issue there as well: https://github.com/monero-project/monero-downloads/issues/1

**Comment by erciccione** [comment]
@viperperidot this is being worked on. I'll post an update on this issue.

**Comment by viperperidot** [comment]
Thanks!

**Comment by erciccione** [comment]
The blockchain snapshot has been updated.
