### ISSUE TITLE
Add <Miller Technical Services> to the list of merchants

### ISSUE THREAD

**Issue by dmillerone** [monero-project/monero-site#1276]
#### What's the name of your business?

Miller Technical Services

#### What's the URL of the website?

http://www.miller-technical.com/

#### Write a brief description of your business/service (max 50 characters)

Discreet Product Development Services

#### Enter the URL where a Monero mention can be found

http://www.miller-technical.com/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [X] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Miller Technical Services believes in Monero like a zealot and preference will be provided to projects paying in Monero.

**Comment by erciccione** [comment]
Looks OK.
