### ISSUE TITLE
Remove 'Indacoin' from the list of merchants

### ISSUE THREAD

**Issue by l33d4n** [monero-project/monero-site#1285]
'Indacoin' offers dozens of cryptocurrencies available for purchase but Monero isn't one of them.

![image](https://user-images.githubusercontent.com/8020386/98056940-16122d00-1e7c-11eb-9e8e-475a1d890431.png)

---
List of supported cryptocurrencies:

![image](https://user-images.githubusercontent.com/8020386/98056483-08a87300-1e7b-11eb-9560-b9463f8b6a36.png)
---
https://github.com/monero-project/monero-site/blob/7a7ae92be334e2261ed1daf99cb5a624530b88ab/_data/merchants.yml#L62-L63

**Comment by erciccione** [comment]
Yes, Monero is not listed. I agree should be removed
