### ISSUE TITLE
Listing of Crypto.com

### ISSUE THREAD

**Issue by andrealiuu** [monero-project/monero-site#1286]
Hi Monero team, 

This is Andrea from Crypto.com and I hope your team is doing all well under the backdrop of COVID-19.

I am responsible for outreach on behalf of Crypto.com and I am outreaching to you because I have found there would be potential opportunities to deepen the relationship between Crypto.com and the Monero team. 

Crypto.com was founded in 2016 with the mission to accelerate the world's transition to cryptocurrency. Crypto.com is always actively building relationships with different token partners and one of the initiatives was launching the token price pages project where we create profile pages to promote different crypto projects. For instance, we have also created a dedicated page for Monero to show the latest market pulse and price movement with token information and an official website, we generate traffic and visibility for our partners with our effort on SEO, and our partners will get free publicity with our pages. You can find this page at https://crypto.com/price/monero and feel free to give us any comments to improve the page.

I just came across the Monero website and I have found there was a page https://www.getmonero.org/community/merchants/ showcase merchants & services which currently accept Monero for their goods and services. I am wondering if it is possible to list our logo with links directing to our page https://crypto.com/price/monero under the section - Tool as an honor for our long lasting working relationship?

No pressure at all for our pitch and we are looking forward to hearing from you soon. 

Thank you for your time and consideration!

Cheers,
Andrea

**Comment by erciccione** [comment]
Please use [the template](https://raw.githubusercontent.com/monero-project/monero-site/master/.github/ISSUE_TEMPLATE/new-merchant.md) to request to add a new service, as requested in the "Merchants" page.

**Comment by andrealiuu** [comment]
name: Crypto.com
about: Propose a new merchant to add to the 'Merchants' page
title: 'Add <Crypto.com> to the list of merchants'
labels: "\U0001F3EA merchant, \U0001F50D Needs investigation"
assignees: ''

---

#### What's the name of your business?

<Crypto.com>

#### What's the URL of the website?

<https://crypto.com/price/monero>

#### Write a brief description of your business/service (max 50 characters)

<Crypto.com launched its own exchange in 2019 and it complied with the highest security and compliance standard in the industry with the Cryptocurrency Security Standard (CCSS), ISO 27001:2013, ISO/IEC 27701:2019 and PCI:DSS 3.2.1 (Level 1) which made Crypto.com be the first crypto company to own all of these certificates at the same time. >

#### Enter the URL where a Monero mention can be found



https://crypto.com/price/monero

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- Exchange

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

**Comment by erciccione** [comment]
Please edit the original comment. Also, your brief description is longer than 50 characters requested and you didn't choose any option for "How do you accept Monero?"

**Comment by andrealiuu** [comment]
Our site doesn't support Monero currently, however, we have a page created for Monero at https://crypto.com/price/monero. Would it be possible to get listed on the Tool section at  https://www.getmonero.org/community/merchants/, linking to https://crypto.com/price/monero? 
Thanks

**Comment by erciccione** [comment]
@andrealiuu I don't see the point of adding you to the list of merchants who accept Monero if you don't accept Monero yet. We can add you once you actually support Monero :)

**Comment by erciccione** [comment]
I'm closing this issue for now. We don't add to the Merchants list merchants who don't presently accept Monero and i don't see why crypto.com would fit in the Tools section. Feel free to reopen when Monero will be accepted :)

**Comment by SamsungGalaxyPlayer** [comment]
Agreed, crypto.com can easily be included if Monero was supported.
