### ISSUE TITLE
W3C Validator errors list

### ISSUE THREAD

**Issue by l33d4n** [monero-project/monero-site#1289]
|#|URL|# Error|# Warning/Info|Total|Review|
|--- |--- |--- |--- |--- |--- |
|1|https://www.getmonero.org/|11|1|12|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2F)|
|2|https://www.getmonero.org/blog/|12|1|13|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fblog%2F)|
|3|https://www.getmonero.org/community/hangouts/|9|2|11|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fcommunity%2Fhangouts%2F)|
|4|https://www.getmonero.org/community/merchants/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fcommunity%2Fmerchants%2F)|
|5|https://www.getmonero.org/community/sponsorships/|9|2|11|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fcommunity%2Fsponsorships%2F)|
|6|https://www.getmonero.org/community/team/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fcommunity%2Fteam%2F)|
|7|https://www.getmonero.org/downloads/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fdownloads%2F)|
|8|https://www.getmonero.org/get-started/accepting/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fget-started%2Faccepting%2F)|
|9|https://www.getmonero.org/get-started/contributing/|9|2|11|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fget-started%2Fcontributing%2F)|
|10|https://www.getmonero.org/get-started/faq/|13|2|15|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fget-started%2Ffaq%2F)|
|11|https://www.getmonero.org/get-started/mining/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fget-started%2Fmining%2F)|
|12|https://www.getmonero.org/get-started/what-is-monero/|17|2|19|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fget-started%2Fwhat-is-monero%2F)|
|13|https://www.getmonero.org/legal/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Flegal%2F)|
|14|https://www.getmonero.org/library/|10|1|11|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Flibrary%2F)|
|15|https://www.getmonero.org/press-kit/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fpress-kit%2F)|
|16|https://www.getmonero.org/resources/about/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Fabout%2F)|
|17|https://www.getmonero.org/resources/developer-guides/|15|1|16|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Fdeveloper-guides%2F)|
|18|https://www.getmonero.org/resources/moneropedia/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Fmoneropedia%2F)|
|19|https://www.getmonero.org/resources/research-lab/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Fresearch-lab%2F)|
|20|https://www.getmonero.org/resources/roadmap/|84|39|123|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Froadmap%2F)|
|21|https://www.getmonero.org/resources/user-guides/|9|1|10|[Review](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.getmonero.org%2Fresources%2Fuser-guides%2F)|

**Comment by erciccione** [comment]
I often run Getmonero on the W3C validator. The vast majority of those errors are caused by the "unusual" way we create dropdowns, the rest are minor issues. Fixing some of those warnings/errors (mostly in the roadmap) is already in my todo list.

This issue in this format cannot be resolved, please edit it with more specific information or narrow it to only one page.
