### ISSUE TITLE
Add Fork Networking to the list of merchants

### ISSUE THREAD

**Issue by apezio** [monero-project/monero-site#1290]
#### What's the name of your business?

Fork Networking, Inc.

#### What's the URL of the website?

https://www.forked.net/

#### Write a brief description of your business/service (max 50 characters)

Provides Dedicated Servers and Virtual Private Servers (VPS).

#### Enter the URL where a Monero mention can be found

https://www.forked.net

#### How do you accept Monero? *(choose only one option)*

- [X] Native wallet

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [X] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Accepting Monero directly since 2017. Thanks!

**Comment by erciccione** [comment]
When trying to access the website through TLS, i get a BAD_CERT error. Please fix. We already link to `https://www.forked.net/` in [Sponsorships](https://www.getmonero.org/community/sponsorships/)

**Comment by erciccione** [comment]
ping @apezio

**Comment by erciccione** [comment]
ping.

**Comment by erciccione** [comment]
No answer. Closing.

**Comment by apezio** [comment]
Sorry, fixed this awhile ago but didn't reply here.  I was missing an intermediate chain cert. sigh.

**Comment by erciccione** [comment]
@apezio please edit the OP with the updated link. Note that it's still possible to access forked.net without TLS. That should be fixed.

**Comment by apezio** [comment]
Thanks, I have fixed that now.

**Comment by apezio** [comment]
#please edit the OP with the updated link.

@erciccione Done.
