### ISSUE TITLE
broken link how to ccs page

### ISSUE THREAD

**Issue by t-900-a** [monero-project/monero-site#1296]
On webpage: https://ccs.getmonero.org/how-to-ccs/

A link: <a href="/what-is-ccs">What is the CCS and What Are Its Rules and Expectations</a>

Why is it broken: the user is redirected to https://ccs.getmonero.org:8080/what-is-ccs/
It should be redirected to https://ccs.getmonero.org/what-is-ccs/

**Comment by 00-matt** [comment]
I think that this bug should be reported in the [ccs-frontend](https://repo.getmonero.org/monero-project/ccs-front) repository instead. This repository is just for the main getmonero.org website.

**Comment by t-900-a** [comment]
done: https://repo.getmonero.org/monero-project/ccs-front/-/issues/2
close
