### ISSUE TITLE
Shapeshift no longer offer Monero

### ISSUE THREAD

**Issue by davidhedlund** [monero-project/monero-site#130]
http://moneroinfo.org/eng-how-to-buy-monero/ says

> At this time, Monero is primarily available for Bitcoin through three primary exchanges: Shapeshift, Poloniex, and Bittrex.  There are currently no direct methods by which one can purchase Monero with fiat currencies on an exchange.

shapeshift.io no longer offer Monero (XMR), so can you remove that from the text?

**Comment by fluffypony** [comment]
@davidhedlund where did you hear they don't offer Monero any longer? It's sometimes unavailable on ShapeShift, but I've heard nothing about them removing it.

**Comment by davidhedlund** [comment]
@fluffypony 

> It's sometimes unavailable

Can you please add that disclaimer to avoid this report again?

**Comment by fluffypony** [comment]
@davidhedlund this repo isn't "moneroinfo.org", nor do I know who runs that site. Best you reach out to them:)

**Comment by davidhedlund** [comment]
@fluffypony Sorry, I posted in the wrong place.
