### ISSUE TITLE
Delete or simplify Moneropedia entry 'Canonically unique host'

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1308]
Is it really useful for the user? If it is, would be better to simplify it.

We can start working on this after #1270 is resolved.

**Comment by SamsungGalaxyPlayer** [comment]
I wonder to what extent we get random visitors on the getmonero.org page, lol. Seems to be the main resource available for this term.

![image](https://user-images.githubusercontent.com/12520755/103296579-f864ce00-49bb-11eb-88c5-bb386c05e3e1.png)

I agree with its removal.
