### ISSUE TITLE
DNS Cache Poisoning - Downloads Page

### ISSUE THREAD

**Issue by 3ach1T3ach1** [monero-project/monero-site#1310]
Please excuse if posting issue to the wrong location, forum or group.

I had a suspected dns spoofing event today multiple times while navigating to the downloads from the monero.org site. 

I was repeatedly being taken to a non https site that obviously looked different to the authentic site. I am able to navigate to what appears to be the https authentic site from my ip however notification of suspicious, malicious, grubby pleb actors targeting the monero.org site and it's clients is needed.

**Comment by erciccione** [comment]
Hi @3ach1T3ach1. The Monero website is https://getmonero.org.

monero[.]org is owned by a domain squatter and should be avoided and considered malicious.

**Comment by 3ach1T3ach1** [comment]
@erciccione Ah yes that is the plebs site. Thanks. I found it through a search while not paying enough attention. Any chance you have a protonmail I could contact you directly though? Privacy related issue concerning crypto. m461ck@protonmail.com

Thanks

**Comment by erciccione** [comment]
> Any chance you have a protonmail I could contact you directly though?

erciccione[at]protonmail[dot]com
