### ISSUE TITLE
Restyle 'Mining' page

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1315]
https://www.getmonero.org/get-started/mining/

It's very ugly and could use a refresh.

**Comment by tankmon354** [comment]
Please see if this redesign is suitable. Added more details to make the page less bare. Depending on whether it is necessary, you can move some contents from related user guides into this page to reduce the need to go to different pages.

[](https://www.figma.com/file/YAlL9ETwJi9QTiwE5zSSbs/GetMonero---Mining-Page?node-id=0%3A1)

**Comment by erciccione** [comment]
That looks very good @synxero354. The content needs to be adjusted and i would remove the transiction effects, but beside that i would be ok with this redesign.

**Comment by synxero354** [comment]
Definitely! I was not sure what content you were looking for so I took bits and pieces of what I thought would be appropriate. As for the transitions, it is just clicking between the 3 categories/subsections, they're not necessary.

**Comment by erciccione** [comment]
For the content, i would say it's fine as it is for now. except the adjustments i mentioned, but those can be done when the PR is open.

**Comment by erciccione** [comment]
@synxero354 do you plan to PR your redesign?

**Comment by synxero354** [comment]
@erciccione I am still figuring out how to use Jekyll as this is all new to me. Sorry for the delay.

**Comment by erciccione** [comment]
Take a look at the README of this repo. There are extensive instructions. If you need any help, join the chatroom on Freenode or matrix (details also in the README)

**Comment by erciccione** [comment]
I opened a PR@ #1656. I like @synxero354's design, but at the end i don't think we have enough content for a submenu in the page. So i offered a simplified version, but kept the comparison between solo and pool mining.
