### ISSUE TITLE
Veldt Gold

### ISSUE THREAD

**Issue by airos999** [monero-project/monero-site#1316]
#### What's the name of your business?
Veldt Gold

#### What's the URL of the website?

https://veldtgold.com/

#### Write a brief description of your business/service (max 50 characters)

Buy and sell gold and silver bullion with Monero 

#### Enter the URL where a Monero mention can be found

https://veldtgold.com/payment-shipping-information/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

cryptowoo monero add on

#### How would you categorize your business? *(choose only one option)*

- [x ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Veldt Gold is an online retailer specializing in the trade/exchange of gold, silver, platinum, palladium for Monero

**Comment by erciccione** [comment]
Looks ok, but i would categorize your business as "Goods" not "Exchange".
