### ISSUE TITLE
Add SphinxLogic to the list of merchants

### ISSUE THREAD

**Issue by kgsphinx** [monero-project/monero-site#1324]
#### What's the name of your business?

SphinxLogic

#### What's the URL of the website?

https://sphinxgadgets.com

#### Write a brief description of your business/service (max 50 characters)

Maker of Alternative Password Manager Gadgets

#### Enter the URL where a Monero mention can be found

The Monero Collection page mentions it, plus there are Monero icons in the footer of most pages alongside the other payment options.

https://sphinxgadgets.com/collections/monero-collection

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [X] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks ok.
