### ISSUE TITLE
Add Backtestking to the list of merchants

### ISSUE THREAD

**Issue by nieuwamsterdam** [monero-project/monero-site#1329]
#### What's the name of your business?
Backtestking

#### What's the URL of the website?

https://www.backtestking.com

#### Write a brief description of your business/service (max 50 characters)

Build or buy your own trading strategy/bot.

#### Enter the URL where a Monero mention can be found

https://www.backtestking.com/build-trading-bot

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [X] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Backtestking accepts only Monero

**Comment by erciccione** [comment]
The cookies pop up is quite annoying, but beside looks ok.

**Comment by nieuwamsterdam** [comment]
Thanks, Does the popup stay? It is supposed to be a one-time event.

**Comment by erciccione** [comment]
I don't know. i couldn't click on it, but that's because of my strict browser settings (for privacy reasons)
