### ISSUE TITLE
Add 1bit.group Anonymous exchange to the list of merchants

### ISSUE THREAD

**Issue by 1Bit-Group** [monero-project/monero-site#1349]
#### What's the name of your business?

1Bit.Group

#### What's the URL of the website?

https://1bit.group

#### Write a brief description of your business/service (max 50 characters)

Anonymous Monero exchanger

#### Enter the URL where a Monero mention can be found

https://1bit.group

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [+] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [+] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Please add our automatic anonymous online exchanger to the list of exchangers

**Comment by erciccione** [comment]
They list Monero.

**Comment by 1Bit-Group** [comment]
Good afternoon.
And we are not currently on the Exchanges list.
We will appear after updating your site as we understood correctly?

**Comment by erciccione** [comment]
You will be listed after this PR will be merged and the website updated.
