### ISSUE TITLE
Add FAQ: 'How big is the Monero blockchain?'

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1371]
Maybe 'Why does the blockchain need so much space?' will need to be adjusted.

**Comment by tonyern** [comment]
Do you know what {% t faq.qblockspace %} is and where I can edit these?

**Comment by erciccione** [comment]
> Do you know what {% t faq.qblockspace %} is and where I can edit these?

https://github.com/monero-project/monero-site/blob/master/_i18n/en.yml#L433

Instructions to edit every section are in the README of this repository.

**Comment by tonyern** [comment]
Thank you! The README didn't said where to find the files to edit the FAQ.

**Comment by erciccione** [comment]
Resolved by #1442
