### ISSUE TITLE
SSL timeout!

### ISSUE THREAD

**Issue by iPhonePKAndroid** [monero-project/monero-site#1377]
https://api.mymonero.com:8443/

https://wallet.mymonero.com/

https://*.mymonero.com/

**Comment by iPhonePKAndroid** [comment]
Has expired!

**Comment by cutff** [comment]
I have some coins on mymonero ? what happened to my coins lost ?

**Comment by selsta** [comment]
You can import your MyMonero seed into a different monero wallet if you have to access your funds.

**Comment by iPhonePKAndroid** [comment]
> You can import your MyMonero seed into a different monero wallet if you want access to your funds.

Do you have any recommendations?

**Comment by selsta** [comment]
https://www.getmonero.org/downloads/

**Comment by iPhonePKAndroid** [comment]
thanks

**Comment by selsta** [comment]
I assume MyMonero will be fixed in the next 12-24h.

**Comment by iPhonePKAndroid** [comment]
maybe

**Comment by iPhonePKAndroid** [comment]
There are so many people using it, why it expires, they should receive the expired email in advance, a reminder from the SSL service provider.

**Comment by cutff** [comment]
I have used cake wallet and I have tried to restore all my funds. but after it done it shows like some new wallets

One calls 
Hateful Red and one Scaly Panties ? 

What is that ? please anyone can help me out here. I feel like I have lost my coins or what ? 

Thank you

**Comment by cutff** [comment]
and there is no funds

**Comment by selsta** [comment]
You did nor lose your funds. MyMonero will should back online in 12-24 hours.

Which restore height did you set in cake wallet?

**Comment by cutff** [comment]
I have just tried Cake wallet as I was afraid I am gonna lose my funds. by after synchronization. there were no funds and two more wallets automatically created as above. I don't know really What I am supposed to do now. can I be back tomorrow in case mymonero is back online again? Thank you very much

**Comment by selsta** [comment]
> can I be back tomorrow in case mymonero is back online again?

Yes.

**Comment by cutff** [comment]
so tomorrow I can just use the same seeds I had before with them to log in again? and just forget about cake or what? I am really sorry I am new to Monero. so much appreciated  with feedbacks here

**Comment by selsta** [comment]
Correct.

**Comment by cutff** [comment]
oh God! I am back to life again. Thank you very much. sincerely appreciated. 
❤️

**Comment by selsta** [comment]
The issue appears resolved.

**Comment by erciccione** [comment]
This is the repository for getmonero.org, not mymonero.

**Comment by cutff** [comment]
my bad bringing the topic here.  my apologizes!
