### ISSUE TITLE
Add Actio-fast-pay.net to the list of merchants

### ISSUE THREAD

**Issue by actio-fast-pay** [monero-project/monero-site#1388]
#### What's the name of your business?

Actio-fast-pay.net

#### What's the URL of the website?

https://actio-fast-pay.net/

#### Write a brief description of your business/service (max 50 characters)

Automatic exchanger 24x7

#### Enter the URL where a Monero mention can be found

https://actio-fast-pay.net/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [*] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [*] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Automatic exchanger 24x7

**Comment by erciccione** [comment]
Lists Monero.

**Comment by erciccione** [comment]
#1404
