### ISSUE TITLE
Add user guide 'How to create a private remote node?'

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1389]
Could also be more in general 'How to create a remote node?' and then add instructions for both public and private remote nodes. We could link to it from the "Remote Node" Moneropedia entry.

**Comment by erciccione** [comment]
Consider we already have: https://www.getmonero.org/resources/user-guides/vps_run_node.html

**Comment by HoverHalver** [comment]
There is indeed also https://www.getmonero.org/resources/user-guides/vps_run_node.html
and installing a private remote node being just quite the same procedure, minus the need to open the node,
such a guide would have 90% overlap with this existing guide.
