### ISSUE TITLE
Add "General Fund" Viewkey to the ccs.getmonero.org page

### ISSUE THREAD

**Issue by johnr365** [monero-project/monero-site#1390]
Currently the https://ccs.getmonero.org/ page shows the general fund address, but it doesn't show the viewkey for this address.

To see the viewkey you pretty much need to know it's at Github, part way down this page: https://github.com/monero-project/monero

I would suggest that for the CSS homepage, in the footer, where the text says:

"Donate to the Monero Project

By donating to the following Monero address (General Fund), you are supporting the Monero Project. If you wish to donate to a specific proposal, please see Funding Required."

We add underneath something like: "To view donations to this address, use the viewkey: f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501"

The viewkey is already public, and aids with transparency - which should encourage donations. Also a powerful feature of Monero that should be demonstrated and taken advantage of!

Let me know your thoughts?

**Comment by erciccione** [comment]
The repository for ccs.getmonero.org is here: https://repo.getmonero.org/monero-project/ccs-front. Please reopen this issue there.

**Comment by johnr365** [comment]
My bad @erciccione - thanks for the info - will re-post it over there! Merry Xmas :)
