### ISSUE TITLE
link to monero hashes.txt outdated

### ISSUE THREAD

**Issue by adrelanos** [monero-project/monero-site#1419]
`https://github.com/monero-project/monero-gui/releases/tag/v0.17.1.9` links to

* `https://getmonero.org/downloads/hashes.txt` which then redirects to
* `https://www.getmonero.org/downloads/hashes.txt`.

This makes it a bit harder to web archive these links.

If the location change is permanent, please consider updating that link for the next release.

**Comment by erciccione** [comment]
See my answer in https://github.com/monero-project/monero-gui/issues/3189#issuecomment-760892256

regardless, the link displayed should be changed in the blog posts to avoid confusions. i'll take care of that.

**Comment by erciccione** [comment]
> he link displayed should be changed in the blog posts to avoid confusions. i'll take care of that.

Done with #1421
