### ISSUE TITLE
Adding new language to Weblate for Monero Site

### ISSUE THREAD

**Issue by tonyern** [monero-project/monero-site#1431]
I am seeing if someone can start a new language on Weblate for the GetMonero site. The language is Vietnamese and its two letter code is "vi".

**Comment by erciccione** [comment]
Done: https://translate.getmonero.org/projects/getmonero/monero-site/vi/

The GUI is already partially translated, but definitely needs a lot of work: https://translate.getmonero.org/projects/monero/gui-wallet/vi/

**Comment by tonyern** [comment]
Thanks!
