### ISSUE TITLE
Many RPC commands have been renamed or delated

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1434]
We need to make a thorough refresh of the dev guides to check which commands have been renamed/deleted/added.

https://www.getmonero.org/resources/developer-guides/daemon-rpc.html
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html

**Comment by erciccione** [comment]
daemon-rpc is PRd in #1448. wallet-rpc is in progress.

**Comment by ndorf** [comment]
> wallet-rpc is in progress.

Is someone actively working on this? I'd like to help, would be nice to avoid duplicating effort.

**Comment by erciccione** [comment]
@ndorf not yet. I plan to start after #1448 will get some attention, but if you want to take care of it already. Sure, go ahead :)

**Comment by erciccione** [comment]
Actually, please let me know if you intend to start working on the wallet-rpc user guide. So i can assign this issue to you as well.

**Comment by ndorf** [comment]
I'm happy to help with the wallet, daemon or both guides. Please assign whatever you feel like to me.

**Comment by erciccione** [comment]
Awesome, then would be great to start by providing the definitions for #1448, if you can :)

**Comment by erciccione** [comment]
Note that more calls have been added since #1448. So after that's merged we should take another look and see what's missing.

**Comment by erciccione** [comment]
We can consider this resolved.
