### ISSUE TITLE
Add <Data Records Corp. - Marketing and Lead Generation> to the list of merchants

### ISSUE THREAD

**Issue by seniorboobies** [monero-project/monero-site#1440]
https://www.datarecordscorp.com/

**Comment by l33d4n** [comment]
Please use [the template](https://raw.githubusercontent.com/monero-project/monero-site/master/.github/ISSUE_TEMPLATE/new-merchant.md) to request to add a new service, as requested in the "Merchants" page.

**Comment by erciccione** [comment]
ping @seniorboobies you actually deleted the template and replaced it with a simple URL. Please use the full template or we will just close this issue.
