### ISSUE TITLE
Add Bacrypt.com to the list of merchants

### ISSUE THREAD

**Issue by Bacrypt** [monero-project/monero-site#1444]
#### What's the name of your business?

Bacrypt.com

#### What's the URL of the website?

https://bacrypt.com/

#### Write a brief description of your business/service (max 50 characters)

Fully anonymous exchange

#### Enter the URL where a Monero mention can be found

https://bacrypt.com/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [+] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [+] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Fully anonymous exchange

**Comment by erciccione** [comment]
> Fully anonymous

This is not a description. A short description should make a potential user understand what you are offering in few words.

**Comment by Bacrypt** [comment]
Corrected
Fully anonymous exchange

**Comment by erciccione** [comment]
#1468
