### ISSUE TITLE
Add CelticGold.eu to the list of merchants

### ISSUE THREAD

**Issue by jirn073-76** [monero-project/monero-site#1449]
#### What's the name of the business?

CelticGold AG

#### What's the URL of the website?

https://www.celticgold.eu/

#### Write a brief description of the business/service 

You can buy and sell precious metals via crypto.

#### Enter the URL where a Monero mention can be found

https://www.celticgold.eu/gold-und-silber-mit-krypto-waehrungen-zahlen
or, the English version
https://www.celticgold.eu/en/pay-gold-silver-with-crypto-currencies

#### How does the site accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc.)

#### How would you categorize the business?

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks OK.

**Comment by erciccione** [comment]
#1468
