### ISSUE TITLE
Add RPC Golang library under Libraries and helpers

### ISSUE THREAD

**Issue by MarinX** [monero-project/monero-site#1453]
Full RPC client written in Go:

[https://github.com/MarinX/monerorpc](https://github.com/MarinX/monerorpc)

Difference from other go libraries:
- Wallet and Daemon client
- Up to date (Wallet RPC version 1.3) (will try to keep it up to date with monero docs)
- Go module support
- Documented
- Written tests (wallet and daemon)

**Comment by erciccione** [comment]
This is a brand new library with only 2 commits. We don't do any vetting, but would be good to have at least the confirmation (from somebody external to the project) that it works.

**Comment by MarinX** [comment]
@erciccione , understandable.
I will close this issue and re-open again once I have a list of people/projects using this library.
Thank you for the input.
