### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by cryptoairck** [monero-project/monero-site#1456]
#### Enter the URL where a Monero mention can be found

https://stats-auto-spa.com/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [x ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Coinpayments*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Please edit the title, fill up all sections and 

> How would you categorize your business? (choose only one option)

you chose two options.

**Comment by cryptoairck** [comment]
Goods

**Comment by erciccione** [comment]
> Please edit the title, fill up all sections

**Comment by erciccione** [comment]
Invalid. Feel free to reopen once all sections will be filled.
