### ISSUE TITLE
Add <YogiWay> to the list of merchants

### ISSUE THREAD

**Issue by Peter-Liska** [monero-project/monero-site#1460]
#### What's the name of your business?

YogiWay

#### What's the URL of the website?

https://yogiway.cz/

#### Write a brief description of your business/service (max 50 characters)

yoga mats, bags and yoga accessories

#### Enter the URL where a Monero mention can be found

https://yogiway.cz/content/1-doprava-a-platba

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
A correctly completed request, a rare sight! :P

Looks OK.

**Comment by SydBal** [comment]
Cross posting a link to the PR for visibility: https://github.com/monero-project/monero-site/pull/1467

**Comment by SydBal** [comment]
@Peter-Liska YogiWay has been added to the list of merchants. https://www.getmonero.org/community/merchants/

**Comment by Peter-Liska** [comment]
Nice &#x1F44D;
