### ISSUE TITLE
Add <BuyVM> to the list of merchants

### ISSUE THREAD

**Issue by boldsuck** [monero-project/monero-site#1462]
#### What's the name of your business?

BuyVM / Frantech

#### What's the URL of the website?

https://buyvm.net/

#### Write a brief description of your business/service (max 50 characters)

Dedicated KVM Slices, Block Storage Slabs & Hosting

#### Enter the URL where a Monero mention can be found

https://buyvm.net/top-10-reasons-to-choose-buyvm/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [X] Other payment gateaway (Coinpayments)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [X] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Affordable Hosting with a touch of Insanity.
[IRC](https://wiki.buyvm.net/doku.php/irc/main) <-> [Discord](https://buyvm.net/beware-the-moshbear/) community chat
Tor Exit, Relay, and Bridge https://buyvm.net/acceptable-use-policy/

**Comment by boldsuck** [comment]
I've been a satisfied customer for a long time. (Monero node & Tor exits)
BuyVM Stock is rare and often something is available at the beginning of the month. It is worth the effort to get some.
You can mount/install your own ISO's, manage routed /48's for each KVM, use an isolated LAN for private networks and your own BGP prefixes (ASN), if any.

**Comment by erciccione** [comment]
Looks OK.

**Comment by erciccione** [comment]
#1468
