### ISSUE TITLE
Add GetBlock to the list of merchants

### ISSUE THREAD

**Issue by wetryingtodorock** [monero-project/monero-site#1465]
#### What's the name of your business?

GetBlock

#### What's the URL of the website?

https://getblock.io

#### Write a brief description of your business/service (max 50 characters)

Blockchain Nodes Provider

#### Enter the URL where a Monero mention can be found

https://getblock.io/nodes/xmr

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [x] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

GetBlock provides access to the XMR full node via JSON-RPC.
Endpoint: xmr.getblock.io

**Comment by erciccione** [comment]
> How do you accept Monero? (choose only one option)

Choose one option

**Comment by wetryingtodorock** [comment]
> > How do you accept Monero? (choose only one option)
> 
> Choose one option

We don't accept payments in Monero, but we provide access to the XMR node

**Comment by erciccione** [comment]
I'm not sure any of the sections on the merchants page would be a good fit for your service. Maybe would be better to put it somewhere else on the website.

**Comment by wetryingtodorock** [comment]
I've seen that the NOWNodes (Explorer & Node APIs) service is in the Tools section, so I thought we could fit there too. But if you have any other more suitable place for GetBlock on your website, please, let me know!

**Comment by erciccione** [comment]
The 'Tools' section will be fine then.

**Comment by wetryingtodorock** [comment]
Thank you!

**Comment by erciccione** [comment]
#1468
