### ISSUE TITLE
Add <PAY2DAY.TOP> to the list of merchants

### ISSUE THREAD

**Issue by Pay2day-top** [monero-project/monero-site#1469]
#### What's the name of your business?

 **PAY2DAY.TOP**

#### What's the URL of the website?

https://pay2day.top

#### Write a brief description of your business/service (max 50 characters)

PAY2DAY.TOP - Buy and sell cryptocurrency.

#### Enter the URL where a Monero mention can be found

https://pay2day.top
https://pay2day.top/xchange_XMR_to_CARDRUB

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
-  Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

-  Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

PAY2DAY. TOP - Buying and selling cryptocurrency for rubles. Cash, Sberbank, QIWI, MTC, YAD, VISA / MasterCard RUB, MIR, RNKB, BTC, LTC, ETH, Monero.
Quickly, profitably, without registration and SMS.

**Comment by erciccione** [comment]
They accept XMR

(note to self: specifythat they are Ru only)

**Comment by erciccione** [comment]
#1468
