### ISSUE TITLE
Flokinet no longer accepts Monero

### ISSUE THREAD

**Issue by archerships** [monero-project/monero-site#1470]
FYI, Flokinet no longer appears to accept Monero:

![Screen Shot 2021-02-15 at 1 08 15 AM](https://user-images.githubusercontent.com/77993343/107926311-68a6bf00-6f2a-11eb-928a-adf358b9a528.png)

**Comment by erciccione** [comment]
They still list it in their footer. They are probably using a payment processor which stopped supporting Monero.

**Comment by erciccione** [comment]
#1471
