### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by ankan53** [monero-project/monero-site#1473]
#### What's the name of your business?

airpodsskydd.se

#### What's the URL of the website?

 https://www.airpodsskydd.se/

#### Write a brief description of your business/service (max 50 characters) Cellphone and computer accessories store in Sweden

<Cellphone and computer accessories store in Sweden

#### Enter the URL where a Monero mention can be found https://airpodsskydd.se

https://airpodsskydd.se

#### How do you accept Monero? *(choose only one option)*

+ [x] Monero integrations *(github.com/monero-integrations)* yes
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
+[ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
>  accessories for: Airpods, Computers, Mobiles. car Keychains, Wallets. Available in Sweden 

These are not max 50 characters

> Tool

You are not offering a tool, you sell goods. Please change to that category

**Comment by ankan53** [comment]
ok fixed

**Comment by erciccione** [comment]
Something went wrong. The description field is empty.

**Comment by ankan53** [comment]
description: Cellphone and computer accessories store in Sweden

**Comment by erciccione** [comment]
Please edit the title of the issue with the name of the merchant you want to add. Now it says "<NAME OF YOUR BUSINESS>"

**Comment by erciccione** [comment]
ping

**Comment by erciccione** [comment]
Abandoned.
