### ISSUE TITLE
Can't access my 24 words seed within the wallet

### ISSUE THREAD

**Issue by Folderguion** [monero-project/monero-site#1474]
Hello,

I have my wallet perfectly working in Linux, connected with my Ledger device. But can't access my SEED to copy and make a backup. The wallet says the seed is protected by device. I open the Monero App in Ledger, when going to settings > show 25 words, there are 2 options: 
1- Electrum Seed: NOTSET  
2- CLEAR WORDS says only {do not wipe the wallet}

And nothing happen. So, how can I re-access my seed to backup?

Thank you

**Comment by erciccione** [comment]
This is the repository of the getmonero.org. For support please use reddit or the chat `#monero` on Freenode or Element (matrix)
