### ISSUE TITLE
Accessibility with Voiceover on Mac OS

### ISSUE THREAD

**Issue by aureliomuth** [monero-project/monero-site#1475]
Hi,
I'm a blind user Getmonero app on Mac OS. It isn't accessible with my screen reader, Voiceover. I can't use it myself. So, can you do something?
Thank you very much!

**Comment by erciccione** [comment]
Could you specify in more detail in what way "it isn't accessible"? We recently improved our accessibility score and there shouldn't be big problems with accessing and browsing getmonero.

**Comment by aureliomuth** [comment]
Thank you!
When I created my wallet, the Voiceover said just “horizontal slider . Nothing else. And when I created the walle, I can’t read every tabs and buttons.


Aurel Calin Muth

**Comment by erciccione** [comment]
I see. Then the problem you are having is related to the Monero GUI wallet. This is the repository of the getmonero.org website. Please reopen this issue on the repository of the GUI. Direct link to open an issue in the correct repo: https://github.com/monero-project/monero-gui/issues/new.

**Comment by erciccione** [comment]
@aureliomuth i opened an issue for you in the repository of the GUI wallet: https://github.com/monero-project/monero-gui/issues/3343

**Comment by aureliomuth** [comment]
Thank you very much!

Aurel Calin Muth
