### ISSUE TITLE
Revise "What is Monero?" page

### ISSUE THREAD

**Issue by wirrickelliot** [monero-project/monero-site#1480]
The wording on the page could use some revision to help it appear a bit more professional.

For example, these two sentences are essentially redundant:
![image](https://user-images.githubusercontent.com/23042683/109233331-ad86ed00-7797-11eb-8420-9d15c3712767.png)

**Comment by wirrickelliot** [comment]
Would it be better to put the video at the top of the page? It's easily overlooked at the moment.

![image](https://user-images.githubusercontent.com/23042683/111055007-678c8300-843f-11eb-9aa9-c74ad347ac48.png)

**Comment by erciccione** [comment]
I considered it and briefly tried it, but i wasn't really enthusiast about how it looked, but if people prefer it up there, we can just move it.
