### ISSUE TITLE
Including Chinese Translation

### ISSUE THREAD

**Issue by ChristopherKing42** [monero-project/monero-site#149]
Monero has increased in popularity lately, and Chinese users may be interested. Given that the Chinese government is quite oppressive at times, many of the Chinese would probably find Monero useful.

Apparently the translation has already been done and is just waiting to be merged. If so, it would be nice if it where merged.

**Comment by rehrar** [comment]
@ChristopherKing42 translation technologies is being looked at for the new redesign of getmonero.org. In the meantime, it would be helpful to close this issue. :)

**Comment by QuickBASIC** [comment]
Since #453 has a more generic description and more discussion. Should we go ahead and close this issue? Or rename this issue and close the other as duplicate?

@rehrar @luigi1111

**Comment by mattcode55** [comment]
After #527 is merged this should be easy to do :)

**Comment by erciccione** [comment]
[Somebody is working on this](https://taiga.getmonero.org/project/erciccione-monero-localization/task/110)
+In progress

**Comment by rehrar** [comment]
As translations are now be tracked in Taiga via the Monero Translations workgroup, I say we should close this issue. @erciccione
