### ISSUE TITLE
[IDEA] Add popup with information related to AV software for Mac OS and Windows GUI downloads

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-site#1494]
AV software typically flags Monero as 'unintended' software (predominantly due to a miner being included). New users are typically affected by this and it may scare them. Whilst we have a proper FAQ on the matter, it would probably be worthwhile to add a small pop-up to inform the user before they download the software.

**Comment by erciccione** [comment]
We already have a warning in the Downloads page. Actually, two, one for the CLI and one for the GUI: `Be aware that some antiviruses and firewalls may flag the Monero executables and archives as malware. More info in the FAQ.(link)`

**Comment by erciccione** [comment]
I added a simple header ('Antivirus') with #1500. It's meant to catch the user attention. Please let me know if you have improvements to suggest.

**Comment by dEBRUYNE-1** [comment]
Looks good to me. Hopefully it will make more users aware. I think the previous warning is not sufficiently visible.
