### ISSUE TITLE
Replace the 'MONERO' header in the homepage with something more informative

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1503]
As discussed in #1483, the MONERO header inthe homepage is redundant and that valuable space could be used for something with more impact on the visitor.

I think we have three options:

1. Replace the MONERO header with something else and keep 'A private DigitalCurrency' under it
2. Remove both headers and replace them with a 2 different headers.
3. Remove both headers and replaced with 1 single header

What of the three options do you prefer?
What headers(s) should we use?

**Comment by dEBRUYNE-1** [comment]
What about:

'Monero - The private, decentralized cryptocurrency that keeps your finances confidential and secure.'

**Comment by erciccione** [comment]
@dEBRUYNE-1 I guess that's a suggestion for option 3. It's a bit too long in my opinion. Ideally we would have something short and of immediate impact.

**Comment by Gingeropolous** [comment]
"Monero means money"

And I would make the call to action mentioned before something that focuses on getting a wallet. "Joining the community" is fine, but most ppl out there probably don't care about the community, they want to see the technology work. So "Get a wallet" or something.

**Comment by erciccione** [comment]
To clarify, this is what this issue is about:

![1](https://user-images.githubusercontent.com/28106476/118479084-e2f50400-b710-11eb-8f3d-f945bc6ea475.png)

For suggestions about the structure of the top card in general, better #1483.

@Gingeropolous i like Monero means money as the main header, but "A Private Digital Currency" under would be redundant.

**Comment by Gingeropolous** [comment]
Yeah, I would drop "A Private Digital Currency". Just do a single header I guess if "monero means money" makes the most sense.

**Comment by erciccione** [comment]
Soemthing like this? (it's a very quick mock up, just to give an idea)

![head](https://user-images.githubusercontent.com/28106476/118497405-556fdf00-b725-11eb-8e62-a13c41c48f25.png)

**Comment by xmrhaelan** [comment]
I like @SamsungGalaxyPlayer initial suggestion. It’s at least much better than what currently exists.

**Comment by SamsungGalaxyPlayer** [comment]
The benefit of my original suggestion is that it goes on the offense and clearly states Monero's position as a widely used payment standard.

I am okay with the main header being "Monero means money" however, or similar.

I also really believe we will need 2 calls to action in the top card also, such as the ones I included in my original draft.

**Comment by erciccione** [comment]
We have two suggestions on this thread:

@dEBRUYNE-1's:
![tr](https://user-images.githubusercontent.com/28106476/118613421-07a7b500-b7bf-11eb-9fff-959e4a6bfbfa.png)


@SamsungGalaxyPlayer's:
![sgp](https://user-images.githubusercontent.com/28106476/118613286-e6df5f80-b7be-11eb-8d08-7cf75c77857e.png)

Note that the main header can be all uppercase or mixed case depending by what people prefers.

Should we vote? Should we ask on reddit?

**Comment by erciccione** [comment]
#1633

**Comment by SamsungGalaxyPlayer** [comment]
Informal poll:

![image](https://user-images.githubusercontent.com/12520755/121924921-fd1b0580-cd01-11eb-9f95-f58b69b4cfe6.png)
