### ISSUE TITLE
Add 24bestex.com to the list of merchants

### ISSUE THREAD

**Issue by best24dev** [monero-project/monero-site#1510]
#### What's the name of your business?

24bestex.com

#### What's the URL of the website?

https://24bestex.com/

#### Write a brief description of your business/service (max 50 characters)

24bestex - cryptocurrency exchanger

#### Enter the URL where a Monero mention can be found

https://24bestex.com/en/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
They list Monero, but we are not going to add this merchant with the description `safe cryptocurrency exchanger`, the word *safe* might give the feeling that is the getmonero.org website to consider it *safe*, but that's not the case. We can add `24bestex.com - cryptocurrency exchanger`

**Comment by best24dev** [comment]
> They list Monero, but we are not going to add this merchant with the description `safe cryptocurrency exchanger`, the word _safe_ might give the feeling that is the getmonero.org website to consider it _safe_, but that's not the case. We can add `24bestex.com - cryptocurrency exchanger`

I agree with your statement

**Comment by erciccione** [comment]
No reason to not add it as far as i can tell.
