### ISSUE TITLE
Add 1984 Hosting to the list of merchants

### ISSUE THREAD

**Issue by sigurdurthorfinnureinarsson** [monero-project/monero-site#1512]
#### What's the name of your business?

1984 Hosting Iceland

#### What's the URL of the website?

https://1984hosting.com

#### Write a brief description of your business/service (max 50 characters)

Privacy concerned hosting for freedom fighters.

#### Enter the URL where a Monero mention can be found

https://1984hosting.com/pricelist

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [x] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment
We added Monero after receiving requests to do so from clients concerned about the lack of privacy and fees provided by Bitcoin which we already accept.

**Comment by erciccione** [comment]
> https://1984hosting.com/pricelist

I guess you meant https://1984hosting.com/product/pricelist/ :)

> We added Monero after receiving requests to do so from clients concerned about the lack of privacy and fees provided by Bitcoin which we already accept.

Great to hear!

Looks OK.

**Comment by erciccione** [comment]
#1525
