### ISSUE TITLE
Add CoinCat.in to the list of merchants

### ISSUE THREAD

**Issue by CoinCatEx** [monero-project/monero-site#1516]
#### What's the name of your business?

CoinCat

#### What's the URL of the website?

https://coincat.in/

#### Write a brief description of your business/service (max 50 characters)

Buy and sell crypto in minutes.

#### Enter the URL where a Monero mention can be found

https://coincat.in/
https://coincat.in/en/exchange-CARDRUB-to-XMR
https://coincat.in/en/exchange-XMR-to-CARDRUB

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

We offer fast crypto to fiat exchange service (at the moment for Russian users only)

**Comment by erciccione** [comment]
Looks ok. Since the website is Russian only we should probably add something like `(Ru)` near the name.

**Comment by erciccione** [comment]
#1525
