### ISSUE TITLE
Add Actio-fast-pay.net to the list of merchants

### ISSUE THREAD

**Issue by actio-fast-pay** [monero-project/monero-site#1519]
#### What's the name of your business?

Actio-fast-pay.net

#### What's the URL of the website?

https://actio-fast-pay.net/

#### Write a brief description of your business/service (max 50 characters)

Automatic exchanger 24x7

#### Enter the URL where a Monero mention can be found

https://actio-fast-pay.net/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [*] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [*] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Please add our exchanger back to the list, as it was removed by mistake, we were accused of fraud without providing any evidence so you can accuse any service and all services are removed from the lists, we believe that this is a competitor provakatsiyu. Please also remove unconfirmed provakatsiya.

**Comment by erciccione** [comment]
Your exchange is still listed on getmonero, but will be removed soon (#1514). We received multiple complaints about Actio-fast-pay.net, we found the complains credible, so we are removing the merchant from the list.
