### ISSUE TITLE
Moneropedia - RingCT

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#152]
The following text should be added to the Moneropedia for RingCT:

RingCT, short for ring confidential transactions, is a way to hide the amount sent in a Monero transaction. This feature is currently in the testnet phase and is a high development priority.

RingCT introduces an improved version of [ring signatures](https://getmonero.org/knowledge-base/moneropedia/ringsignatures) called A Multi-layered Linkable Spontaneous Anonymous Group signature, which allows for hidden amounts, origins and destinations of transactions with reasonable efficiency and verifiable, trustless coin generation.

For more information, please read the creator Shen Noether's paper [here](http://eprint.iacr.org/2015/1098).

**Comment by Hueristic** [comment]
Excellently worded.

**Comment by palexande** [comment]
Done
