### ISSUE TITLE
Add www.trilightzone.org to the list of merchants

### ISSUE THREAD

**Issue by trilightzone** [monero-project/monero-site#1520]
#### What's the name of your business?

TrilightZone

#### What's the URL of the website?

https://trilightzone.org/

#### Write a brief description of your business/service (max 50 characters)

Anonymous offshore services since 2005

#### Enter the URL where a Monero mention can be found

https://www.trilightzone.org/board/index.php/topic,12.0.html

And on each page footer XMR payment symbol 

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [X]] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Started a couple of years ago when we got clients asking about Monero.
After carefully reviewing and considering the whole picture of Monero
we feel this is one of the best alternatives to traditional payment methods
and its anonymity and security increasing features are a huge plus.

**Comment by erciccione** [comment]
Thanks for opening the issue :)

OK

**Comment by trilightzone** [comment]
Thank you and keep up the good work !

**Comment by erciccione** [comment]
#1525
