### ISSUE TITLE
Add 1plus.world to the list of merchants

### ISSUE THREAD

**Issue by 1Plus-World** [monero-project/monero-site#1524]
#### What's the name of your business?

1plus.world

#### What's the URL of the website?

https://1plus.world/

#### Write a brief description of your business/service (max 50 characters)

1plus.world - Instant anonymous crypto exchange

#### Enter the URL where a Monero mention can be found

https://1plus.world/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [+] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [+] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
NACK

**Comment by luigi1111** [comment]
Very likely scam. If someone wants to investigate, go ahead. Closing for now.

**Comment by Abi-ko** [comment]
Hello 
Please tell me why you closed our issue, and linked us to another exchanger?
