### ISSUE TITLE
Moneropedia - Blockchain

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#153]
The following page on Blockchain should be updated to the following:

A distributed ledger of all transactions both past and present. This ledger is made up of a series of [blocks](https://getmonero.org/knowledge-base/moneropedia/block). In Monero, the blockchain does not reveal who the funds came from or went to. To see how the blockchain is obscured, see [ring signatures](https://getmonero.org/knowledge-base/moneropedia/ringsignatures).

**Comment by palexande** [comment]
Done.
