### ISSUE TITLE
Add digitalgoods by ProxyStore to the list of merchants

### ISSUE THREAD

**Issue by b068931cc450442b63f5b3d276ea4297** [monero-project/monero-site#1536]
#### What's the name of your business?

digitalgoods by ProxyStore

#### What's the URL of the website?

https://digitalgoods.proxysto.re/
http://digitazyyxyihwwzudp5syxxyn3qhcd63wqcha2dxpfqiyydmrgdiaad.onion/

#### Write a brief description of your business/service (max 50 characters)

We sell digital goods such as Mullvad VPN Codes.

#### Enter the URL where a Monero mention can be found

https://digitalgoods.proxysto.re/
http://digitazyyxyihwwzudp5syxxyn3qhcd63wqcha2dxpfqiyydmrgdiaad.onion/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [X] Other payment gateaway (BTCPay Server)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks OK.

**Comment by erciccione** [comment]
Added with #1533
