### ISSUE TITLE
Moneropedia - Smart Mining

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#154]
Smart mining is the process of having a throttled miner mine when it otherwise does not cause drawbacks. Drawbacks include increases heat, slower machine, depleting battery, etc. The intent of smart mining is to increase network security by allowing as many people as possible to let the smart miner on all the time. For this to work, the miner must prove unobtrusive, or it will be turned off, depriving the Monero network from a little bit of security. As such, it is likely that a smart miner will mine slower than a normal miner on the same hardware.

Smart mining was started in 2014, but the contributor had to leave due to lack of time. View the current code [here](https://github.com/oranjuice/bitmonero/tree/smart-mining).

When this is finished, it is hoped that the relative slowness of a smart miner (especially on low-power machines) will be offset by the large amount of people running a miner for a possible "lottery win", and thus increase the Monero network security by a non trivial amount. The increased hash rate from many different sources will help keep the Monero network decentralized.

(Page adapted from [here](http://monero.stackexchange.com/questions/36/what-is-smart-mining)).

**Comment by palexande** [comment]
Done.
