### ISSUE TITLE
Add Abi-ko.com to the list of merchants

### ISSUE THREAD

**Issue by Abi-ko** [monero-project/monero-site#1543]
#### What's the name of your business?

Abi-ko.com

#### What's the URL of the website?

https://abi-ko.com/

#### Write a brief description of your business/service (max 50 characters)

Abi-ko.com - Anonymous Crypto Exchange

#### Enter the URL where a Monero mention can be found

https://abi-ko.com/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [+] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [+] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

**Comment by erciccione** [comment]
NACK

**Comment by luigi1111** [comment]
#1524

**Comment by Abi-ko** [comment]
> #1524

Hello 
Please tell me why you closed our issue, and linked us to another exchanger?
