### ISSUE TITLE
Add North of Boston to the list of merchants

### ISSUE THREAD

**Issue by u9000-Nine** [monero-project/monero-site#1545]
#### What's the name of your business?

North of Boston

#### What's the URL of the website?

https://northofboston.farm

#### Write a brief description of your business/service (max 50 characters)

Farm: Veggies fruit meat. Home delivery & markets

#### Enter the URL where a Monero mention can be found

https://northofboston.farm/home-delivery

https://northofboston.farm/farmers-markets

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

#### Comment

Servicing Boston and Boston North Shore

**Comment by erciccione** [comment]
Looks OK
