### ISSUE TITLE
Moneropedia - Kovri

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#155]
Kovri is a C++ router for I2P that is under heavy development. The intent is to run Monero [nodes](https://getmonero.org/knowledge-base/moneropedia/node) in the Kovri I2P router to hide IP addresses.

Kovri development helps Monero by increasing the privacy of it, and Monero helps Kovri by increasing the size of the I2P network.

View the Kovri project on GitHub [here](https://github.com/monero-project/kovri).

**Comment by anonimal** [comment]
In-progress here https://github.com/monero-project/kovri/issues/256

**Comment by anonimal** [comment]
Referencing https://github.com/anonimal/monero-site/commit/9e7e99b52f314517f2898743b226314b1ff28d0c and https://github.com/anonimal/monero-site/commit/e8aa590f0045210000e19572ea94549375fffbb7 in addition to the previous commits.

**Comment by anonimal** [comment]
@SamsungGalaxyPlayer for the time being, you're welcome to observe/contribute to https://github.com/anonimal/monero-site/tree/kovri-moneropedia/knowledge-base/moneropedia while I work on this.

**Comment by anonimal** [comment]
@SamsungGalaxyPlayer https://getmonero.org/knowledge-base/moneropedia/kovri has been up for a while now, can you close this issue?

**Comment by SamsungGalaxyPlayer** [comment]
@anonimal just saw this message. Closing.
