### ISSUE TITLE
Specify acronym for Monero Research Lab

### ISSUE THREAD

**Issue by alreadyburnt** [monero-project/monero-site#1552]
Similarly to the CCS, the Research Lab is often referred to by the acronym MRL. Such an unexplained acronym might confuse newcomers, which is why I think it should be officialized and added next to the title, as was done for the Community Crowdfunding System. I also suggest renaming the "Monero Research Lab Paper" section to "Published Papers" to avoid repetition.
<br>
![Screenshot_2021-04-05 CCS - Community Crowdfunding System (CCS)(1)](https://user-images.githubusercontent.com/81592644/113636700-4cdeb000-9673-11eb-8959-2c57758d36e2.png)
![Screenshot_2021-04-05  Monero Research Lab (3)](https://user-images.githubusercontent.com/81592644/113638579-7d284d80-9677-11eb-9ae1-25ec472f2fc7.png)

**Comment by erciccione** [comment]
I'm ok with both suggestions.

**Comment by erciccione** [comment]
#1590
