### ISSUE TITLE
moneropedia: example doesn't match explanation 

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-site#1561]
Here: https://www.getmonero.org/resources/moneropedia/address.html

![screen](https://user-images.githubusercontent.com/81592644/113939175-f355bd00-97fb-11eb-9ae4-ec43bdda1b11.png)

Either we explain that the subaddresses start with 8 or we change the address in the example.

**Comment by plowsof** [comment]
closed in #1990 (translation docs where not updated, a PR updating all moneropedia/user-guides is on-going, and will need to merge in recent changes also)
