### ISSUE TITLE
add the feature to conserve the page when converting to .onion with ".onion available" button on the Tor browser.

### ISSUE THREAD

**Issue by Jonahgay** [monero-project/monero-site#1571]
I couldn't come up with a better title.

![image](https://user-images.githubusercontent.com/16048625/114608802-9b043c80-9c8d-11eb-92c7-f87cd6f1f40c.png)

**Comment by erciccione** [comment]
I'll look into it. I too think should be doable. It's not easy to test though.

**Comment by erciccione** [comment]
#1592
