### ISSUE TITLE
Update worflow to check integrity of the sources tarball when a new release is pushed

### ISSUE THREAD

**Issue by binaryFate** [monero-project/monero-site#1576]
The automatic check of the hashes done in `.github/workflows/hashes.yaml` is a very nice feature that checks the hashes PR to the website correspond to the binaries available on the getmonero.org server. It helps with security and catches potential human errors.

We are now uploading sources together with binaries. As they are not produced in a deterministic way, one cannot check the integrity of the final file by just checking its hash. However it is possible to check the sources have not been tampered with by generating a new fresh tarball from the repository, uncompressing it, and checking that the result corresponds to the file on getmonero.org.

The script in `.github/workflows/hashes.yaml` shoul be upated to check the tarballs by basically doing something like the following:

```
#!/bin/bash

# You need to clone/download https://github.com/fabacab/git-archive-all.sh

# Generate your own tarballs
echo "--> Generating your own tarballs..."
version="v0.17.2.0"
# CLI
git clone --recursive -b $version --depth 1 --shallow-submodule https://github.com/monero-project/monero.git monero.git && cd monero.git && git-archive-all.sh --prefix monero-source-$version/ --format tar --tree-ish $version ../monero-source-${version}.tar && cd .. && bzip2 monero-source-${version}.tar && rm -rf monero.git

# GUI
git clone --recursive -b $version --depth 1 --shallow-submodule https://github.com/monero-project/monero-gui.git monero-gui.git && cd monero-gui.git && git-archive-all.sh --prefix monero-gui-source-$version/ --format tar --tree-ish $version ../monero-gui-source-${version}.tar && cd .. && bzip2 monero-gui-source-${version}.tar && rm -rf monero-gui.git
mkdir yours
mv monero*bz2 yours/.

# Grab tarballs generated by binaryFate
echo -e "\n--> Downloading tarballs from website..."
wget dlsrc.getmonero.org/gui/monero-gui-source-${version}.tar.bz2
wget dlsrc.getmonero.org/cli/monero-source-${version}.tar.bz2
mkdir from_website
mv monero*bz2 from_website/.

# Unpack all
echo -e "\n--> Unpacking all..."
bunzip2 yours/*.bz2
bunzip2 from_website/*.bz2
cd yours
tar xf monero-source-${version}.tar
tar xf monero-gui-source-${version}.tar
cd ../from_website
tar xf monero-source-${version}.tar
tar xf monero-gui-source-${version}.tar
cd ..

# Compare directories
echo -e "\n--> Comparing CLI directories:"
diff -r yours/monero-source-$version from_website/monero-source-$version
echo "--> Comparing GUI directories:"
diff -r yours/monero-gui-source-$version from_website/monero-gui-source-$version
```

If everything runs successfully until the end, and the output of the diff commands are empty (meaning no difference), then and only then the run should be successful.

**Comment by plowsof** [comment]
Thank you for doing most of the work @binaryFate , i took your script, and made a few adjustments:
- download and verify the hash of `git-archive-all.sh`
- get the current release tag version from github api
- instead of downloading the tarballs again, i have moved them into the directory for comparing
I've tested it and it fails when the diffs at the end break.    

@selsta gave me some tips and found some bugs. I will make a PR soon to close this - here is the working script on my own branch https://github.com/monero-project/monero-site/blob/7479219b2f4ca554f0a1b3690e0705ac3417d96c/.github/workflows/hashes.yaml#L76
