### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by Declic-CBD** [monero-project/monero-site#1577]
#### What's the name of your business?

Declic CBD

#### What's the URL of the website?

https://declic-cbd.fr/

#### Write a brief description of your business/service (max 50 characters)

CBD products online shop

#### Enter the URL where a Monero mention can be found

https://declic-cbd.fr/  i mention Monero 2 times in the first page

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x ] Goods
- [ ] Entertainment

#### Comment

Thanks in advance, regards

**Comment by erciccione** [comment]
OK
