### ISSUE TITLE
Add Bitvape to the list of merchants

### ISSUE THREAD

**Issue by xenpods** [monero-project/monero-site#1584]
#### What's the name of your business?

Bitvape

#### What's the URL of the website?

https://bitvape.com.au

#### Write a brief description of your business/service (max 50 characters)

Australias top rated JUUL store.

#### Enter the URL where a Monero mention can be found

https://bitvape.com.au/we-are-now-accepting-monero-xmr/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Note that this merchant was already listed and then removed with #1402. What happened here @xenpods ? Did you delist Monero and then list it again or was always listed and your merchant was removed by mistake?

**Comment by xenpods** [comment]
Im not sure what happened, I do have 2 merchant sites accepting xmr, so maybe someone thought there was a duplicate and removed this one.

**Comment by erciccione** [comment]
@xenpods please add a monero badge at the bottom of the page like you already do for Bitcoin and the other payment methods, that will help avoid confusions. People won't go looking for a blog post when they want to know if you accept Monero or not :)

**Comment by xenpods** [comment]
It's not possible with my wordpress theme im using, they only have the bitcoin logo. I have made a blogpost about monero though.

**Comment by erciccione** [comment]
#1588
