### ISSUE TITLE
Add cryptoFacile.io to the list of Tools

### ISSUE THREAD

**Issue by overgrowninfnat** [monero-project/monero-site#1586]
[cryptoFacile.io](https://cryptofacile.io/en-US/best-places-to-buy/monero)  (cryptocurrency exchanges comparison web app)

**Comment by erciccione** [comment]
Please open an issue using [the template for merchants](https://github.com/monero-project/monero-site/issues/new?assignees=&labels=%F0%9F%8F%AA+merchant%2C+%F0%9F%94%8D+Needs+investigation&template=new-merchant.md&title=Add+%3CNAME+OF+YOUR+BUSINESS%3E+to+the+list+of+merchants) if you want to add one.
