### ISSUE TITLE
Add cryptoFacile to the list of merchants

### ISSUE THREAD

**Issue by overgrowninfnat** [monero-project/monero-site#1587]
#### What's the name of your business?

cryptoFacile

#### What's the URL of the website?

https://cryptofacile.io

#### Write a brief description of your business/service (max 50 characters)

Compare crypto prices from the best crypto exchanges

#### Enter the URL where a Monero mention can be found

https://cryptofacile.io/en-US/best-places-to-buy/monero

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [x ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
OK.
