### ISSUE TITLE
Add pandaCD to the list of merchants

### ISSUE THREAD

**Issue by t-900-a** [monero-project/monero-site#1597]
#### What's the name of your business?

pandaCD (I'm not affiliated with them, just found them randomly)

#### What's the URL of the website?

https://pandacd.io/

#### Write a brief description of your business/service (max 50 characters)

 Peer-to-peer for musicians
PandaCD is a file-sharing community that features legally distributed music with Creative Commons and artist permission.
Accept Bitcoin , Ethereum , and Monero for your music. 

#### Enter the URL where a Monero mention can be found

https://pandacd.io/index.php?payment=xmr

#### How do you accept Monero? *(choose only one option)*

Monero address

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [x] Entertainment

**Comment by erciccione** [comment]
OK
