### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by 7ephtys** [monero-project/monero-site#1598]
Absolu Creation

https://absolucreation.com/

Description : 

We offer: Realization of flyer, advertising poster, business card, album cover, Ytb banner, logos on the theme of typography.
Everything at 5 € #French touch

#### Enter the URL where a Monero mention can be found

https://absolucreation.com/

#### How do you accept Monero? *(choose only one option)*

- [ ] Native wallet

#### How would you categorize your business? *(choose only one option)*

- [x] Service
I am preparing the page for the monero logo with my wallet
Thx for your time

**Comment by erciccione** [comment]
- The description is not max 50 characters as requested, if left like this we will add a description
- Don't remove fields if you don't want to fill them up, just leave them blank
- There are no mentions of Monero in your website

**Comment by erciccione** [comment]
ping
