### ISSUE TITLE
Add ProxyStore to the list of merchants

### ISSUE THREAD

**Issue by b068931cc450442b63f5b3d276ea4297** [monero-project/monero-site#1601]
#### What's the name of your business?

ProxyStore

#### What's the URL of the website?

https://proxysto.re/en/bestellservice.html

#### Write a brief description of your business/service (max 50 characters)

order products via the proxystore within the eu

#### Enter the URL where a Monero mention can be found

https://proxysto.re/en/bestellservice.html

#### How do you accept Monero? *(choose only one option)*

- [X] Other payment gateaway (BTCPay Server)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

#### Comment

We are not only interested in enabling payments with monero, but our offer aims to enable data-saving or anonymous online shopping. https://proxysto.re/en/warum.html

**Comment by erciccione** [comment]
OK
