### ISSUE TITLE
Add Z1 Fashion- Imagoza to the list of merchants

### ISSUE THREAD

**Issue by herbichimp** [monero-project/monero-site#1602]
#### What's the name of your business?

 Z1 Fashion- Imagoza

#### What's the URL of the website?

https://www.etsy.com/shop/ImagozaZ1fashion

#### Write a brief description of your business/service (max 50 characters)

Transformational clothing for a unique individual.

#### Enter the URL where a Monero mention can be found

https://www.etsy.com/shop/ImagozaZ1fashion

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

#### Comment

Note: Click "Read More" under "Announcement" if you don't see any mention of Monero.

**Comment by erciccione** [comment]
> What's the URL of the website?

We specifically ask for no referral links.

> Write a brief description of your business/service (max 50 characters)

That description is not max 50 characters

**Comment by herbichimp** [comment]
@erciccione thank you for taking a look! I didn't see that it was a reference link, didn't know I could remove that part! 

Fixed;

Removed ref part of link
&
Shortened description to less than 50 characters.

**Comment by erciccione** [comment]
Thanks. OK.

**Comment by erciccione** [comment]
#1588
