### ISSUE TITLE
Add Vesper Farms to the list of merchants

### ISSUE THREAD

**Issue by vesperfarms** [monero-project/monero-site#1603]
#### What's the name of your business?

Vesper Farms

#### What's the URL of the website?

https://www.vesperfarms.com/

#### Write a brief description of your business/service (max 50 characters)

Vermont CBD oil  & Custom 3D Printed chess sets and crafts

#### Enter the URL where a Monero mention can be found

https://https://www.vesperfarms.com/cbd-payment-options/

#### How do you accept Monero? *(choose only one option)*

- [ x] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ x] Goods
- [ ] Entertainment

#### Comment

Thanks!

**Comment by erciccione** [comment]
OK

**Comment by erciccione** [comment]
#1588
