### ISSUE TITLE
Add Reflectacles Privacy Eyewear to the list of merchants

### ISSUE THREAD

**Issue by bncb4** [monero-project/monero-site#1604]
#### What's the name of your business?

Reflectacles Privacy Eyewear

#### What's the URL of the website?

<https://www.reflectacles.com/>

#### Write a brief description of your business/service (max 50 characters)

Sunglasses designed to fool facial recognition

#### Enter the URL where a Monero mention can be found

<https://www.reflectacles.com/#beyond>

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X ] Goods
- [ ] Entertainment

#### Comment

Thanks much

**Comment by erciccione** [comment]
OK

**Comment by erciccione** [comment]
#1588
