### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by rollingreenhills** [monero-project/monero-site#1608]
#### What's the name of your business?

Southwest Environmental Limited

#### What's the URL of the website?

<https://www.southwest-environmental.co.uk>

#### Write a brief description of your business/service (max 50 characters)

Environmental Consultancy

#### Enter the URL where a Monero mention can be found

<https://www.southwest-environmental.co.uk/default.html>

https://www.southwest-environmental.co.uk/default.html

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
OK

**Comment by erciccione** [comment]
#1588
