### ISSUE TITLE
Add kryptocheck.de to the list of merchants

### ISSUE THREAD

**Issue by phplernen** [monero-project/monero-site#1612]
#### What's the name of your business?

kryptocheck.de

#### What's the URL of the website?

https://kryptocheck.de/

#### Write a brief description of your business/service (max 50 characters)

KryptoCheck is a german crypto marketplace comparison

#### Enter the URL where a Monero mention can be found

https://kryptocheck.de/monero-preisvergleich

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [x] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Besides the comparison KryptoCheck also offers a nice crypto earnings calculator that helps users to see how much money they could have earned by holding crypto. See https://kryptocheck.de/gewinn-rechner for that and choose f.e. Monero as a currency. We also have a tool thats helps users fo find a wallet for their coins. See https://kryptocheck.de/wallet-finder for this.

**Comment by erciccione** [comment]
OK.

**Comment by erciccione** [comment]
#1611
