### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by Yarnicorn** [monero-project/monero-site#1623]
#### What's the name of your business?

 Humble Acres Yarn 

#### What's the URL of the website?

 https://humbleacresyarn.com/ 

#### Write a brief description of your business/service (max 50 characters)

 High quality yarns for knitting, crochet, weaving. Also have free patterns for download.

#### Enter the URL where a Monero mention can be found

https://humbleacresyarn.com/54956589206/checkouts/6d9d22321eea9e77d31eb7dca4826ff9?previous_step=shipping_method&step=payment_method

#### How do you accept Monero? *(choose only one option)*

- [X ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X ] Goods
- [ ] Entertainment

#### Comment

 Thank you for allowing us to be apart of the awesomeness!

**Comment by erciccione** [comment]
> https://humbleacresyarn.com/54956589206/checkouts/6d9d22321eea9e77d31eb7dca4826ff9

I don't see Monero listed.

**Comment by erciccione** [comment]
@Yarnicorn ?
