### ISSUE TITLE
Add CryptoStop to the list of merchants

### ISSUE THREAD

**Issue by bwoff11** [monero-project/monero-site#1630]
#### What's the name of your business?

CryptoStop

#### What's the URL of the website?

http://cryptostop.org/

#### Write a brief description of your business/service (max 50 characters)

General store with over 1,000 brand-name items

#### Enter the URL where a Monero mention can be found

http://cryptostop.org/

On the main page, there should be an announcement that XMR can be used. XMR is accepted at checkout.

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [x ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

#### Comment

No comment.

**Comment by erciccione** [comment]
> Write a brief description of your business/service (max 50 characters)

This is not 50 characters. OK for the rest.

**Comment by bwoff11** [comment]
> This is not 50 characters. OK for the rest.

Sorry about that, it's been fixed.

**Comment by erciccione** [comment]
#1651
