### ISSUE TITLE
Add Andes Web Design to the list of merchants

### ISSUE THREAD

**Issue by erdos4d** [monero-project/monero-site#1636]
#### What's the name of your business?

Andes Web Design

#### What's the URL of the website?

https://www.andeswebdesign.com

#### Write a brief description of your business/service (max 50 characters)

Custom software, low prices, expert quality.

#### Enter the URL where a Monero mention can be found

Please see our landing page footer.

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [X] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

We run a full node and accept Monero to our wallet, I assume this is the "Native wallet" option above, please correct this if not. Thanks.

**Comment by erciccione** [comment]
OK.

**Comment by erciccione** [comment]
#1651
