### ISSUE TITLE
Add Radio Paradise to the list of merchants

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-site#1637]
#### What's the name of your business?

Radio Paradise

#### What's the URL of the website?

https://radioparadise.com/

#### Write a brief description of your business/service (max 50 characters)

Listener supported & always 100% commercial free on-line radio

#### Enter the URL where a Monero mention can be found

https://payments.radioparadise.com/?f=crypto

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [x] Entertainment

**Comment by erciccione** [comment]
I'm not sure this radio would qualify as "merchant". Looks more like it's a project distributed for free, that users can support by donating Monero. If that's the case i don't think the merchant page is the correct place to list this. We only have the "tools" section which is an exception to the rule (and IMO should be removed from the merchants page).

**Comment by ordtrogen** [comment]
Fair enough. I just happened to be listening to them while working and they had a blurb mentioning crypto currency as a way to support them and when looking into it, found Monero as an alternative. I thought it was in the project's interest to list as many ways to spend monero as possible and added the suggestion here on Github.

Not sure whether they run the service as a business or not, but the listener-provided support appears to be used to cover costs and support the artists they play

https://payments.radioparadise.com/?file=crb

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
