### ISSUE TITLE
Remove the 'Tools' section from the Merchants page

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1638]
The Merchants page lists businesses and services that accept Monero in exchange for said services/products. The 'Tools' section is an exception, as it lists tools like block explorers, which accept Monero donations.

I think the merchants page is not the best place for these services. I suggest to remove the 'Tools' section from the merchants page and instead create a dedicated section somewhere else.

**Comment by steverusso** [comment]
I might be missing something, but the 'Block Explorers' section is actually its own section outside of 'Tools,' right?

Regardless, I completely agree. Those types of things should be separated out from the 'Merchants' page.

**Comment by erciccione** [comment]
Yes, my wording was incorrect. Both sections ("Tools" and "Block Explorers") should be moved somewhere elese.

Note we already have a "Monero Tools" user guide, which it's very ugly and should be replaced with something else. This could be a good moment to fix 2 problems at the same time.

**Comment by steverusso** [comment]
> which it's very ugly and should be replaced with something else.
For sure. Anything particular in mind as to what should replace it?

It seems more like a list of links rather than a 'guide,' which makes me think it should just be removed instead. And then maybe those links can be placed in the new 'Tools' section.

**Comment by erciccione** [comment]
> makes me think it should just be removed instead

I think so too, but before deleting it we need to come up with an alternative. We could have a dedicated "Tools" page under "Resources" and move the content of the guide and the two sections "Tools" and "Block Explorers"

**Comment by steverusso** [comment]
Agreed :+1: 

Can I take a try at this?

**Comment by erciccione** [comment]
Sure go ahead. Would be good if you could share your progresses as you go, so we can look into this together. It will be a relatively big change.
