### ISSUE TITLE
Add page where to show technologies/services/tools built on Monero

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1641]
We don't have a place where to show technologies/services/tools built on Monero. We could have a dedicated page (the structure would be similar to the [sponsorships](https://www.getmonero.org/community/sponsorships/) page) for these projects.

Could be a new entry under the "Community" tab. So "Community" -> "Built on Monero".

Projects built on Monero:

**[Townforge](https://www.townforge.net/):** Game based on a slightly edited version of Monero, developed by Monero dev moneromooo. Even if the underlying technology is a fork of Monero, it shows the potentiality of the technology.

**[Primo](https://repo.getmonero.org/selene/primo):** "Primo (Private Monero payments) is a protocol and set of software which enables a party to require payment for service.
Users will mine Monero and submit shares to the party like to a pool. The party (eg, a web site) uses such mining as payment,
and supplies the service based on those payments"

**RPC-pay:** Not sure about this one. It's more a stratch because it's a Monero feature not something built on Monero, but this it's so underused and unknown to most that might make sense to add it to such list.

**[Haveno](https://github.com/haveno-dex/haveno):** Exchange built on and powered by Monero multisig (WIP, so would be added later on. Also, disclaimer: I'm part of the core team of Haveno)

Anything else built on Monero (excluding wallets, for obvious reasons) that we would like to add?

**Comment by HardenedSteel** [comment]
Maybe we can add open source Monero only market too: https://github.com/Janoher/MoneroMarket

**Comment by plowsof** [comment]
Is primo worth listing? seems dead, but still interesting use of the technology none the less
