### ISSUE TITLE
Add BitcoinWide to the list of merchants

### ISSUE THREAD

**Issue by glagola** [monero-project/monero-site#1643]
#### What's the name of your business?

BitcoinWide

#### What's the URL of the website?

https://bitcoinwide.com/

#### Write a brief description of your business/service (max 50 characters)
Find companies and individuals accepting Monero

#### Enter the URL where a Monero mention can be found

https://bitcoinwide.com/search?query=xmr

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [x] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Bitcoinwide.com is a global, open and free platform to search businesses, organizations or individuals who accept cryptocurrency as a payment.

**Comment by erciccione** [comment]
This is not a merchant, more like a directory of merchants. They don't accept Monero, so they don't fit the merchants page. Closing.
