### ISSUE TITLE
Public Donations List

### ISSUE THREAD

**Issue by sh5x5j12** [monero-project/monero-site#1648]
There will be a public donation list, last month's most donators, last donations and while donation optional nickname or name would be better. This feature will encourage people to donate.

**Comment by erciccione** [comment]
You can use the view key of the general fund to monitor incoming transactions. I think that would have all the info you are looking for.

**Comment by sh5x5j12** [comment]
> You can use the view key of the general fund to monitor incoming transactions. I think that would have all the info you are looking for.

Yes but I think if we list at website it will encourage people to donate.

**Comment by erciccione** [comment]
I don't think so. Maintaining such list would be also very time consuming. I don't see any benefits in this suggestions. Closing.
