### ISSUE TITLE
Add <VENOM X SECURITY LTD.> to the list of merchants

### ISSUE THREAD

**Issue by Knightsbr1dge** [monero-project/monero-site#1650]
#### What's the name of your business?

Venom X Security Ltd.

#### What's the URL of the website?

https://www.venomxsecurity.com

#### Write a brief description of your business/service (max 50 characters)

Penetration testing, vulnerability assessment and OSINT

#### Enter the URL where a Monero mention can be found

https://www.venomxsecurity.com/crypto-currency/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

We look forward to helping extend the Monero platform and reach.

**Comment by erciccione** [comment]
OK.

**Comment by erciccione** [comment]
#1651
