### ISSUE TITLE
Add Uniochange to the list of merchants

### ISSUE THREAD

**Issue by uniochange** [monero-project/monero-site#1654]
#### What's the name of your business?

Uniochange

#### What's the URL of the website?

https://uniochange.com/en

#### Write a brief description of your business/service (max 50 characters)

Buy and sell crypto.

#### Enter the URL where a Monero mention can be found

https://uniochange.com/en

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Our service gives users the opportunity to exchange Monero.

**Comment by erciccione** [comment]
Rejected.
