### ISSUE TITLE
Add Royal.cash to the list of merchants

### ISSUE THREAD

**Issue by royal-cash** [monero-project/monero-site#1657]
#### What's the name of your business?

Royal.cash

#### What's the URL of the website?

https://royal.cash/en/

#### Write a brief description of your business/service (max 50 characters)

fast exchange

#### Enter the URL where a Monero mention can be found

https://royal.cash/en/monero-na-bitcoin.html

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

**Comment by erciccione** [comment]
Rejected.
