### ISSUE TITLE
ChangeHero - Instant exchange !!!SCAM!!!

### ISSUE THREAD

**Issue by kozilolop** [monero-project/monero-site#1660]
When exchanging Monero for Bitcoin deleted my request and wrote that the address to which I paid to them does not belong as a result dumped 3.12 XMR
Remove them from the list of exchangers on your site that others did not throw.

**Comment by erciccione** [comment]
Please post the exact URL of the exchange.

**Comment by kozilolop** [comment]
https://changehero.io/

**Comment by erciccione** [comment]
Looks like possible selective scammers.

**Comment by erciccione** [comment]
I'm not convinced this should be removed for now. More feedback would be helfpul and welcome.

**Comment by Scam-ChangeHero** [comment]
As I see I'm not the only one who suffered from the actions of these scammers why are they still on your list?
And why this issue was opened on the 26th and you knew they were crooks and you have not removed them yet? If you had removed them in time I would not have lost 15000 USD!!!

**Comment by erciccione** [comment]
While i'm not convinced of the legitimacy of these brand new accounts opened only to comment on this exchange, there could be reasons to delist this merchant. If anybody has a feedback concerning changehero, please post it here.

**Comment by Scam-ChangeHero** [comment]
https://www.bestchange.com/changehero-exchanger.html
Here are enough reviews to prove that this is a scam that selectively scams customers.
They also use the AML / KYC method of fraud. Request a check which they have a very long and incomprehensible and if a person can not pass it just keep the money.
I see feedback that many are not refunded even after the user has passed AML / KYC making up new excuses this is 100% fraud.

**Comment by Scam-ChangeHero** [comment]
In addition, they cheat with the amount of payment, understating it at the time of payment. Since their payment amount is recalculated when the cryptocurrency has received enough confirmations and when this happens, they artificially underestimate the rate.

**Comment by erciccione** [comment]
>  Here are enough reviews to prove that this is a scam that selectively scams customers.

The almost totality of the reviews on that page are positive. What are you referring to?

> I see feedback that many are not refunded

Could you provide links to these feedbacks?

**Comment by Scam-ChangeHero** [comment]
I am relying on my experience with this exchanger for which I lost 15000 USD.
Here are the reviews I found in a couple of minutes.
https://www.trustpilot.com/reviews/60a6235df9f4870a94a7c079
https://www.trustpilot.com/reviews/60a324bef9f4870a94a55618
https://www.trustpilot.com/reviews/60882f4ff9f4870984ad1fe1
https://www.trustpilot.com/reviews/600ad332755dc104c0c5be4a
https://www.trustpilot.com/reviews/5ff74905755dc1032c0efb14
https://www.trustpilot.com/reviews/5e1e336fc8454503e831f6f6

**Comment by Scam-ChangeHero** [comment]
There's a lot of negativity about them online.
Why they are not removed from your site is not clear.
If this negativity came up recently, there would be no questions and so you have the first complaint from a client was 1 month ago, well, he you have active until now.

How do you remove the unscrupulous exchangers do not understand I look at the other exchangers come sometimes complaints you immediately remove them without question.
This hangs for a month, he has two complaints and he still has not been removed, please explain your actions!

**Comment by Scam-ChangeHero** [comment]
Because I lost 15,000 USD because of your actions.
If you had removed it after the first customer complaint I would not have lost that money, I think I deserve at least a simple explanation on your part as to why it was not removed after the complaint.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
