### ISSUE TITLE
Remove Scammer 24bestex.com

### ISSUE THREAD

**Issue by Kornevech** [monero-project/monero-site#1666]
https://github.com/monero-project/monero-site/issues/1510
Remove scammers from your list, went to their site exchanged XMR to a ruble card have removed the application and say that I have not paid!
I lost 40,000 rubles in the end.

**Comment by erciccione** [comment]
OK

**Comment by best24dev** [comment]
You probably made a mistake with the site, because this exchanger does not work with rubles. Please check the full address of the site, you may have created an application on a phishing site.
Please indicate your application number, I will check the information.

Thank you.

**Comment by Kornevech** [comment]
I was not mistaken exchanger he worked with the ruble, well this exchanger if you pay attention as a week on the technical works or he hacked or what happened to him I do not know well that the exchanger as a week stopped working.

**Comment by Kornevech** [comment]
After they ditched a number of clients the exchanger stopped working.
And at the moment it also does not work, you can just go to the site and nothing else on the site does not work.

**Comment by erciccione** [comment]
Removing with #1681

**Comment by best24dev** [comment]
> Removing with #1681

Please note, 24bestex.com never work with rubles. You can check it back with the wayback machine service or on thematic forums. The exchanger works only with cryptocurrencies and electronic payment systems, such as perfect money, payeer, advcash. Earlier, with its help it was possible to raise exchanges for the hryvnia.  But the exchanger for all it existence did not carry out any exchange in rubles.

This request is more like slander. Thus it is possible to remove all merchants, having thought up non-existent reasons
