### ISSUE TITLE
Add Cloud Matrix (Pty) Ltd to the list of merchants

### ISSUE THREAD

**Issue by wadejbeckett** [monero-project/monero-site#1668]
#### What's the name of your business?

Cloud Matrix (Pty) Ltd or Cloud Matrix

#### What's the URL of the website?

https://my.cloudmatrix.ie/

#### Write a brief description of your business/service (max 50 characters)

Shared Hosting, Virtual Servers, Linux Server Administration.

#### Enter the URL where a Monero mention can be found

https://my.cloudmatrix.ie/knowledgebase/4992/How-to-pay-with-Monero-XMR.html

https://

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [x ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

I am actively engaging customers to get them to move over to XMR at the moment, and offer incentive discounts for Monero payment.

**Comment by mycloudmatrix** [comment]
Additional link: https://my.cloudmatrix.ie/knowledgebase/4992/How-to-pay-with-Monero-XMR.html

**Comment by erciccione** [comment]
> Shared Hosting, Domain Registration, Virtual Servers, WordPress Managed Hosting, Linux Server Administraion.

This is more than 50 characters

**Comment by mycloudmatrix** [comment]
> > Shared Hosting, Domain Registration, Virtual Servers, WordPress Managed Hosting, Linux Server Administraion.
> 
> This is more than 50 characters

Updated. Thank you.

**Comment by erciccione** [comment]
Ok.

**Comment by erciccione** [comment]
#1687
