### ISSUE TITLE
REMOVE Newton from the list of merchants

### ISSUE THREAD

**Issue by zerozeroinfinity** [monero-project/monero-site#1671]
#### What's the name of your business?

Newton

#### What's the URL of the website?

https://newton.co

#### Write a brief description of your business/service (max 50 characters)

Newton is a Canadian cryptocurrency exchange.

#### Enter the URL where a Monero mention can be found

https://twitter.com/newton_crypto/status/1403495281740500995
https://www.newton.co/blog/xmr-discontinued?utm_source=Social&utm_medium=Twitter&utm_campaign=XMR_discontinued

**Comment by erciccione** [comment]
OK

**Comment by erciccione** [comment]
#1672
