### ISSUE TITLE
Add Swirlwallet to the list of merchants

### ISSUE THREAD

**Issue by swirlwalletadmin** [monero-project/monero-site#1680]
#### What's the name of your business?

Swirlwallet

#### What's the URL of the website?

https://swirlwallet.com

#### Write a brief description of your business/service (max 50 characters)

Wallet Service with Exchange option.

#### Enter the URL where a Monero mention can be found

https://swirlwallet.com/home

https://

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Thanks for your consideration.

**Comment by erciccione** [comment]
Brand new and closed source. Too risky to add for now. Feel free to request to be added again in the future.

NACK
