### ISSUE TITLE
Add Private Phone Shop to the list of merchants

### ISSUE THREAD

**Issue by privatephoneshop** [monero-project/monero-site#1685]
#### What's the name of your business?

Private Phone Shop

#### What's the URL of the website?

https://www.privatephoneshop.com

#### Write a brief description of your business/service (max 50 characters)

De-googled phones w/ LineageOS and GrapheneOS

#### Enter the URL where a Monero mention can be found

https://privatephoneshop.com/faq/#Do_you_accept_cryptocurrency_as_payment

#### How do you accept Monero? *(choose only one option)*

- [X ] Other payment gateaway  - MyCryptoCheckout

#### How would you categorize your business? *(choose only one option)*

- [X] Goods

#### Comment

Nothing else, we love Monero!

**Comment by erciccione** [comment]
Ok.

**Comment by erciccione** [comment]
#1687
