### ISSUE TITLE
Add Bitpro.cash to the list of merchants

### ISSUE THREAD

**Issue by bitpro-cash** [monero-project/monero-site#1688]
#### What's the name of your business?

Bitpro.cash

#### What's the URL of the website?

https://bitpro.cash/en

#### Write a brief description of your business/service (max 50 characters)

Instant exchange aggregator

#### Enter the URL where a Monero mention can be found

https://bitpro.cash/en/ETH-to-XMR
https://bitpro.cash/en/XMR-to-USDTERC

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment
Hello 
We represent an aggregator of exchange services.

With the help of our aggregator, holders of Monera cryptocurrency can exchange it for other cryptocurrencies at the most favorable conditions.

All our partners undergo a frequent security check, we cooperate only with the themes of services that provide their services to customers for at least 1 year, and have no negative feedback.

**Comment by erciccione** [comment]
Rejected.
