### ISSUE TITLE
Add <7b> to the list of merchants

### ISSUE THREAD

**Issue by MichaelSelge** [monero-project/monero-site#1692]
#### What's the name of your business?

7b crypto broker app 

#### What's the URL of the website?

https://sevenb.io/ 

#### Write a brief description of your business/service (max 50 characters)

7b is a crypto broker app with easy-to-use interface

#### Enter the URL where a Monero mention can be found

https://drive.google.com/drive/folders/1Eshds0nk7_sx4emmRKGB6YPpehiU1qIT?usp=sharing

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [+] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [+] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

**Comment by MichaelSelge** [comment]
Add new merchant

**Comment by erciccione** [comment]
PR: #1669.

According to the stricter rules we are adapting when it comes to listing exchanges, i would reject this merchant, but @selsta voiced interest in adding them (see the PR). So it's up to core to decide (@luigi1111).

**Comment by selsta** [comment]
My comment wasn't in regards of accepting / rejecting this merchant, just that a screenshot is okay as proof that monero is accepted inside an app. If you have different rules for this then ignore my comment.

I don't know anything about this merchant

**Comment by MichaelSelge** [comment]
@selsta @erciccione Hello! 

Could you please send me your TG addresses? I will describe you our app and answer all of your questions about it!)

**Comment by MichaelSelge** [comment]
Here is mine - https://t.me/Michael_7b. 

Looking forward contacting with you!

**Comment by selsta** [comment]
Sorry, I don't have Telegram and I don't think I can judge this.

**Comment by MichaelSelge** [comment]
In that case whom can I talk about it? 

@luigi1111, can you contact me via TG?

**Comment by MichaelSelge** [comment]
+ we've already released Monero page on our web-site - https://sevenb.io/currencies/monero.

**Comment by MichaelSelge** [comment]
Guys?

**Comment by erciccione** [comment]
@MichaelSelge. We recently decided to list less exchanges on getmonero and only if they fulfil our requirements. Sadly, your exchange does not for now. Please come back after you'll be more established.

Rejected.
