### ISSUE TITLE
Add 24bestex.com to the list of merchants

### ISSUE THREAD

**Issue by best24dev** [monero-project/monero-site#1694]
#### What's the name of your business?

24bestex.com

#### What's the URL of the website?

https://24bestex.com/

#### Write a brief description of your business/service (max 50 characters)

24bestex - cryptocurrency exchanger

#### Enter the URL where a Monero mention can be found

https://24bestex.com/en/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [x] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

According to issue #1666, the merchant has been removed
However, I believe that it was removed without investigation and evidence. 
Please note, 24bestex.com never work with rubles. You can check it back with the wayback machine service or on thematic forums. The exchanger works only with cryptocurrencies and electronic payment systems, such as perfect money, payeer, advcash. Earlier, with its help it was possible to raise exchanges for the hryvnia. But the exchanger for all it existence did not carry out any exchange in rubles.
The issue #1666 is more like slander. Thus it is possible to remove all merchants, having thought up non-existent reasons

**Comment by erciccione** [comment]
> Listing merchants on the 'Merchants' page is at our discretion and acceptance shouldn't be assumed.

Please don't open more issues about this.
