### ISSUE TITLE
Remove   DV Chain (OTC) - Cryptocurrency OTC desk that offers buying and selling of Monero from the list of merchants

### ISSUE THREAD

**Issue by Zoloqiko** [monero-project/monero-site#1699]
#### What's the name of the merchant you are asking to remove?

DV Chain (OTC) - Cryptocurrency OTC desk that offers buying and selling of Monero

#### What's the URL of their website?

https://dvchain.co/

#### Why do you think it should be removed?

- [x] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://dvchain.co/

#### Additional comments

Passed the registration, KYC and as it turned out the seller does not accept Monero.

**Comment by gsee** [comment]
Hi @Zoloqiko, there must have been a misunderstanding. DV Chain 100% supports monero and we encourage our counterparties to trade it more.  Please reach back out.

**Comment by erciccione** [comment]
Thanks for the clarification @gsee. Monero is also listed in the FAQ ("What cryptocurrencies can I trade?").

Rejected.
