### ISSUE TITLE
Remove CoinCut (OTC) from the list of merchants

### ISSUE THREAD

**Issue by Zoloqiko** [monero-project/monero-site#1700]
#### What's the name of the merchant you are asking to remove?

CoinCut (OTC)

#### What's the URL of their website?

https://www.coincut.com/

#### Why do you think it should be removed?

- [x] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://www.coincut.com/

#### Additional comments

Very strange site has passed registration well I have not found where they have the opportunity to exchange Monero, perhaps she was before but at the moment there is no way to exchange Monero on this site.

**Comment by erciccione** [comment]
They seem to accept Monero, but we should remove them anyway. They look inactive.
