### ISSUE TITLE
Add De-Googled.com to the list of merchants

### ISSUE THREAD

**Issue by Roverid** [monero-project/monero-site#1701]
#### What's the name of your business?

De-Googled.com

#### What's the URL of the website?

https://de-googled.com/

#### Write a brief description of your business/service (max 50 characters)

We sell de googled phones. Customer can choose Pixel series phones shipping with either Graphene OS or Calyx OS.

#### Enter the URL where a Monero mention can be found

https://de-googled.com/

#### How do you accept Monero? *(choose only one option)*

Globee

#### How would you categorize your business? *(choose only one option)*

- [ ] Goods

#### Comment

Thanks Monero community for all you've done and you're doing.

**Comment by erciccione** [comment]
> We sell de googled phones. Customer can choose Pixel series phones shipping with either Graphene OS or Calyx OS.

This is not max 50 characters
