### ISSUE TITLE
Add HedgeBot to the list of merchants

### ISSUE THREAD

**Issue by randomx55** [monero-project/monero-site#1703]
#### What's the name of your business?

HedgeBot

#### What's the URL of the website?

https://hedgebot.trade/

#### Write a brief description of your business/service (max 50 characters)

HedgeBot - Advanced Crypto Trading Bot

#### Enter the URL where a Monero mention can be found

On the first page
https://hedgebot.trade/

#### How do you accept Monero? *(choose only one option)*

Gateway : nowpaiement.io 

#### How would you categorize your business? *(choose only one option)*

- Service

#### Comment

HedgeBot is a brand new automatic trading robot. I would be very proud to have our site appear in the monero merchant page, also very happy to offer this payment method. We are very focused on the privacy of our customers, so it was natural to offer monero.

**Comment by erciccione** [comment]
Rejected.

Feel free to reopen after your service will be more estabilished.
