### ISSUE TITLE
Remove Alfacashier from the list of merchants

### ISSUE THREAD

**Issue by LifeFrederic** [monero-project/monero-site#1704]
#### What's the name of the merchant you are asking to remove?

Alfacashier

#### What's the URL of their website?

https://www.alfa.cash/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [x] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://www.alfa.cash/

#### Additional comments

Paid the exchange 612852
The warrant was canceled.
They wrote that the payment was not received and the wallet to which I paid does not belong to their service.
Scammers remove them.

I also want to point out that your site has a domain: https://www.alfacashier.com/
Well, when you go to this domain is redirected to the domain https://www.alfa.cash/
The bad thing is that I noticed it after I paid for it.

**Comment by erciccione** [comment]
ACK. I found enough reasons to delist it.

**Comment by LifeFrederic** [comment]
Are you laughing?
This exchanger has turned into a scam project.
I lost my money on it.
And confirmation that the exchanger has become a scam can be seen immediately without any investigation.

On your site https://www.getmonero.org/community/merchants/#exchanges
When you click on Alfacashier goes to https://www.alfacashier.com/ well this domain no longer works and it is redirected to https://www.alfa.cash/ do you think this is normal?

**Comment by LifeFrederic** [comment]
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/87032869/124894483-39711700-dfcb-11eb-9afb-fadeab5846e8.png">

**Comment by LifeFrederic** [comment]
Paid the exchange 612852
The warrant was canceled.
They wrote that the payment was not received and the wallet to which I paid does not belong to their service.
How can you explain this in their defense?
