### ISSUE TITLE
Add Occidental Technologies to the list of merchants

### ISSUE THREAD

**Issue by CM-IV** [monero-project/monero-site#1705]
#### What's the name of your business?

Occidental Technologies

#### What's the URL of the website?

https://civdev.rocks

#### Write a brief description of your business/service (max 50 characters)

Web Development --- Software Engineering

#### Enter the URL where a Monero mention can be found

https://civdev.rocks

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ X ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ X ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Computer Scientist owned and operated web development business.

**Comment by erciccione** [comment]
OK

**Comment by erciccione** [comment]
Added with #1713
