### ISSUE TITLE
Remove Liberalcoins from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1706]
#### What's the name of the merchant you are asking to remove?
Liberalcoins

#### What's the URL of their website?

https://liberalcoins.com/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [x] They closed / Their services are unavailable

#### Useful links

https://liberalcoins.com/

#### Additional comments

It doesn't work.

**Comment by erciccione** [comment]
Ok.
