### ISSUE TITLE
Remove ExchangeD.I2P - Darknet exchange (I2P) from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1707]
#### What's the name of the merchant you are asking to remove?

ExchangeD.I2P - Darknet exchange (I2P)

#### What's the URL of their website?

http://www.exchanged.i2p

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [x] They closed / Their services are unavailable

#### Useful links

http://www.exchanged.i2p

#### Additional comments

It doesn't work.

**Comment by erciccione** [comment]
This website works only on P2P. Have you checked using the I2P network?

**Comment by AiloQito** [comment]
Yes I checked through the i2P network.

**Comment by erciccione** [comment]
Just checked through I2P and it looks offline.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
