### ISSUE TITLE
Remove Swaplab from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1708]
#### What's the name of the merchant you are asking to remove?

Swaplab

#### What's the URL of their website?

https://swaplab.cc/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [x] They closed / Their services are unavailable

#### Useful links

https://swaplab.cc/

#### Additional comments

It doesn't work.

**Comment by erciccione** [comment]
Ok.
