### ISSUE TITLE
Remove CRYPTODIGGERS.EU from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1709]
#### What's the name of the merchant you are asking to remove?

CRYPTODIGGERS.EU

#### What's the URL of their website?

https://cryptodiggers.eu/

#### Why do you think it should be removed?

- [x] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://cryptodiggers.eu/

#### Additional comments

This is not an exchanger, but some kind of obscure site.

**Comment by erciccione** [comment]
They offer services and a payment gateway (which we already list). It shouldn't be removed, but moved to "services".
