### ISSUE TITLE
Remove   Trovemat.com (ATM) from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1710]
#### What's the name of the merchant you are asking to remove?

Trovemat.com (ATM)

#### What's the URL of their website?

https://trovemat.com/

#### Why do you think it should be removed?

- [x] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://trovemat.com/

#### Additional comments

This is not an exchanger, but some kind of obscure site.

**Comment by erciccione** [comment]
Looks abandoned. Ok.
