### ISSUE TITLE
Remove LocalCoin.is - LLC/XMR from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1711]
#### What's the name of the merchant you are asking to remove?

LocalCoin.is - LLC/XMR

#### What's the URL of their website?

https://localcoin.is/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [ч] They closed / Their services are unavailable

#### Useful links

https://localcoin.is/

#### Additional comments

Trading does not work and as I understand the site operates as a business card and was not run to the end.

**Comment by erciccione** [comment]
Abandoned. OK.
