### ISSUE TITLE
Remove LocalMonero (P2P exchange) from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1712]
#### What's the name of the merchant you are asking to remove?

LocalMonero (P2P exchange)

#### What's the URL of their website?

https://localmonero.co/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable
- [x] Repeat

#### Useful links

https://agoradesk.com/

#### Additional comments

You 2 times specified in fact one and the same exchange, just 2 of its domains.
https://agoradesk.com/ © 2021 Blue Sunday Limited 
https://localmonero.co/ © 2021 Blue Sunday Limited 
This is one and the same exchange just under two different domains.

In the bottom menu of both domains there are links to mirror domains.

**Comment by erciccione** [comment]
It's run by the same entity, but it's not the same thing.

NACK
