### ISSUE TITLE
Remove LocalMonero (P2P exchange) from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1715]
This is not separate services, namely one and the same service only on two different domains and they indicate it themselves.
Here are examples of the fact that it is the same service.
1: Statistics of traders is the same on two domains and is updated online and there at once.
https://localmonero.co/user/MalMen
https://agoradesk.com/user/MalMen
https://localmonero.co/user/TheKaii
https://agoradesk.com/user/TheKaii
2: It's the same with the announcements of traders in any direction the same.
https://localmonero.co/sell-monero-using-advcash-with-usd
https://agoradesk.com/sell-monero-using-advcash-with-usd
https://localmonero.co/sell-monero-using-zelle-with-usd
https://agoradesk.com/sell-monero-using-zelle-with-usd
3: Completely the same functionality on 2 domains.
4: When you register on one domain, the account is available on the second domain at once.
5: Their websites indicate that these are their mirrors, not separate services.

That is, it's just two domains well one server with one base.

**Comment by erciccione** [comment]
Please stop spamming the repository.
