### ISSUE TITLE
Remove Bisq; decentralized exchange (previously Bitsquare) from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1716]
#### What's the name of the merchant you are asking to remove?

Bisq; decentralized exchange (previously Bitsquare)

#### What's the URL of their website?

https://bisq.network/

#### Why do you think it should be removed?

- [x] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable

#### Useful links

https://bisq.network/

#### Additional comments

All described well but in fact no one direction with Monero is not possible to buy or sell anything as there is no offers from traders.

In fact, just yes Monero they have in currencies well only sell or buy is not possible for what they need such an exchange users Monero is not clear.

**Comment by SamsungGalaxyPlayer** [comment]
There have been several trades for the last several days

https://bisq.network/markets/?currency=xmr_btc

**Comment by erciccione** [comment]
Of course Bisq still supports Monero. This is borderline spam by somebody who is not doing the minimal due diligence before opening an issue.
