### ISSUE TITLE
Remove MorphToken from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1717]
#### What's the name of the merchant you are asking to remove?

MorphToken

#### What's the URL of their website?

https://www.morphtoken.com/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [x] They closed / Their services are unavailable

#### Useful links

https://www.morphtoken.com/

#### Additional comments

The exchange does not work, and on the site under the form of exchange says the following:

Service is not available

For issues enter in contact by email.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
