### ISSUE TITLE
Remove   Kaiserex from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1718]
#### What's the name of the merchant you are asking to remove?

Kaiserex

#### What's the URL of their website?

https://www.kaiserex.com/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [x] They closed / Their services are unavailable

#### Useful links

https://www.kaiserex.com/order

#### Additional comments

Site abandoned impossible to exchange anything, nothing just does not work, all that works is just registration.
Then it is impossible to perform any further actions on the site.

**Comment by erciccione** [comment]
Ok.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
