### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by Kursescomua** [monero-project/monero-site#1719]
#### What's the name of your business?

kurses the monitoring of exchangers

#### What's the URL of the website?

https://en.kurses.com.ua

#### Write a brief description of your business/service (max 50 characters)

Collects, analyzes and provides data on exchange rates from the best exchangers. With us, exchanges will be fast, profitable and no extra fees.

#### Enter the URL where a Monero mention can be found

https://en.kurses.com.ua/from-visa-mastercard-usd-to-monero

#### How do you accept Monero? *(choose only one option)*

- [ ] Globee

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange

#### Comment

Allows you to quickly find a suitable exchanger with the best rate. Exchangers are checked before entering the site, therefore, using our service, you can not only make a profitable exchange, but also much safer.

**Comment by AiloQito** [comment]
Very vintage website design. Also, this is not an exchanger but just an informational site where they can add anyone for money.

In fact, this is an advertising site, well, not an exchanger.

**Comment by Kursescomua** [comment]
> Very vintage website design. Also, this is not an exchanger but just an informational site where they can add anyone for money.
> 
> In fact, this is an advertising site, well, not an exchanger.

Sorry but, where did you see the advertise?

**Comment by AiloQito** [comment]
Your whole site works on the principle of advertising. 

You are not an exchanger you are a platform for advertising exchangers and your zarobotok goes from referral program exchangers.

That is, you advertise the exchanger, and then when the client goes to the exchanger and makes the exchange you get referral payments, well, you are not like you do not control the exchange process and can not affect it.

What do you call it?
It's just a site that advertises exchanges, not an exchange site.

**Comment by AiloQito** [comment]
If I understand something wrong, please write.

**Comment by Kursescomua** [comment]
> zarobotok

What does it mean?

**Comment by Kursescomua** [comment]
> If I understand something wrong, please write.

According to your description, a trade place is also an advertisement.

The user transfers money to her, pays a commission, then, when he buys another currency, he also pays a commission.

The trading platform does not dispose of its own funds, it uses the funds of its clients and takes a commission for it.

In fact, she is simply advertising other customers' sales offers, NOT OWN.

That is, it does not change anything, but simply brings different clients together. Otherwise, there would be no such concept as the input and output of money, there would be only one concept, exchange and that's it.

We provide a simple, convenient and the safest way to exchange funds, at a favorable rate for more than 12 years.

We do not dispose of other people's money, which does not require additional financial costs from anyone.

Not all has referral programs, and even if there is something, it does not mean that we benefit from it.

Most likely you are not familiar with us and how everything functions, draw conclusions based on your own beliefs.

We can confirm our words.

**Comment by AiloQito** [comment]
It's not right to compare marketplaces to your site.

On the trading platforms exchange occurs on the site of the site itself without any third-party sites and transitions.

You have a completely different situation you just show users which exchanger at what rate does the exchange and the user goes to the exchanger's site and already at the site of the exchanger makes the exchange and not at your site. 

So you never answered my question how you position yourself as an exchanger if you are not.

You a site that advertises exchangers not in the usual way, that is, it shows exactly the exchange rate, and the client chooses through your advertising, which exchanger he will use.

Well, you're not an exchanger.

In addition, you are not responsible for the exchange and are not responsible for the means users, in a disputed situation with the exchanger maximum you can do is to remove the exchanger from your site, well, the user of this is not easier, he will lose their money.

**Comment by AiloQito** [comment]
If the exchange was performed directly on your site, for example, as at these services:
https://swapzone.io/
https://swapspace.co/
Then you could be called an exchanger, but you're just an advertising site and nothing more.

**Comment by AiloQito** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/87210500/125194247-ed7ad800-e23f-11eb-94c8-666431efadae.png">

**Comment by Kursescomua** [comment]
> If the exchange was performed directly on your site, for example, as at these services:
> https://swapzone.io/
> https://swapspace.co/
> Then you could be called an exchanger, but you're just an advertising site and nothing more.

In order not to argue for a long time, then pay attention to this list https://www.getmonero.org/community/merchants/index.html

There are really very few exchangers in it, mainly trade platform. And they are not exchangers, at least later, what are called trade platform.

Further, this list contains BestChange, it is not the same exchanger as we are, but it is on this list, then explain why we cannot be on this list?

**Comment by AiloQito** [comment]
For 12 years you could not make the site open properly from all browsers and make a normal SSL-certificate?
The fact that you write that you work 12 years does not mean that it is so and maybe you just bought a domain at the domain exchange 12 years old.

Well, it's not even the term of the domain, the exchanger can be a new one, even 1-2 months, well it is properly done and beautifully decorated and everything is clear on it and everything works properly such exchangers can be added.

Well you are not an exchanger, but just an advertising site, which  does not work correctly and has elementary problems with SSL.

Make a competitive service for users and then write anywhere that you would have been added. But you just write that to the official website of cryptocurrency added site to advertise exchangers.

**Comment by AiloQito** [comment]
Thank you for pointing out Bestchange should also not be on this list as it is the same site as you.

**Comment by erciccione** [comment]
This website doesn't fit in our merchants page for multiple reason, including the fact that it has an expired certificate.

Rejected.

**Comment by Kursescomua** [comment]
> This website doesn't fit in our merchants page for multiple reason, including the fact that it has an expired certificate.
> 
> Rejected.

Certificate not expired, provide proof please!

It is valid until 30.07 and then, a new one will be generated and so on. This gives you maximum security. Similarly to a password, the more often it is changed, the more reliable the protection.

**Comment by Kursescomua** [comment]
> For 12 years you could not make the site open properly from all browsers and make a normal SSL-certificate?
> The fact that you write that you work 12 years does not mean that it is so and maybe you just bought a domain at the domain exchange 12 years old.
> 
> Well, it's not even the term of the domain, the exchanger can be a new one, even 1-2 months, well it is properly done and beautifully decorated and everything is clear on it and everything works properly such exchangers can be added.
> 
> Well you are not an exchanger, but just an advertising site, which does not work correctly and has elementary problems with SSL.
> 
> Make a competitive service for users and then write anywhere that you would have been added. But you just write that to the official website of cryptocurrency added site to advertise exchangers.

The site works fine in different modern browsers, please provide proof where is this wrong?

An answer was given about the certificate earlier. You do not know how to check the certificate but have taken it upon yourself to check other sites?

**Comment by Kursescomua** [comment]
> Thank you for pointing out Bestchange should also not be on this list as it is the same site as you.

So either delete this site, or add ours, you get a purely judgmental attitude, which is based on your personal opinion and not on specific rules.

**Comment by Kursescomua** [comment]
> This website doesn't fit in our merchants page for multiple reason, including the fact that it has an expired certificate.
> 
> Rejected.

Here is proof that everything is fine with the site and everything is displayed correctly https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fen.kurses.com.ua&tab=desktop

We hope Google is an authority for you. He confirms that everything is fine, and the certificate too.
