### ISSUE TITLE
Remove   BestChange from the list of merchants

### ISSUE THREAD

**Issue by AiloQito** [monero-project/monero-site#1720]
#### What's the name of the merchant you are asking to remove?

BestChange

#### What's the URL of their website?

https://www.bestchange.com/

#### Why do you think it should be removed?

- [ ] They don't accept Monero anymore
- [ ] They are likely scammers
- [ ] They closed / Their services are unavailable
- [x] This site is not an exchanger

#### Useful links

https://www.bestchange.com/

#### Additional comments

This site is not an exchanger, it is an advertising platform for exchangers, the site does not conduct any exchange but simply earns on referrals.

**Comment by erciccione** [comment]
Ok.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
