### ISSUE TITLE
Add Dr. Apis to the list of merchants

### ISSUE THREAD

**Issue by drapis** [monero-project/monero-site#1726]
#### What's the name of your business?

Dr. Apis

#### What's the URL of the website?

drapis.com

#### Write a brief description of your business/service (max 50 characters)

Raw bee products from Portugal

#### Enter the URL where a Monero mention can be found

https://drapis.com/#order

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [x] Goods
- [ ] Entertainment

#### Comment

Please keep up the awesome work!

**Comment by erciccione** [comment]
> Premium Raw Apiculture products from Portugal * Raw Honey, Comb Honey, Beeswax, Propolis and Bee Bread * Worldwide Shipping

this is not max 50 characters, but beside that, Ok.

**Comment by drapis** [comment]
Hi @erciccione, my bad! Let's shorten it to:
Raw bee products from Portugal

Thank you

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
