### ISSUE TITLE
Add things4monero.com to the list of merchants

### ISSUE THREAD

**Issue by XMRftw** [monero-project/monero-site#1727]
#### What's the name of your business?

 Things 4 Monero

#### What's the URL of the website?

https://www.things4monero.com

#### Write a brief description of your business/service (max 50 characters)

On our site you can buy things from stickers, speakers, cell phones, to even cars

#### Enter the URL where a Monero mention can be found

Be aware of the fact that to be listed, you must specify somewhere on your website that you accept Monero.

https://things4monero.com/?product=big-red-land-rover-defender-110

#### How do you accept Monero? *(choose only one option)*

- [ x] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ x] Goods
- [ ] Entertainment

#### Comment

Hello Our site is still in progress as we are adding our new products and such. People will be able to buy monero from us as well on the site

**Comment by erciccione** [comment]
The website is very much work in progress, most of the pages are empty and there is only one item listed. It doesn't make sense to ad it to the merchants page now. Please reopen this issue after the website is completed.

Rejected.
