### ISSUE TITLE
Wrong merchant removing

### ISSUE THREAD

**Issue by CoinCatEx** [monero-project/monero-site#1729]
Some user confused us with another service or something else and our exchange was mistakenly removed

This user hadn't contacted our support. We have no orders for this sum 12.48 XMR in past 3 weeks.

You can check out lots of reviews of our exchange here:
https://exchangesumo.com/exchanger/933/CoinCat/
https://kurs.expert/ru/obmennik/coincat-in/feedbacks.html
https://bitcointalk.org/index.php?topic=5168201.20

There are lots of exchange listings and forums we are listed on. Please revert this commit since we have no deals with this user.

_Originally posted by @CoinCatEx in https://github.com/monero-project/monero-site/issues/1697#issuecomment-880611148_

**Comment by erciccione** [comment]
We recently decided to reduce the list of exchanges on Getmonero after some reports of fraudolent exchanges. Beside the user report, there were the basis to remove your merchant from the list.

**Comment by CoinCatEx** [comment]
Could you please clarify the basis that our exchange meant to be removed from the list?

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
