### ISSUE TITLE
Add Two Doubloon to the list of merchants

### ISSUE THREAD

**Issue by rayhobbs** [monero-project/monero-site#1730]
#### What's the name of your business?

Two Doubloon

#### What's the URL of the website?

https://twodoubloon.com

#### Write a brief description of your business/service (max 50 characters)

Crypto apparel, stickers, and more!

#### Enter the URL where a Monero mention can be found

https://twodoubloon.com/pages/acceptedcryptos

#### How do you accept Monero? *(choose only one option)*

- Other payment gateway (NOWPayments)

#### How would you categorize your business? *(choose only one option)*

- Goods

#### Comment

We are big fans of creating cryptocurrency awareness and spreading our passion for decentralized money through good-looking designs that are fun to wear!

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
