### ISSUE TITLE
Occidental Technologies missing from merchant list.

### ISSUE THREAD

**Issue by CM-IV** [monero-project/monero-site#1734]
This company was recently approved and merged to the main monero-site.

[Here is the merge pull request.](https://github.com/monero-project/monero-site/commit/0841db2564e8233de886b324b9b8030f8b95dfc1)

However, upon searching the listed merchants with a ctrl + F (Occidental Technologies), the name is not found on the listing under the services section.

![Screenshot 2021-07-15 at 18-18-49  Merchants Services ](https://user-images.githubusercontent.com/44551614/125889497-8ecbadf9-05da-4a63-989f-c0a5753f8d82.png)

I'm not sure why the listing is not showing up, can someone give me some info as to why?

**Comment by erciccione** [comment]
The server hosting getmonero still needs to be updated with the newest code. Please don't open a new issue just to make a question when there is already a dedicated issue and a dedicated pull request. You could have commented under any of the two.
