### ISSUE TITLE
Add CrypTor744 to the list of merchants

### ISSUE THREAD

**Issue by HoverHalver** [monero-project/monero-site#1735]
#### What's the name of your business?

CrypTor744

#### What's the URL of the website?

http://cryptor744w6rl53zcydeqd6s5qi74zbeioicycjccbdxk77qnbaxlqd.onion/

#### Write a brief description of your business/service (max 50 characters)

CrypTor744 = Weekly Cryptos Betting on Tor 

#### Enter the URL where a Monero mention can be found

http://cryptor744w6rl53zcydeqd6s5qi74zbeioicycjccbdxk77qnbaxlqd.onion/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

CrypTor744 has several goals. Among them :
- explore a bit the field of Prediction markets (https://en.wikipedia.org/wiki/Prediction_market)
- help to increase the usage of Monero
- help to increase the usage of Tor and the Torbrowser
- provide another way for people to touch to cryptos

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
