### ISSUE TITLE
Add THE FEMALE CYCLE to the list of merchants

### ISSUE THREAD

**Issue by thefemalecycle** [monero-project/monero-site#1737]
#### What's the name of your business?

The Female Cycle

#### What's the URL of the website?

https://thefemalecycle.love/

#### Write a brief description of your business/service (max 50 characters)

There is so much Wisdom & Beauty in our female topics!

#### Enter the URL where a Monero mention can be found

https://thefemalecycle.love/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [x] wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

When we claim our cycle and know how it works we are empowered in a way that cannot be taken away from us. Just like when we claim our financial privacy...

**Comment by erciccione** [comment]
In theory OK, but consider we are removing the merchants page: #1736

**Comment by thefemalecycle** [comment]
Oh that's too bad :/ Would be such a good way to connect with like minds (&hearts)...

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
