### ISSUE TITLE
Add Silver Coconut to the list of merchants

### ISSUE THREAD

**Issue by lemsmyth** [monero-project/monero-site#1738]
#### What's the name of your business?

Silver Coconut

#### What's the URL of the website?

https//:silvercoconut.com

#### Write a brief description of your business/service (max 50 characters)

Fashion Jewelry, Books, Games, and more. 

#### Enter the URL where a Monero mention can be found

https://silvercoconut.com (any page, right side of footer)

#### How do you accept Monero? *(choose only one option)*

- [ x] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ x] Goods
- [ ] Entertainment

#### Comment

Fashion Jewelry, Vietnamese Coffee Makers, Books, Board Games, Clothing, & more.

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
