### ISSUE TITLE
Add tuxexchange.com to list of Exchanges

### ISSUE THREAD

**Issue by sipherr** [monero-project/monero-site#174]
Please add Tux Exchange (www.tuxexchange.com) to the list of exchanges that support Monero.

https://getmonero.org/getting-started/merchants

Thanks.

**Comment by dEBRUYNE-1** [comment]
#177

**Comment by serhack** [comment]
This issue should be closed,

**Comment by rehrar** [comment]
@sipherr let's go ahead and close this issue :)

**Comment by sipherr** [comment]
Thanks guy. Closed.
