### ISSUE TITLE
Add Real Mad Honey to the list of merchants

### ISSUE THREAD

**Issue by Nickb073** [monero-project/monero-site#1740]
#### What's the name of your business?

Real Mad Honey

#### What's the URL of the website?

www.realmadhoney.com

#### Write a brief description of your business/service (max 50 characters)

Webshop who sells the u rare all natural "Mad Honey"

#### Enter the URL where a Monero mention can be found

https://www.realmadhoney.com/checkout/

#### How do you accept Monero? *(choose only one option)*

- [x] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)
MyCryptoCheckout

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
