### ISSUE TITLE
Add MoneroSMS to the list of merchants

### ISSUE THREAD

**Issue by EgosOwn** [monero-project/monero-site#1741]
#### What's the name of your business?

MoneroSMS operated by VoidNetwork LLC

#### What's the URL of the website?

https://sms.voidnet.tech/
http://rmt3s47llu3e57jch5mzuxmbnb3iuqf7l3sec5ds7tmen7kzrojxhtid.onion/

#### Write a brief description of your business/service (max 50 characters)

Private & cheap mobile and virtual numbers for SMS

#### Enter the URL where a Monero mention can be found

https://sms.voidnet.tech/

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [X] Service
- [ ] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
