### ISSUE TITLE
Add CoinRabbit to the list of merchants

### ISSUE THREAD

**Issue by DanFromCoinRabbit** [monero-project/monero-site#1742]
#### What's the name of your business?

CoinRabbit

#### What's the URL of the website?

http://coinrabbit.io

#### Write a brief description of your business/service (max 50 characters)

Earn & Borrow Crypto At Any Market Conditions

#### Enter the URL where a Monero mention can be found

https://coinrabbit.io/loans/xmr

#### How do you accept Monero? *(choose only one option)*

- [x] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [x] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Your cryptocurrency should work for you right now. Without waiting for the rate to rise to the desired level, without fear of losing it. We have created a solution that allows you to borrow and earn quickly and safely.

**Comment by DanFromCoinRabbit** [comment]
Dear @erciccione 

We sent a request for adding us to the list of merchants about a month ago. Are there any updates regarding this matter?

_Regards,

Dan from CoinRabbit_

**Comment by erciccione** [comment]
Hello, we are in the process of changing the 'Merchants' page (https://github.com/monero-project/monero-site/issues/1736). All current exchanges and merchants will be removed, so there is no point in adding new ones, since they will be removed anyway soon.

**Comment by DanFromCoinRabbit** [comment]
> Hello, we are in the process of changing the 'Merchants' page (#1736). All current exchanges and merchants will be removed, so there is no point in adding new ones, since they will be removed anyway soon.

Hello @erciccione 

Thank you for the answer.

In this case, our project would like to be present in your updated section.

In addition, since we fit the definition of "tools", please consider our application to be added to the Market section here https://www.getmonero.org/resources/tools/

Thank you very much and we are waiting for new updates both from the Monero asset itself and for the sections of the website. 

Have a good day!

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
