### ISSUE TITLE
Developer Guides: globe icon not being displayed on Chrome and Internet Explorer

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-site#1751]
It is being displayed correctly on Firefox.

![image](https://user-images.githubusercontent.com/45968869/127778085-05df5646-dd42-4b33-8924-37f2607ab3ac.png)

**Comment by erciccione** [comment]
What operating system are you using?

I just tried Chromium and Chrome and all seems to be working well.

**Comment by erciccione** [comment]
This seems to happen only on windows. I fixed by replacing the unicode images with SVGs. This will also make the page more uniform and less prone to this kind of problems: #1755

**Comment by rating89us** [comment]
> This seems to happen only on windows. 

Yes, I'm using windows. Your PR fixes this issue.
