### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> JACK VELOUR

### ISSUE THREAD

**Issue by jackv18** [monero-project/monero-site#1760]
#### What's the name of your business?

Jack Velour

#### What's the URL of the website?

www.jackvelour.com

#### Write a brief description of your business/service (max 50 characters)

Magician for hire anywhere in the world. Private events and company gatherings. 

#### Enter the URL where a Monero mention can be found

https://www.jackvelour.com/booking

https://

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ X] Native wallet 
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ X] Entertainment

#### Comment

I am a professional magician who performs all over the world and I also accept Monero!

**Comment by devuana** [comment]
@jackv18 , maybe you should consider editing the title of your issue.

The title sould look like this:

> Add **Jack Velour** to the list of merchants

**Comment by devuana** [comment]
@jackv18 , a short update on my comment. 

There is an open issue for removing the merchants page (#1736 ), so you can take a look on that.

**Comment by jackv18** [comment]
Okay, thanks.

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
