### ISSUE TITLE
Introduce i18n system for the Moneropedia

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#1780]
The Moneropedia is currently in the same situation the user guides were before the refactor (see #1270). All Moneropedia entries should be easy to update and translate. Also, new entries should be added painlessly. This is not the case at the moment.

The basic idea is to use po4a as we do for the user guides to translate the content of each Moneropedia entry.

The problem is that the Moneropedia is more challenging to refactor than the user guides, because we also have to consider the ruby plugin that parses tooltip descriptions (which shows up when hovering on a word preceeded with `@` ) and an array of terms.

We could keep most of the original structure and use a combination of po4a + a script parsing only what's necessary to translate (so leaving out the front matter of each Moneropedia entry), but that would increase complexity quite a lot, since we would need to add an additional script to strip entries from their front matter, and then a "bridge" file containing the stripped entries to translate. Then po4a would work on this bridge file, feeding Weblate with strings to translate.

That's not idea, IMO the best solution is to do basically what we did in #1270 and get rid of the `moneropedia.rb` plugin. The hyperlinks to the Moneropedia entries that we have spreead across the website are useful. I would keep them but instead of triggering them with `@` we can add them manually with html + CSS. This will result in slightly more complexity for translators, but if they are correctly instructed to leave those strings alone, shouldn't be an issue.

If there are no better suggestions, i'll work on this. Note that because of the ruby script, it might be not feasible to make multiple PRs with the changes like i did with the user guides, but i might have to do a single big PR with most of the needed changes.

**Comment by devuana** [comment]
Seems a good idea to me. This way it will be much easier to 'track the status of a translated file and to reliably update the entries', as you mentioned in #1270. Plus Weblate seems an easier solution for onboarding new translators.

**Comment by erciccione** [comment]
After some testing, i realized that refactoring `@` links to work with only css + html is not really feasible. yaml files don't support liquid formatting, so we would need to split a paragraph every time a word needs to be linked to a Moneropedia. Not really convenient.

What we can do is to keep the structure mostly as it is. The content of the front matter would be parsed by po4a, which will display it like this (will be then parsed by Weblate):

```
"terms: [\"account\", \"accounts\", \"wallet\", \"wallets\"]\n"
"summary: \"similar in function to a bank account, contains all of your sent "
"and received transactions\"\n"
```

There is some complexity added by the `\` before `"`. People not familiar with escaping characters will be confused at first, but i think won't be a problem if we add clear instructions on these strings on Weblate (we already add instructions to multiple strings).

Translators would be instructed to add translated `terms` after the last English one (in this case `"wallets"`) and to translate the content of `summary:`.

**Comment by erciccione** [comment]
Just PRd #1876, which makes the last Moneropedia entry (wallet.md) trnaslatable on Weblate. I also PRd the adjustements to the README with #1877.

After all the PRs listed above will be merged, we will only need to add all the guides on Weblate, then this issue will be considered resolved.

**Comment by erciccione** [comment]
Almost all PRs have been merged (only one missing). We can start the process of adding the moneropedia entries on weblate. Now that there is a structure for internationalization, Moneropedia entries can be edited safely.

**Comment by netrik182** [comment]
> Almost all PRs have been merged (only one missing). We can start the process of adding the moneropedia entries on weblate. Now that there is a structure for internationalization, Moneropedia entries can be edited safely.

I'd like to collaborate on adding them to Weblate ErCiccione. Please let me know when you have time. We can coordinate on matrix as always.

**Comment by netrik182** [comment]
Moneropedia added to Weblate: https://translate.getmonero.org/projects/getmonero-moneropedia/

**Comment by erciccione** [comment]
This is completed.
