### ISSUE TITLE
Add <NAME OF YOUR BUSINESS> to the list of merchants

### ISSUE THREAD

**Issue by Roverid** [monero-project/monero-site#1785]
#### What's the name of your business?

Labeloom

#### What's the URL of the website?

https://www.labeloom.com

#### Write a brief description of your business/service (max 50 characters)

Website to buy custom woven and printed labels

#### Enter the URL where a Monero mention can be found

https://labeloom.com/apps/FAQ#hc-what-payments-do-you-accept

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [X] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [X] Goods
- [ ] Entertainment

**Comment by devuana** [comment]
@Roverid, maybe you should consider editing the title of your issue. Substitute `<NAME OF YOUR BUSINESS>` with the actual name of your business. 

The title sould be:

> Add **Labeloom** to the list of merchants

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
