### ISSUE TITLE
Obsolete reference to the Core Team's assistant

### ISSUE THREAD

**Issue by thomasvaughan** [monero-project/monero-site#1787]
The “Contributing” page (https://www.getmonero.org/get-started/contributing) says “Donations to the general fund are used to pay the salary of core's assistant”. My understanding is that the Core Team no longer has a paid assistant.

**Comment by erciccione** [comment]
This is already resolved by https://github.com/monero-project/monero-site/pull/1776. Needs only to be deployed on Getmonero.
