### ISSUE TITLE
Michael's Book Corner

### ISSUE THREAD

**Issue by mscharen** [monero-project/monero-site#1788]
#### What's the name of your business?

Michael's Book Corner

https://michaelsbookcorner.com

Book sales/blog for science-fiction author Michael J. Scharen

https://michaelsbookcorner.com

https://michaelsbookcorner.com/cryptoCurrencyPayments.html

https://michaelsbookcorner.com/bookCornerCart.html

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ X] NowPayments.io
#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ X] Goods
- [ ] Entertainment

#### Comment

Michael's Book Corner and author Michael J. Scharen believe in consumer privacy and we believe in Monero.

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
