### ISSUE TITLE
Add XMRStickers.com to the list of merchants

### ISSUE THREAD

**Issue by xmrstickers** [monero-project/monero-site#1794]
#### What's the name of your business?

 "monero stickers" / "xmr stickers" 

#### What's the URL of the website?
xmrstickers.com (preferred) or monerostickers.com (redirects to xmrstickers.com)

#### Write a brief description of your business/service (max 50 characters)

Using entirely open-source solutions, this website accepts monero and monero **only** in exchange for monero-themed stickers. 

#### Enter the URL where a Monero mention can be found

The only payment option is monero - the home-page header says "Selling monero stickers, in exchange for monero."

https://xmrstickers.com

#### How do you accept Monero? *(choose only one option)*

- [ X] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ X] Goods
- [ ] Entertainment

#### Comment

My short-term vision is to sell the single design I have and re-invest all profits back into the business such that it can offer more designs and multiple sizes; after a sufficient sticker selection is established (3+ variations, 2+ sizes), I plan on donating 10% of all profits to the monero general fund and/or promising community proposals. This website gives me a fun, real-world exercise in practically accepting monero as a business, and I look forward to both sharing my experience and, hopefully, giving back to the community if successful!

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
