### ISSUE TITLE
Incorrect Example Wallet RPC Docs For get_version

### ISSUE THREAD

**Issue by elibroftw** [monero-project/monero-site#1806]
https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#get_version

Firefox
![image](https://user-images.githubusercontent.com/21298211/131772375-fa4fcc1c-db95-43f1-80a1-3853a791c6e7.png)
Chrome
![image](https://user-images.githubusercontent.com/21298211/131772652-3eaee09b-3088-420c-a368-65f3b35a39b8.png)

There is no underscore visually available, but if I copy the text, an underscore is there. This seems to be a line-height issue so my recommendation: set `line-height: 1.4rem;` for `code`

**Comment by erciccione** [comment]
Changed to 1.4 in #1808 as suggested.
