### ISSUE TITLE
Add Swirlwallet to the list of merchants

### ISSUE THREAD

**Issue by swirlwalletadmin** [monero-project/monero-site#1811]
#### What's the name of your business?

Swirlwallet

#### What's the URL of the website?

https://swirlwallet.com/

#### Write a brief description of your business/service (max 50 characters)

Wallet Service with Exchange option.

#### Enter the URL where a Monero mention can be found

https://swirlwallet.com/home

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ ] Native wallet
- [X] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [X] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Web Hosting
- [ ] Tool
- [ ] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

Thanks for your consideration. If there is any further required information please inform me.
Thank you.

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
