### ISSUE TITLE
AnonCoj - a P2P marketplace

### ISSUE THREAD

**Issue by anoncoj** [monero-project/monero-site#1813]
AnonCoj is a Monero-alone marketplace based on Agora philosophy.
Anoncoj (pronounced Anon-Tsoi) or "Classifieds" in Esperanto  is an anonymous P2P place to buy or sell goods and services for monero. 
Our aim is to make AnonCoj a 'Pli bona merkato'. Note that forum is still in in alpha version.
the front and backend are both opensource and currently less than 100 active users,  we are looking to make this platform more known to XMR users.  link: AnonCoj.ch

**Comment by HardenedSteel** [comment]
Hello, what is this for? Also i couldn't find website's link.

**Comment by anoncoj** [comment]
Hi, it is an alpha version of an XMR-P2P platform. Updated the link.
The site is opensource is a copy of Flarum.

**Comment by erciccione** [comment]
The merchants page has been removed (#1736). Closing this issue.
