### ISSUE TITLE
New FAQ: "What is Monero's maximum supply?"

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#1817]
This question is sadly very poorly indexed on most search engines. We recently had a major exchange produce a video about XMR saying the max supply was 18.44 million coins.

Q: What is Monero's maximum supply?

A: Monero has a fixed emission rate, not a set maximum supply. Around May 2022, Monero's emission will drop to and permanently remain at 0.3 XMR per minute (0.6 XMR per block). This is approximately 1% inflation for the first year, asymptotically approaching 0% inflation in future years. This [tail emission](https://www.getmonero.org/resources/moneropedia/tail-emission.html) allows for permanent incentives to secure Monero, even in the far future, while keeping inflation at a very low %.

**Comment by erciccione** [comment]
#1818. Note that i did some small changes (removed asymptotically to simplify the text). Please review.
