### ISSUE TITLE
Add AnyCOLO.Net to the list of merchants

### ISSUE THREAD

**Issue by anycolo** [monero-project/monero-site#1822]
#### What's the name of your business?

AnyCOLO.Net

#### What's the URL of the website?

https://anycolo.net

#### Write a brief description of your business/service (max 50 characters)

AnyCOLO.Net - Buy VPS Hosting and pay with Monero

#### Enter the URL where a Monero mention can be found

https://anycolo.net/

#### How do you accept Monero? *(choose only one option)*

- [x] BTCPAYSERVER with Monero ADDON

#### How would you categorize your business? *(choose only one option)*

- [x] Web Hosting

#### Comment

We are available for talk at: administrator@anycolo.net

**Comment by erciccione** [comment]
Hello. We recently changed the purpose of the "Merchants" page and now it doesn't list merchants anymore (see #1736), so we are going to close this issue. Now we list 2 merchants directories:

- https://cryptwerk.com/pay-with/xmr/
- https://www.acceptedhere.io/catalog/currency/xmr/

Consider requesting to be added to one of the directories above if your service fits.
