### ISSUE TITLE
Merchant Labels

### ISSUE THREAD

**Issue by HardenedSteel** [monero-project/monero-site#1884]
We should remove merchant and merchant removal labels from Github repo.

**Comment by erciccione** [comment]
Is there a specific reason to remove them? As far as i know it doesn't matter if we don't use them, but we could also user them again in the future. People could still propose additions to the page.

**Comment by HardenedSteel** [comment]
> we could also use them again in the future.

Didn't we remove merchant page already? Why could we use them again? @erciccione

**Comment by erciccione** [comment]
Because there is still a 'Merchants & Exchanges' page. This is a non issue regardless and removing labels is not really useful. Closing.
