### ISSUE TITLE
Localmonero 9000usd Scam and must be removed from getmonero.org/community/merchants/

### ISSUE THREAD

**Issue by LocalMoneroScam** [monero-project/monero-site#1889]
you have listed LocalMonero as trusted place to trade monero here https://www.getmonero.org/community/merchants/
Online P2P exchange offering person-to-person trades.

How can you allow such scam project be listed on your website?

here is my story how they steal my 35 XMR and looks like i am not the only one
https://www.saashub.com/localmonero-reviews

Next step i am going to Bitcointalk to rase this issue, people has to know what scam localmonero is!!!!!!!!

The Admin of Agoradesk.com/LocalMonero.co telegram group https://t.me/LocalMonero is a Scumbag. His telegram is https://t.me/Alex_LocalMonero_AgoraDesk

This is a screenshot of my chat with him https://ibb.co/Nxfxxgb

I've know about LocalMonero for about a year but didn't really trusted them because it is shitty centralised platform and outdated website looks like crap, it doesn't build trust at all. And now, after loosing my money I know I should avoid even registering with them.

Agoradesk.com/LocalMonero.co scammed me for 9500 usd by blocking my account right after I deposited another 10 xmr

This is my account https://agoradesk.com/user/audy

You can see they add a message=reason  inventing an excuse to steal my money, linking me to other profile who, I found out later, Alex admin of Localmonero had an argument with.

As I see now LocalMonero admin decided to co er his lose on my account. If they do it over 9500 usd than this means they have no trading volume and profit and ready to take your money just like that. They will make it look like it is your fault or whatever.

Check this https://t.me/MoneroUK/12051
I contacted this guy and asked him what happened between him and Localmonero(scammers) and it looks like I am not the first one who was scammed by localmonero aka agoradesk
 
Avoid this scammers and your money will be saved.

That was my last time I ever user centralised exchanger. It is 3rd time I got burned.

LocalMonero aka AgoraDesk is scam!!!!
Stay away from it!!!!

**Comment by erciccione** [comment]
> you have listed LocalMonero as trusted place to trade monero here 

None of the exchanges listed on getmonero are considered trusted. As the disclaimer at the bottom of the page says, you should make your own researchers before using any online service.

That said, if you are having problems with localmonero, please contact their support. From the content of the links and screenshots you posted i don't think makes sense to keep this issue open.

**Comment by LocalMoneroScam** [comment]
> > you have listed LocalMonero as trusted place to trade monero here
> 
> None of the exchanges listed on getmonero are considered trusted. As the disclaimer at the bottom of the page says, you should make your own researchers before using any online service.
> 
> That said, if you are having problems with localmonero, please contact their support. From the content of the links and screenshots you posted i don't think makes sense to keep this issue open.

I totally understand it is my fault that i got scammed

But you should remove them form your website and do not recommend other people to get scammed like i was.

 **i was scammed not by one of their users but admin itself, pls check the screenshot of what he told me!!!**

Scam exchangers cannot be listed on your website, i am pushing this case further to other portals and forums
