### ISSUE TITLE
 Addition for Merchants List: VoteForRodneyLewis.com

### ISSUE THREAD

**Issue by pyrodney** [monero-project/monero-site#189]
Addition for Merchants List:

Link: "Web Developer - VoteForRodneyLewis.com"
Target: "http://www.VoteForRodneyLewis.com"

I am a web developer using Python with the Django web framework.

Thank you for your assistance.  It is an honor to be in your directory!

**Comment by QuickBASIC** [comment]
@pyrodney I don't see anywhere on your site that says you accept Monero and I'm not sure what you're selling. Can you please clarify why you want to be listed on our merchant list for the Monero site?

**Comment by QuickBASIC** [comment]
@pyrodney

There still doesn't seem to be any indication on your site that you accept Monero.

+stale
+merchant
