### ISSUE TITLE
Binaries mixed up?

### ISSUE THREAD

**Issue by TimGalloo** [monero-project/monero-site#1901]
shasum -a 256 monero-gui-linux-x64-v0.17.3.0.tar.bz2
ac18ce3d1189410a5c175984827d5d601974733303411f6142296d647f6582ce  monero-gui-linux-x64-v0.17.3.0.tar.bz2

 shasum -a 256 monero-linux-x64-v0.17.3.0.tar.bz2
ac18ce3d1189410a5c175984827d5d601974733303411f6142296d647f6582ce  monero-linux-x64-v0.17.3.0.tar.bz2

same hash = same files ?

**Comment by selsta** [comment]
Can't reproduce. Where did you download this file?

**Comment by TimGalloo** [comment]
Getmonero.org

**Comment by TimGalloo** [comment]
Getmonero.org but now ok
Issue can close
