### ISSUE TITLE
Redesign Concept - Reddit Thread

### ISSUE THREAD

**Issue by HardenedSteel** [monero-project/monero-site#1904]
I would like to bring discussion to here, current design is not aesthetic. Someone made a redesign at Reddit, what's your opinions about it? 
Reddit thread: https://redd.it/pr8x6v

**Comment by HardenedSteel** [comment]
I think we can keep old design like at lite.getmonero.org and when the user doesn't have javascript it can redirect to old design.

**Comment by erciccione** [comment]
Maintaining two different websites is highly unrealistic.
