### ISSUE TITLE
Setup 'hooks' for Weblate integration

### ISSUE THREAD

**Issue by netrik182** [monero-project/monero-site#1907]
Hello,

I'd like to ask a repo/project maintainer to add the following URL to the hooks config of the repo: https://translate.getmonero.org/hooks/github/

This will enable us to activate continuous localization as described here: https://docs.weblate.org/en/weblate-4.8/admin/continuous.html#github-setup

Thanks

**Comment by erciccione** [comment]
While this would be convenient from some points of view, some projects on weblate, like user guides and moneropedia on getmonero, require to trigger scripts manually. Probably better keep things as they are. Closing this, feel free to repoen if it requires further discussion.

**Comment by plowsof** [comment]
+1
