### ISSUE TITLE
Listing on the Merchants&Exchanges page

### ISSUE THREAD

**Issue by SZ-olya** [monero-project/monero-site#1926]
Hey, I'm Olya, a marketing manager from [swapzone.io](https://swapzone.io/) aggregator of crypto exchanges. We've been supporting XMR non-custodial swaps since the inception of our service and we'd be grateful if you placed our link under the Swappers section on the Merchants&Exchanges page. 
ps Swapzone - this is the right spelling. NOT SwapZone.

**Comment by HardenedSteel** [comment]
duplicate of #1970, issue can be closed @erciccione
