### ISSUE TITLE
wrong link to github site repository on Workgroups page

### ISSUE THREAD

**Issue by monetory** [monero-project/monero-site#1928]
on this [Workgroups page](https://web.getmonero.org/community/workgroups/index.html )
link to Website Workgroup github is `https://web.getmonero.org/community/workgroups/index.html#` 
must be `https://github.com/monero-project/monero-site`

![image](https://user-images.githubusercontent.com/99361157/153306007-e6807423-dcaf-4733-881e-c0d96ba02df3.png)

**Comment by selsta** [comment]
Thanks! Opened #1929 to fix it.
