### ISSUE TITLE
Please update or omit an outdated statement on the GetMonero.org website

### ISSUE THREAD

**Issue by LiveFree1776** [monero-project/monero-site#1934]
Hello,
On the website https://www.getmonero.org/get-started/what-is-monero/ there is an outdated statement:

"Unlike selectively transparent alternatives (e.g. Zcash), Monero is the only cryptocurrency where every user is anonymous by default."

Although it may have been true when written, Monero can no longer claim to be the "only" cryptocurrency that is anonymous by default. It may be the most trusted, time-tested, and peer-reviewed privacy crypto but it is no longer the "only" one. Could this be updated or changed by someone to reflect reality? Probably the simplest thing to do would be to change it to

"Unlike selectively transparent alternatives (e.g. Zcash), Monero is anonymous by default."

But it can be changed to anything as long as it is not a falsehood.

Thank you!

**Comment by monerochan-moe** [comment]
he doesn't know what a pull request is and thinks a wagie is going to come here modify the html for him
![pepelaughz](https://user-images.githubusercontent.com/90231001/157584879-8e2e92f9-d61e-42a4-8ff6-5a9403699454.jpg)

**Comment by LiveFree1776** [comment]
Of course I don't know what a "pull" request is. Who does? This literally is my first day on github. People told me if you want it to change make a request. So here I am. You can't say I didn't try to be the change I seek.

**Comment by erciccione** [comment]
@monerochan-moe please refrain from trolling. People are allowed and welcome to open issues even if they don't know how to open pull requests. One thing doesn't exclude the other.

@LiveFree1776 I see your point. Maybe we could change it to something like "The only major cryptocurrency...". That would be more correct.

**Comment by plowsof** [comment]
Please close, issue solved :+1:
