### ISSUE TITLE
Update 2022-2023 roadmap to include the primary features in the v15 hard fork

### ISSUE THREAD

**Issue by kowalabearhugs** [monero-project/monero-site#1937]
The roadmap is currently outdated: https://www.getmonero.org/resources/roadmap/

The 2022 roadmap should be updated to include the primary features set to be deployed with the v15 hard fork (Monero v0.18.0): https://github.com/monero-project/meta/issues/630

The roadmap for 2023 could include the current research being done into Seraphis & JAMTIS, decoy binning, OPSEAD, and more.

**Comment by plowsof** [comment]
I've done the adjustments (merged 2017 into the 2014-2016) tab. and put the mentioned suggestions in (albeit with incorrect status, lets discuss what needs to be added / changed - or if something needs to link somewhere)
![rm_1](https://user-images.githubusercontent.com/77655812/169704082-66832da0-0f2d-41c5-9344-c9f01ffbddce.png)
Added to december 2021:
![rm_4](https://user-images.githubusercontent.com/77655812/169704098-b4a38a28-c257-472b-ac42-e174a0bb0ea3.png)
![rm_3](https://user-images.githubusercontent.com/77655812/169704109-4fa496ff-c60a-46a1-bfc2-8b249412232b.png)

 "increase ring size to 100+ through Seraphis or Triptych"  is a suggestion for being listed in 'Future'

**Comment by HardenedSteel** [comment]
@plowsof will you create pull request?
