### ISSUE TITLE
German - index.html href error 404 

### ISSUE THREAD

**Issue by nice42q** [monero-project/monero-site#1939]
https://www.getmonero.org/de/index.html
The Hyperlink "Arbeitsgruppen" in the footer is linked wrong (404)

**Comment by erciccione** [comment]
Thanks @nice42q :)

The i18n links are not being redirected. @binaryFate  we need a redirect for `https://www.getmonero.org/$LANG/community/team/` -> `https://ww.getmonero.org/$LANG/community/workgroups/`. Right now it's working only for the English version.

**Comment by binaryFate** [comment]
Ah yes, sorry that was on me.
I'll post here to confirm when done.

**Comment by binaryFate** [comment]
Ok I fixed it and tested successfully. Can someone else check too?

**Comment by nice42q** [comment]
> Ok I fixed it and tested successfully. Can someone else check too?

No more 404 error.
But it redirects to English instead of the selected language.

**Comment by binaryFate** [comment]
@nice42q sorry, please check again

**Comment by erciccione** [comment]
Seems to be working now. @nice42q if everything is ok now, please close the issue.
