### ISSUE TITLE
Addition to the Merchant page under Services - ELG

### ISSUE THREAD

**Issue by FilipinoLawyer** [monero-project/monero-site#194]
Please add to the Merchant page under Services;

Text: Emmanuel Galang, Canada Immigration and Refugee Lawyer
Link: www.galanglaw.com

Thank you!

**Comment by QuickBASIC** [comment]
@FilipinoLawyer Can you confirm that your business still accepts Monero? I don't see it listed in any way on your site.

**Comment by FilipinoLawyer** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hello Mike. Yes I still accept Monero. Thank you.


On 17-08-31 08:50 AM, Mike Justman wrote:
> @FilipinoLawyer Can you confirm that your business still accepts Monero? I don't see it listed in any way on your site. >
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBAgAGBQJZrybVAAoJEA/3I7be0JyPxEoQAKidw9umye4e6h3wuz8db2qK
Tb4810BTLaNWs22N/K9ONVM2WhbilkUxeTEy2soPIOINsF3mI4URtc/IMuz/vUmu
9pPmpXVtyKDN2RL9x4kPRHMJGxhpl89NUeD/coacQ6jdip38IafSOuR+7F22QMZ7
TPgje7x5DuTvcVpn0cHL2i4KZvx7Tq+i98TpcuK19V6N6EfkJktVGrx1xoe2sIh9
F5LKIoK/49iEUkRYXeyWMgDO8G6uELneQOyqaSIsOcpNBCaA43w6OlMCTV9qmUKv
YNlGzrdT9oXmpUmmjIHs3oQ7qdvCawgrYgI6KE21f5YRmohKbzrMTRUkNCARKsz4
sRFsDn41NLFJj9JeMxD00ORJDNrV0spxQjyip+emvb3Aw5KIUe1kw4QOA4+OqG24
nITIC/BrSUzZns0eLeZtM+ate2DnTeclgqAATCPdO8UAw92H3JjbBmN8yzNEKekW
BmZYG8G/F0Ad6eyKbDSJ8W46yWFT+x3LCy1MOOLIyZ3ecFO4Coab3yJrzy2fYF7f
L5fAtK1R1XwJLOR7CPKQdl6NHC7f0P589kmi4fXJqVNB+kQYmSeX4bXtGy9u4MlT
F/+FvcghqzMS/JqK25qkRAv8+Xy/WpwE4p05FJ837fm7hXP+ogva04jz4MrT01+U
xuf4diMuBu0HvtgoxSBd
=iRWm
-----END PGP SIGNATURE-----

**Comment by QuickBASIC** [comment]
Thank you. It looks like your site is already listed on the merchant directory... I just wanted to be sure before we closed the issue.
