### ISSUE TITLE
HTTP404 (broken link)

### ISSUE THREAD

**Issue by Alexxhn** [monero-project/monero-site#1944]
On page https://www.getmonero.org/get-started/mining/ there's a link under text 'More details in the announcement post.' that leads here: https://www.getmonero.org/get-started/mining/%7B%7B%20site.baseurl%20%7D%7D/2021/10/05/p2pool-released.html which is not found (HTTP404)
As far as I found it - the correct link should be https://www.getmonero.org/2021/10/05/p2pool-released.html

**Comment by plowsof** [comment]
Please close, issue fixed :+1:
