### ISSUE TITLE
Moneropedia address article clarification

### ISSUE THREAD

**Issue by alphatomcat** [monero-project/monero-site#1947]
In the [Moneropedia address article](https://www.getmonero.org/resources/moneropedia/address.html)  it says raw addresses start with a 4, and then it seemingly gives the monero donation address as an example, which does not start with a 4. Could this do with some clarification?

**Comment by moneroguides** [comment]
yea, that's pretty poor. the example should definitely follow the definition.

**Comment by Mark-777-0** [comment]
https://github.com/monero-project/monero-site/pull/1990

**Comment by Mark-777-0** [comment]
Not sure how to link my pull request here, sorry I'm very new @moneroguides @alphatomcat @erciccione .

Let me know if I broke any etiquette, and how to do better next time 👍

**Comment by Mark-777-0** [comment]
I can update the other languages if it's not a bad edit

**Comment by Mark-777-0** [comment]
@alphatomcat @erciccione let me know :)

**Comment by Mark-777-0** [comment]
@erciccione would you like me to do the other languages as well now?

**Comment by erciccione** [comment]
@Mark-777-0 language files shouldn't be edited on the repository or we risk conflicts on Weblate. The PR will do it fine :)
