### ISSUE TITLE
We should add the following question to the FAQ

### ISSUE THREAD

**Issue by FeatureSpitter** [monero-project/monero-site#1963]
I just saw, yet another thread, discussing the inflation topic on Monero.

https://www.reddit.com/r/Monero/comments/un5jwz/inflation_in_monero/

This is such a common question, that monero should address it on their website.

Many people don't understand this and avoid Monero because of it, because they perceive this as a design flaw.

Remember folks, if you want Monero's adoptions, you should not treat everyone as if they have a PhD in macro economy. If my granny isn't able to understand Monero, then we are doing a terrible job at marketing it.

Unfortunately I am not smart enough to provide a good FAQ answer for this, so could someone please push this?

**Comment by citrus-flagman** [comment]
I could write an FAQ answer for this. I think we might want to wait until the end of the month (when tail emission begins) to add it so we don't risk the answer becoming immediately out of date. I will look into this for you @FeatureSpitter

**Comment by FeatureSpitter** [comment]
Thanks! Awesome!
