### ISSUE TITLE
Improve Magazines section of the Library page

### ISSUE THREAD

**Issue by LeoNero** [monero-project/monero-site#1976]
The current Magazines section lists two "Revuo Monero" editions from 2017.

I believe the section could be improved by removing the two links and add links to the Revuo website (https://revuo-xmr.com/), to 
 The Monero Moon (https://www.themoneromoon.com/), and maybe to Monero Outreach (https://www.monerooutreach.org/).

**Comment by erciccione** [comment]
Agreed the page needs an update.

> add links to the Revuo website (https://revuo-xmr.com/)

This specific link won't be added. The author is unreliable (he has an history of manipulating data and logs for his personal gains), is known for harassing multiple Monero community members (including death threats) and is currently banned from most Monero for all kind of toxic behaviours (including doxxing Monero contributors).

**Comment by LeoNero** [comment]
@erciccione didn't know about that. Thank you for the update!!

**Comment by HardenedSteel** [comment]
I think we need to rename "Magazines" title because these resources are newsletter more than magazine.

**Comment by erciccione** [comment]
Thanks to people like you i stopped my contributions to Monero, so you won't see more commits from me, but that only means that you made the project lose one of its most active contributors. I'll still be around doing my best to make sure what's left of the sane part of the Monero community has a chance to work as it did in past: without being forced to fear harassments, threats and doxxing. All activities you have repeatedly engaged in the recent past.

Of course, who has familiarity with the monero repositories and doesn't only show up to create chaos or attempt to remove the contributors they don't like, knows i never had gatekeeping powers on this repo, but i do have opinions that i'm free to share. For the reason i said, I'm still against listing on getmonero anything produced or contributed by @rottenwheel.

**Comment by nahuhh** [comment]
Erc needs to step down from all admin roles.
When itvwas decided to reinstate rottenwheel, erc decided he doesnt care and will do what he wants.

has a modbot on his own server in monero-site (a monero owned libera namespace) with special rules to ban rottenwheel.

His contributions to the repo are appreciated. His "contributions" by way of admin/mod to our social networks has been nothing short of terrible. 

an admin (erc) started attacking luigi and plowsof in public over a bumpy restart to CCS. Erc closed his ccs in protest, missed the funding, then banned ofrnxmr in "all rooms i admin" after protesting to have a casual community member banned for tastelessly trolling a spam comment.

![b60yzjxclcu97ag3.jpg](https://github.com/monero-project/monero-site/assets/50635951/62c39a0c-ea07-47e3-83ec-0049a7a50c09)

**Comment by HardenedSteel** [comment]
> He claims that he does not gatekeep, but Feather Wallet did not get listed until his criteria was met, as you may see in https://github.com/monero-project/monero-site/pull/1379. Technically he did not pull the lever, but in practice, things were run the way he said or no other way, like a little bossy brat.

@rottenwheel: Also @selsta didn't approve the PR alongside with @erciccione, its not fair to say Feather wallet didn't listed because of @erciccione. Also the PR only got comments from only 2 different persons.
