### ISSUE TITLE
Some websites not working in the resources/tools/ page

### ISSUE THREAD

**Issue by LeoNero** [monero-project/monero-site#1980]
The ones not working:
- https://www.exploremonero.com/
- https://xmr.llcoins.net/ (certificate not valid)
- https://monerohash.com/nodes-distribution.html
- https://nownodes.io/connect-xmr-node (link to https://nownodes.io/nodes/monero-xmr instead?)
- https://www.backtestking.com/
- https://monerobase.com/
- https://vigla.biz/

**Comment by HardenedSteel** [comment]
https://www.backtestking.com, https://monerobase.com and https://vigla.biz are don't work. https://nownodes.io/connect-xmr-node is gives 404 error. Rest of them works fine.

**Comment by LeoNero** [comment]
Thank you for accessing the links again!

**Comment by erciccione** [comment]
Removing the broken resources pointed out by @HardenedSteel: https://github.com/monero-project/monero-site/pull/2012
