### ISSUE TITLE
Add nixt.io to payment gateways section of 

### ISSUE THREAD

**Issue by nixt7** [monero-project/monero-site#1981]
Hello
I would like to suggest adding nixt.io to the [Merchants&Exchanges](https://www.getmonero.org/community/merchants/) page.

"NIXT" is anonymous payment system 

Logo:
![logo](https://user-images.githubusercontent.com/105312507/173250340-e2b7ae6e-7bba-4403-882e-2a6c38e18c20.png)

Description:

"NIXT"  is anonymous payment system with friendly interface and simple to use implementation of accepting crypto-payments.

Open source: x
Non-custodial: +
No KYC (Know Your Customer): +
Onion address: x
link: [https://nixt.io](https://nixt.io)

**Comment by HardenedSteel** [comment]
[Merchants & Exchanges](https://www.getmonero.org/community/merchants/) page is not appropriate for this. It should be at [resources > tools](https://www.getmonero.org/resources/tools/)

**Comment by nixt7** [comment]
> [Merchants & Exchanges](https://www.getmonero.org/community/merchants/) page is not appropriate for this. It should be at [resources > tools](https://www.getmonero.org/resources/tools/)

Why not there? :) That's fine

**Comment by erciccione** [comment]
@nixt7 please open a new PR for adding this service in the "tools" section.
