### ISSUE TITLE
New merchant accepting Monero

### ISSUE THREAD

**Issue by zoolbia** [monero-project/monero-site#199]
Wanted to notify that, my company started accepting Monero from last week in Goteborg / Sweden:

website: [www.LagaiPhone.se](url)
cellphone and laptop repair online store in Sweden

**Comment by KristijanZic** [comment]
How do you account those transactions of goods/services for monero in your books? Is it legal?

**Comment by serhack** [comment]
This should be closed.

**Comment by rehrar** [comment]
@zoolbia can we close this issue please? thanks.
