### ISSUE TITLE
Missing wallet rpc methods in wallet-rpc.md

### ISSUE THREAD

**Issue by MexicanTakeout** [monero-project/monero-site#1993]
A few methods I found missing in wallet-rpc.md while checking wallet_rpc_server.h
from [here](https://github.com/monero-project/monero/blob/9750e1fa103539b3e533455500610aae76e253a5/src/wallet/wallet_rpc_server.h#L70)
... to [here](https://github.com/monero-project/monero/blob/9750e1fa103539b3e533455500610aae76e253a5/src/wallet/wallet_rpc_server.h#L163)

- freeze
- thaw
- frozen
- sweep_unmixable
- scan_tx 
- exchange_multisig_keys
- set_log_level
- set_log_categories
- estimate_tx_size_and_weight

Let me know if you need a script showing these diffs.

**Comment by eversinc33** [comment]
sweep_unmixable is available in the documentation as sweep_dust (where the former is an alias for the latter).

Came here to open an issue about the same thing though.

**Comment by plowsof** [comment]
closed by #2083
