### ISSUE TITLE
getmonero.org/how-to-ccs Has strangely broken link

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-site#2015]
If you visit https://ccs.getmonero.org/how-to-ccs/ and click the link under "[What is the CCS and What Are Its Rules and Expectations](https://ccs.getmonero.org/what-is-ccs)", you get getmonero.org on port 8080 like this:

```
https://ccs.getmonero.org:8080/what-is-ccs/
```
![image](https://user-images.githubusercontent.com/32943174/183833837-9c766da4-fbf3-427e-9267-8ced15f74f0c.png)

**Comment by ProkhorZ** [comment]
The CCS is in a separate repository on Gitlab. [This error was reported and dismissed there](https://repo.getmonero.org/monero-project/ccs-front/-/issues/2). I think there's a slash missing at the end of the link. Might have been dismissed because it does work in the local preview there.

**Comment by plowsof** [comment]
Thanks for raising the issue, had a quick look, it is indeed a missing slash at the end. A PR must be made to the CCS-front end repository on gitlab (not here)

https://repo.getmonero.org/monero-project/ccs-front/-/tree/master/how-to-ccs (easy fix but, my account isn't able to fork the repo)

**Comment by erciccione** [comment]
Closing this issue as it's unrelated to this repository. Please use the merge request on gitlab for further discussion.
