### ISSUE TITLE
ring_size listed as input to wallet RPC transfer method

### ISSUE THREAD

**Issue by dimalinux** [monero-project/monero-site#2021]
I thought the `ring_size` in Monero can no longer be changed.  Does it still belong as an input to `transfer` in the RPC documentation?
https://github.com/monero-project/monero-site/blame/28cfcdb38e735f5c35b83c067d8410ff4dc81ad4/resources/developer-guides/wallet-rpc.md#L659

**Comment by plowsof** [comment]
On mainnet yes, but devs are still able to perform tests on older versions of the blockchain. so perhaps just a few words to clarify this e.g. "Not adjustable on mainnet" or something to that effect

**Comment by dimalinux** [comment]
Instead of "not adjustable on mainnet", I think the phrase "the field is completely ignored on mainnet" would be more helpful. Seeing that description, client developers of libraries not intended for testing older versions will just omit the field entirely. Developers won't waste time trying to figure out if they need to set it to exactly 16 or if setting it to an arbitrary number like 13 will generate an error.

**Comment by plowsof** [comment]
moneromoo - "It is not ignored if sending pre rct outputs."

**Comment by dimalinux** [comment]
@plowsof Did moneromoo give any advice on how the `ring_size` field should set for the standard use case of transferring Monero on the current mainnet? The `transfer` method only takes an `amount`.  You don't specify or easily know which outputs get used and if they are pre rct or not. I've just been leaving it unset or with a value of zero and it seems to be working.

**Comment by plowsof** [comment]
I will ask, i share the same feelings, for now i'm using "(Unless dealing with pre rct outputs, this field is ignored on mainnet)."
