### ISSUE TITLE
Clarify why Monero is still on GitHub adn the contingency measures planned

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#2028]
This question gets asked all the time, especially after a big project is banned from github.

**Comment by nahuhh** [comment]
There is a reasonable ccs (1.5xmr) open:
https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/339

Auto backed up every 8hrs

Live here:
http://rjk5vwl4wxqozunx6rpaat7rwxkbtlcknkhyq5tuzmy7rc22rbxl4wyd.onion/monero_archive/

Perhaps we could host a few?

**Comment by erciccione** [comment]
That's unrelated to this issue, as the point is to list contingencies already in place and managed by the current maintaienrs of the project (core team).
