### ISSUE TITLE
MyMonero should be removed from Downloads until compatible with Fluorine Fermi network upgrade

### ISSUE THREAD

**Issue by Rucknium** [monero-project/monero-site#2029]
Many users are looking for a new wallet after their current wallet software, e.g. Exodus, did not update in time for the Fluorine Fermi hard fork. GetMonero.org should not point users to another wallet that is also currently not working.

Once MyMonero is confirmed to be working with the hard fork, it can be added to Downloads again.

**Comment by nahuhh** [comment]
Edge relies on Mymonero's update and has confirmed that
"The XMR update for edge is still inprogress, however the all other coins on Edge are still working"

Either full removal or a section / indication that these apps are non-functional

**Comment by Cactii1** [comment]
> Once MyMonero is confirmed to be working with the hard fork, it can be added to Downloads again.

I don't think this should happen immediately or automatically. We have a responsibility to other users to not recommend unreliable service providers and MyMonero should have to rebuild community trust before it's added back.

**Comment by AslanPonies** [comment]
Official update from MyMonero here: https://github.com/mymonero/mymonero-app-js/issues/513

**Comment by LivBoss** [comment]
Please find MyMonero’s official response here:

https://www.reddit.com/r/MyMonero/comments/wxbdb9/mymonero_important_announcement/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by LivBoss** [comment]
See MyMonero's latest update here:
https://github.com/mymonero/mymonero-app-js/issues/513#issuecomment-1227235460

**Comment by erciccione** [comment]
I do appreciate that mymonero is speeding up things to fix the problem, but the issue here is that we are still pointing people to a wallet outside of Monero's network. Thousands of people visit the website every day. IMO #2030 should be merged and deployed immediately. We can re-add MyMonero easily as soon as they will be ready.

**Comment by AslanPonies** [comment]
(https://github.com/monero-project/monero-site/pull/2030#issuecomment-1227311250)

**Comment by LivBoss** [comment]
See MyMonero's latest official update here:

https://github.com/mymonero/mymonero-app-js/issues/513#issuecomment-1228276635
