### ISSUE TITLE
moneroaddress.org link broken under tools section

### ISSUE THREAD

**Issue by Snatchess** [monero-project/monero-site#2037]
Suggest remove the link for moneroaddress.org under "address generator" section under resources > tools.

**Comment by GraoMelo** [comment]
evidences: 

![moneroaddress_discontinued](https://user-images.githubusercontent.com/60477737/188676633-1fe1fdc3-1b3b-4927-a233-b15deed29b71.png)

last checked on archive dot org 09 June 2022

![fixedXMRAddrss](https://user-images.githubusercontent.com/60477737/188676754-56d27467-72e6-47a0-b3a4-5c526a9f889c.png)



please verify this @luigi1111 it's important. 

domain information: 

''
Domain Name: moneroaddress.org
Registry Domain ID: a14bde6116444120b3c0b95b0b128ac4-LROR
Registrar WHOIS Server: whois.tucows.com
Registrar URL: http://www.tucows.com
Updated Date: **2022-09-03T04:25:38Z**
Creation Date: 2014-07-24T18:32:20Z
Registry Expiry Date: 2023-07-24T18:32:20Z
Registrar: Tucows Domains Inc.
Registrar IANA ID: 69
Registrar Abuse Contact Email: domainabuse@tucows.com
Registrar Abuse Contact Phone: +1.4165350123

**Comment by HardenedSteel** [comment]
should we completely remove or find alternative for moneropedia page?
