### ISSUE TITLE
forgot my Monero wallet key words and password 

### ISSUE THREAD

**Issue by mkalmutairi** [monero-project/monero-site#2046]
hi all

I have created my monero wallet in 2017 and I was mining so after that I stopped mining for years then I just remembered that I have wallet and then I tried to open it but its ask me for key words and the password that I forgot it what should I do now ???

I need help please 

best regards

**Comment by HardenedSteel** [comment]
Nobody can help you sorry, you have to remember your wallet password or seeds or private keys. Trying to find your wallet password would be easiest one

Also this repo is for getmonero.org, you can ask your questions at [stackexchange](https://monero.stackexchange.com/), [reddit](https://reddit.com/r/MoneroSupport) or [IRC/Matrix channels](https://www.getmonero.org/community/hangouts/)
