### ISSUE TITLE
devguides: stop_wallet description needs clarification

### ISSUE THREAD

**Issue by dimalinux** [monero-project/monero-site#2093]
In the monero [wallet RPC documentation](https://github.com/monero-project/monero-site/blame/0d05edf78e2e1b41d36c905f967168b2d98d6561/resources/developer-guides/wallet-rpc.md#L1336-L1338):

The description of `close_wallet` is:
> Close the currently opened wallet, after trying to save it.

The description of  `stop_wallet` is:
> Stops the wallet, storing the current state.

Since the user can open and close different wallets on a single `monero-wallet-rpc` instance (and may not even have an open wallet on a running instance), they don't understand the difference between these two methods. I would change the wording of `stop_wallet` to:
> Store the current state of any open wallet and exit the `monero-wallet-rpc` process.

**Comment by plowsof** [comment]
Thank you ( i've ctrl+f'd for exit many times .. i end up using the pid file to stop it )
