### ISSUE TITLE
devguides: wallet-rpc query_key should list "spend_key" as a key_type value

### ISSUE THREAD

**Issue by dimalinux** [monero-project/monero-site#2103]
Right now the `query_key` wallet RPC method only mentions `mnemonic` and `view_key` as valid inputs:
https://github.com/monero-project/monero-site/blame/ac1602403936f18bfe08ad757ad428f418d55c5e/resources/developer-guides/wallet-rpc.md#L1240

Thankfully, the undocumented `spend_key` value worked when I tried it. I see it in the tests as well: https://github.com/monero-project/monero/blob/da9aa1f/tests/functional_tests/wallet.py#L108-L109

**Comment by plowsof** [comment]
thanks, will do. (updating docs are paused now until the 'big one' is merged)
