### ISSUE TITLE
Linux distribution from getmonero.org is a tarbomb

### ISSUE THREAD

**Issue by aluminiumgeek** [monero-project/monero-site#212]
Why do you guys distribute it as a tarbomb (http://www.linfo.org/tarbomb.html)? Is where a particular reason why you do that?
A tarball exploding into an existing directory can be a major annoyance, or even dangerous. That is, it can result in the overwriting of any files and directories that have the same names and which reside in the same directory.

**Comment by KristijanZic** [comment]
It would be a good idea to distribute it as a snap package. See http://snapcraft.io/ .
I've already proposed this on telegram/irc but here it is again.

**Comment by anonimal** [comment]
@aluminiumgeek I don't like tarbombs either but tar's aren't designed to read minds. `-C` should always be used if there is concern. For this issue, I think the binaries should be put into a folder named after the tarfile: something like `monero.linux.x64.v0-10-1-0`
@KristijanZic https://github.com/monero-project/monero/issues/1532

**Comment by anonimal** [comment]
This issue has been resolved as proven in latest point release https://getmonero.org/downloads/.  @aluminiumgeek can you please close this issue?
