### ISSUE TITLE
Please add a new site to the MONERO MERCHANTS AND SERVICES DIRECTORY 

### ISSUE THREAD

**Issue by JoelStrawnCode** [monero-project/monero-site#214]
Please add https://mychain.store to the MONERO MERCHANTS AND SERVICES DIRECTORY under the Goods section.

Products can be paid for directly using Monero.  Fiat currencies are not accepted.

**Comment by rehrar** [comment]
@JoelStrawnCode seeing as how this has been added, can we close this issue? Thanks.
