### ISSUE TITLE
what-is-monero: change "anonymity" to "privacy"

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-site#2160]
midipoet requested. also suggested "Monero, on the other hand, uses various enhanced technologies to ensure the privacy of its users". 

https://github.com/monero-project/monero-site/blob/c3c21f92cc62c7cdba5133cc8854e64a4c97a4bc/_i18n/en.yml#L587 

i assume the one word change would have to delete every translation for the entire thing? :(

**Comment by erciccione** [comment]
I'd agree with this change.

> i assume the one word change would have to delete every translation for the entire thing? :(

Translators will be asked to retranslate the string, but the old translation will be displayed until a new one is provided.

**Comment by erciccione** [comment]
#2166
