### ISSUE TITLE
`monerooutreach.org` (as used in https://www.getmonero.org/get-started/faq/#vulnerabilities) is no longer owned and is parked.

### ISSUE THREAD

**Issue by recanman** [monero-project/monero-site#2185]
When going [here](https://www.getmonero.org/get-started/faq/#vulnerabilities), there is the option to go to `monerooutreach.org`. When visiting the website (over HTTP, HTTPS seems to kill the TLS handshake), there are three scripts referenced, and they all have **parking-lander** in them (e.g `<script src="https://img1.wsimg.com/parking-lander/static/js/0.d34b8e6e.chunk.js"></script>`).
I assume that the domain is no longer in ownership and is now parked.

I am not sure who operates the domain, but someone should get in contact with them.

**Comment by erciccione** [comment]
The outreach workgroup seem to be dead. I opened https://github.com/monero-project/monero-site/pull/2154 to remove it.
