### ISSUE TITLE
Appearance issue with Safari

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#22]
Safari, left sidebar opened

![Safari, left sidebar opened](https://cloud.githubusercontent.com/assets/4220418/6692150/3e574128-cccb-11e4-9888-e1314e88fd4f.png)

**Comment by fluffypony** [comment]
If the menu state is collapsed then the menu doesn't automagically show - you must have changed the menu state and then gone back to full width before collapsing the width again. Just click on the menu button at the top right to collapse it again.

**Comment by davidlatapie** [comment]
This was a user during an IRL meetup. I sent him the link, he'll tell me if this happens again.
