### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by fheroes2bugs** [monero-project/monero-site#2204]
The roadmap looks outdated...
![image](https://github.com/monero-project/monero-site/assets/145407420/a00fdbe2-fdf4-4455-bb43-79b1167f74fc)

Last years monero roadmap had a future plans by years, now it is only "future".

It would be better to add something to 2024 and 2025.

**Comment by erciccione** [comment]
> Last years monero roadmap had a future plans by years, now it is only "future".

Not really. We have been showing "future" for a very long time. That's on purpose, because we cannot plan when some roadmap items will be completed. We only no it will be done in the future.

The roadmap still needs to be updated tho. I'll take care of it.

**Comment by kayn1k** [comment]
> > Last years monero roadmap had a future plans by years, now it is only "future".
> 
> Not really. We have been showing "future" for a very long time. That's on purpose, because we cannot plan when some roadmap items will be completed. We only no it will be done in the future.
> 
> The roadmap still needs to be updated tho. I'll take care of it.

Anything is better than having nothing on 2023 and 2024 so on. We need to show there is an active development team still perfecting the only "people's currency" in the world. 

Deadlines generate hype and hype generates free advertisement.
