### ISSUE TITLE
adding new explanatory videos

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-site#2206]
Animated video on the subject of Tail emission:
https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/387#note_22477

the same team have an open CCS idea to create 2 videos on RandomX/Nodes
https://repo.getmonero.org/monero-project/ccs-proposals/-/merge_requests/412

would the tail emission / future videos fit nicely here: https://www.getmonero.org/get-started/faq/#videos ?

**Comment by erciccione** [comment]
We can put the tail emission video in the videos faq and related moneropedia article. We can see what to do with the other videos when/if they will be created.

**Comment by plowsof** [comment]
nice, will add to #2244 after feedback

**Comment by plowsof** [comment]
thanks for the reminder, we can close this with #2311 

note erc comment:
>and related moneropedia article(s)

i will look into this now^
