### ISSUE TITLE
sponsorships: Fork Networking info request

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-site#2209]
> "Fork Networking provides a server which is used for development."

I and some others are unsure of FN's role and would like this to be the point of discussion around that. 

- How many server(s) does FN provide and what are the software/hardware/bandwidth specs?
- Do they provide maintenance (or other valuable services) for the server(s)?
- Who has access to the server(s)?
- Are they actively used for development? If yes, what kinds of development take place there?
- How would one obtain access to perform these development tasks?

feel free to answer some/all of the questions or add your own, thank you.

**Comment by nahuhh** [comment]
@binaryFate

**Comment by plowsof** [comment]
resolved by emailing them directly. #2298
