### ISSUE TITLE
New merchant to list on MONERO MERCHANTS AND SERVICES DIRECTORY

### ISSUE THREAD

**Issue by CameronRuggles** [monero-project/monero-site#221]
https://www.vesp.co/Fungible

I'd like to be listed under goods on this page: https://getmonero.org/getting-started/merchants

I sell mushroom cultures, mushroom growing supplies and related items such as seeds.

**Comment by serhack** [comment]
This issue should be closed.

**Comment by rehrar** [comment]
@CameronRuggles can we close this issue? The store is up there. Thanks.
