### ISSUE TITLE
Monero CLI Node rpc Wallet

### ISSUE THREAD

**Issue by landvogt76** [monero-project/monero-site#2211]
Hello, I have a monero node running ubuntu on a separate computer. I would also like to connect a second computer to the node via rpc, how is this done under cli? Greetings Michael

**Comment by plowsof** [comment]
hi, if you are still having issues, please try to reach out on other channels such as Matrix/IRC (https://www.getmonero.org/community/hangouts/) for support as the issues here are for a different purpose, thank you. Please close
