### ISSUE TITLE
Trezor Safe 3 also supports Monero

### ISSUE THREAD

**Issue by inson1** [monero-project/monero-site#2239]
It should be added to https://www.getmonero.org/downloads/#hardware

https://trezor.io/coins/detail/monero

**Comment by plowsof** [comment]
there is an open PR #2213 , checking comments, its time to merge (pending an description edit), ill make a new one as the author is awol

**Comment by inson1** [comment]
@plowsof Are you sure about the minimal firmware?

**Comment by plowsof** [comment]
definitely not @inson1 , for now it would be the version that got shipped with safe3 , will try to find out
