### ISSUE TITLE
Daemon-rpc doc: Add correct output description for /sendrawtransaction

### ISSUE THREAD

**Issue by cryptoshrimpi** [monero-project/monero-site#224]
URL: https://getmonero.org/knowledge-base/developer-guides/daemon-rpc#sendrawtransaction

The output of ```/sendrawtransaction``` is described as:

> Outputs:
> - status - string; General RPC error code. "OK" means everything looks good.
> 

In Monero v0.10.1.0 the actual output for an invalid ```tx_as_hex``` input value such as ```'abc'``` is

```
{ double_spend: false,
  fee_too_low: false,
  invalid_input: false,
  invalid_output: false,
  low_mixin: false,
  not_rct: false,
  not_relayed: false,
  overspend: false,
  reason: '',
  status: 'Failed',
  too_big: false }
```
This leads to the following type pattern:

    double_spend: boolean;
    fee_too_low: boolean;
    invalid_input: boolean;
    invalid_output: boolean;
    low_mixin: boolean;
    not_rct: boolean;
    not_relayed: boolean;
    overspend: boolean;
    reason: string;
    status: string;
    too_big: boolean;

**Comment by QuickBASIC** [comment]
@cryptoshrimpi Do you feel comfortable editing the [daemon-rpc.md](https://github.com/monero-project/monero-site/blob/master/resources/developer-guides/daemon-rpc.md) and adding the correct information? (Make sure you add `closes #224` in the commit description.) 

Or could someone more familiar with daemon rpc update the doc so we can close this issue, please? (I'd do it but I don't know enough about it to know what I'm adding.)

**Comment by QuickBASIC** [comment]
+guide

**Comment by cryptoshrimpi** [comment]
I'll try to add the correct information to the doc when I find time the next days. Can someone confirm that all of the mentioned attributes are not optional in the result set? I was only able to submit an invalid tx so far.

**Comment by cryptoshrimpi** [comment]
I also noticed that the method can return the status "OK" even if the transaction was not relayed. One would expect that it returns "OK" only if everything went fine. Especially when the methods name is "**send**rawtransaction".
