### ISSUE TITLE
Mismatching/outdated links for cakewallet on downloads page

### ISSUE THREAD

**Issue by rfxDarth** [monero-project/monero-site#2242]
In full desktop version, cakewallet link points to https://cakewallet.com/, but if you shrink the browser window until Mobile/Desktop/Source Code links disappear, the new link now points to https://cakewallet.io/ which seems to be abandoned.

**Comment by plowsof** [comment]
Fixed in #2210 soon(tm)

**Comment by plowsof** [comment]
closed by #2210
