### ISSUE TITLE
Some swappers not providing monero anymore

### ISSUE THREAD

**Issue by MajesticBank** [monero-project/monero-site#2247]
Some of the swap sites, 2 out of the 5 listed to be precise are not able to provide monero swaps

Doesn't work: 

https://godex.io/ - Probably used only one exchange which removed Monero
https://fixedfloat.com/ - For other technical reasons but also most likely using that same exchange only

Works:

According to their website they have access to at least 2 or more exchanges that have support for Monero for now

https://changenow.io/
https://simpleswap.io/ 
https://stealthex.io/

**Comment by plowsof** [comment]
Thanks. Does @MajesticBank have access to the same/less/more xmr after the binance delisting?

**Comment by MajesticBank** [comment]
I can speak about the volume itself, which goes up to x3 from the same period of last year.

MajesticBank was never dependent  on centralized exchanges liquidity in first place,

Hopefully with spot market and two more integrations with monero-only wallets we are closing the question of liquidity

**Comment by nahuhh** [comment]
Fixedfloat was due to repeated hacks afaik

**Comment by plowsof** [comment]
we have removed fixed float, but godex not, oops
