### ISSUE TITLE
Please add a new site to the MONERO MERCHANTS AND SERVICES DIRECTORY 

### ISSUE THREAD

**Issue by kaiserex** [monero-project/monero-site#225]
Please add https://www.kaiserex,com to the MONERO MERCHANTS AND SERVICES DIRECTORY under the Exchanges section.

We provide XMR exchange services and help our clients invest in Monero.

**Comment by serhack** [comment]
This should be closed.

**Comment by rehrar** [comment]
@kaiserex can we close this issue? The exchange has been added.
