### ISSUE TITLE
Query to monero-site admin

### ISSUE THREAD

**Issue by vpts1202** [monero-project/monero-site#2279]
Hello

In website section https://www.getmonero.org/downloads/#cli, is description of feature **Pay-for-RPC**
As per Monero Dev. Team info,support for this feature dropped more than a year ago:
https://github.com/monero-project/monero/issues/9248
So info on webpage https://www.getmonero.org/downloads/#cli, regarding Pay-for-RPC feature is deprecated and just not deleted on time, or there is other reward model under this feature?

Thanks.

**Comment by nahuhh** [comment]
Please change title
