### ISSUE TITLE
Please add a new site to the MONERO MERCHANTS AND SERVICES DIRECTORY

### ISSUE THREAD

**Issue by algoStrategic** [monero-project/monero-site#228]
Please add algoStrategic.com to the MONERO MERCHANTS AND SERVICES DIRECTORY under the Services section.

algoStrategic - Internet Marketing and Web Development

**Comment by serhack** [comment]
Can you post the link thanks?

**Comment by algoStrategic** [comment]
https://algostrategic.com/
