### ISSUE TITLE
Status page

### ISSUE THREAD

**Issue by jermanuts** [monero-project/monero-site#2283]
It would be great if Monero had a status page for all Monero related services, so users can keep track of incident reports/downtimes.

**Comment by plowsof** [comment]
status page sounds like it would need to be updated dynamically on the fly. please see commit history/frequency of site deployments as to why this is not feasible.

**Comment by jermanuts** [comment]
Yes, also Mainnet, Testnet and Stagenet. But might not be feasible rn tho which hopefully not going to be forever.

**Comment by nahuhh** [comment]
> Yes, also Mainnet, Testnet and Stagenet. But might not be feasible rn tho which hopefully not going to be forever.

Lol.

**Comment by HardenedSteel** [comment]
this how Monero not works, nodes ran by the community not the site maintainers. if you're looking for status of nodes you can use https://monero.fail or https://nodes.monero.com

**Comment by plowsof** [comment]
not planned and adds more maintenance overhead
