### ISSUE TITLE
posts: issue with "About supply auditability" 

### ISSUE THREAD

**Issue by plowsof** [monero-project/monero-site#2339]
https://www.getmonero.org/2020/01/17/auditability.html

Issue taken with "then you need a transparent asset." making it seem that [there are no complex maths](https://libera.monerologs.net/monero-site/20240808#c408259) involved in transparent chains. 

linking moneroinflation.com was also [suggested](https://libera.monerologs.net/monero-site/20240808#c408287) if any edits/additions are to be made

**Comment by HardenedSteel** [comment]
If the website is still maintained its okay for me.
