### ISSUE TITLE
Update join Monero core team Matrix server guide; screenshots outdated

### ISSUE THREAD

**Issue by rottenwheel** [monero-project/monero-site#2361]
Guide refers to 'matrix.monero.social' as the Synapse server to reference when signing up on the Matrix client of choice, when it should be raw 'monero.social' as everyone's handles and log-in credentials indicate.

It is necessary to update text and screenshots showing how to modify the hosting synapse server in order for user to sign up on Monero's Matrix server. One screenshot from desktop/web, another from Android and another from iOS showing 'monero.social' as server are needed.

Apparently it requires an e-mail for sign-up now too, it didn't before. Text to be updated accordingly as well.

**Comment by HardenedSteel** [comment]
working on it

**Comment by SamsungGalaxyPlayer** [comment]
Thanks @HardenedSteel; apologies @rottenwheel for not having the time to get to this.
