### ISSUE TITLE
CEX Listing: bit2me.com 

### ISSUE THREAD

**Issue by HardenedSteel** [monero-project/monero-site#2395]
An exchange that supports some EU countries.

It has 1.1% fee if trading volume <€2k* (while Kraken had 0.65%** and Haveno Reto has 0.6%)

\* https://support.bit2me.com/en/support/solutions/articles/35000172197-what-are-the-fees-for-the-bit2me-pro-service-
\** https://www.kraken.com/features/fee-schedule

**Comment by danielsippel** [comment]
I tried bit2me. Actually it looks like you can buy Monero with EUR, but they do not allow to transfer it to your wallet on the blockchain. WTF

<img width="529" alt="Bildschirmfoto 2024-10-17 um 09 01 39" src="https://github.com/user-attachments/assets/77e26b09-cb87-43c0-bd58-6d0acf451de7">

**Comment by danielsippel** [comment]
<img width="959" alt="Bildschirmfoto 2024-10-17 um 10 57 22" src="https://github.com/user-attachments/assets/f4fcd719-b7f7-480f-a383-8161ed37b6ba">

**Comment by HardenedSteel** [comment]
that's called scamming. thanks for the feedback

**Comment by nahuhh** [comment]
> I tried bit2me. Actually it looks like you can buy Monero with EUR (Visa via GPay), but they do not allow to transfer it to your XMR wallet on the blockchain. WTF
> 
> <img width="529" alt="Bildschirmfoto 2024-10-17 um 09 01 39" src="https://github.com/user-attachments/assets/77e26b09-cb87-43c0-bd58-6d0acf451de7">
> 
> 
> Looks like this is not possible at all:
> https://de.trustpilot.com/reviews/65fc5e0271a27cc62c03fa70
> 
> Not cool.

Did you try it as a result of this github issue? Or on your own?

**Comment by danielsippel** [comment]
Bc of the issue. 

Was researching why you guys still list Kraken after they stopped XMR. 

Ended up buying XMR on changenow.io today (VISA direct). Worked perfect without acc, without KYC.. but was quite expensive at a, I guess, bad rate (~180).

**Comment by nahuhh** [comment]
Were you able to get a refund?

**Comment by jeffro256** [comment]
> Was originally researching why you guys still list Kraken after they stopped XMR.

Kraken stopped XMR trades in the EU, but they still operate in the US

**Comment by nahuhh** [comment]
> > Was originally researching why you guys still list Kraken after they stopped XMR.
> 
> Kraken stopped XMR trades in the EU, but they still operate in the US

And Europe, just not the EEA
