### ISSUE TITLE
At http://dr.mindsci.com/ to the merchants and services directory

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#24]
I met Pradeep Atluri in person last Thursday in Paris ([reddit](http://www.reddit.com/r/Monero/comments/2dum4r/i_am_a_new_york_city_psychiatrist_who_accepts/))

**Comment by fluffypony** [comment]
done

**Comment by davidlatapie** [comment]
[Can't find him](http://getmonero.org/getting-started/merchants).

**Comment by fluffypony** [comment]
https://github.com/monero-project/monero-site/commit/043722447022b736c6f7096b582d7083553beff2
