### ISSUE TITLE
Getmonero.org Redesign

### ISSUE THREAD

**Issue by rehrar** [monero-project/monero-site#245]
There's an issue. It's a decently large issue. The issue is, that the current website isn't designed well, and the content is thrown wheverever it will fit without any thought put into how it can be the most easily accessible.

I have made two sets of redesign options, which can be viewed on the following albums: 

Redesign proposal 1 (drafts 1-3): http://imgur.com/a/MwyxX
Redesign proposal 2 (drafts 1-2): http://imgur.com/a/H9i3z

I think it's important we restructure the site and give it a makeover of some sort. A proposal has been made on the FFS which can be viewed here: https://forum.getmonero.org/6/ideas/87558/getmonero-com-redesign

I'm available to contact with any questions.

**Comment by anonimal** [comment]
@rehrar this should be posted in https://github.com/monero-project/meta

**Comment by anonimal** [comment]
@rehar scratch my last post (I didn't see that this was `monero-site`).

My two cents: I like the direction of design prop 1.

**Comment by rehrar** [comment]
Dude, I was just getting ready to delete and move it. :D 

Thanks for your comments!

**Comment by jonathancross** [comment]
Nice work!
I prefer number 2, feels cleaner, and will load faster without the huge splash image.
Also not into the large icons used in number 1 (Secure, Private Untraceable) as they just seem to fill up space without adding value.

I can probably help code this up if / when we choose a direction.

**Comment by anonimal** [comment]
I like the simplicity of No. 2 but, to me, it looks more like the front page of a technical paper. No. 1 appears more inviting to the general population as it has all the usual eye candy in the right places. How about a mix of the best of both designs?

**Comment by rehrar** [comment]
I think the structuring of the second design is much better and modular, and will more easily allow others to add pages should they want to later. 

That said, it does seem a bit sanitized, so we're going to play around with some color and let you guys know the results.

**Comment by anonimal** [comment]
The best part: anyone will eventually be able to PR any changes they want 😄

**Comment by rehrar** [comment]
I plan to also create an "assets" page that will have the mark-up for all of the types of blocks that can just be copy and pasted into the type of page that someone wants. So they will easily be able to make pages that fit with the website and add helpful content. 

Good idea?

**Comment by anonimal** [comment]
>Good idea?

That sounds like a good start to me, but I'm not an avid website developer.
