### ISSUE TITLE
Moneropedia links are not indicated as such.

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero-site#247]
Internal links in the moneropedia are styled exactly like the text so there is no indication that they are clickable.  Example: https://getmonero.org/knowledge-base/moneropedia/block

The CSS class below forces them to grey:
```css
.moneropedia {
  color: #505050;
}
```

If this color property is simply removed, we get nice links again:

![moneropedia-links](https://cloud.githubusercontent.com/assets/5115470/24769006/24d5986e-1b05-11e7-9cfb-fa69e6113728.png)

**Comment by anonimal** [comment]
Why not PR the change?

**Comment by jonathancross** [comment]
I'd love to, but have not found the CSS.

This message in the README suggests it is not possible:
> since all static content (CSS/JS/images) is hosted in a separate, non-public repository, changes can be suggested via Github issues and we will cross-apply them to that repo, crediting you in the commit message

**Comment by fluffypony** [comment]
@jonathancross that's changed, someone should update the README. CSS is in the monero-forum repo.

**Comment by jonathancross** [comment]
@fluffypony Found it, thanks!
Will send over some PRs to update the README and fix this issue.
