### ISSUE TITLE
Monero Missives podcasts deleted?

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero-site#249]
It seems that all podcasts have been deleted, eg:
* http://traffic.libsyn.com/monero/Monero_Missives_Podcast_for_the_week_of_2016-06-20.mp3
* http://traffic.libsyn.com/monero/Monero_Missives_Podcast_for_the_week_of_2015-12-26.mp3
* http://traffic.libsyn.com/monero/Monero_Missives_Podcast_for_the_week_of_2015-09-14.mp3
* Etc...

I got the links off of the monero site.
Can these be restored, or are there backups somewhere?

**Comment by serhack** [comment]
Hello @jonathancross 
I was looking for these files, but I never found them :(

**Comment by jonathancross** [comment]
I have no idea who was in charge of these, but they can [file a support ticket here](https://playerfm.freshdesk.com/support/tickets/new) if the takedown was not intentional.  If it **_was intentional_**, then the links should be removed from the website.

**Comment by QuickBASIC** [comment]
@jonathancross I think you're mistaken. I don't believe they were hosted there, but instead were syndicated at last.fm. 

> Hi Mike.
> 
> I am sorry that the links to the episodes you specified are dead.
> 
> I tried opening them on my end and I got the following message:
> 
> "Error: 404 Not Found
> There was a problem processing your request!
> Details:
> 
> Attempting to load:
> http://traffic.libsyn.com/monero/Monero_Missives_Podcast_for_the_week_of_2016-06-20.mp3
> Previous URL:
> No Previous URL"
> 
> What I can suggest you to do is to reupload your podcast on a podcast hosting service, get an RSS feed and send it to us, if you want them displayed on our end.
> 
> I hope that this answers your question.
> 
> Cheers,
> Viktor
> Player FM

I think our best bet is going to be to get them from the original creator of the podcast or someone that downloaded them to listen to them and still have them somewhere.

www.libsyn.com costs $5/mo, so my assumption is that someone didn't pay the rent on the hosting. I don't know how the community is hosting large binary files, but if we don't already have hosting I'm assuming we could do a FFS to fund hosting if we find them.

**Comment by QuickBASIC** [comment]
The other day on IRC @fluffypony said he had them and will figure out how to rehost them.

**Comment by QuickBASIC** [comment]
+in progress
+blog

**Comment by erciccione** [comment]
Any update on this issue? @fluffypony ?

**Comment by fluffypony** [comment]
@erciccione sorry missed the earlier ping. I can rehost them on downloads.getmonero.org - thoughts on that? I'm also thinking of putting the whole downloads directory up on git so there's a mirror.

**Comment by erciccione** [comment]
> I can rehost them on downloads.getmonero.org - thoughts on that?

Since i don't think it's necessary to create a dedicated section on getmonero for the podcasts, that sounds like the best option for me. The only conflict i see is that media.getmonero cease to have a reason to exist at this point (it's not active at the moment tho), epecially if we decide to move the videos in the 'Download' repo as well (referring to [#393 (comment)](https://github.com/monero-project/monero-site/issues/393#issuecomment-399901130))

> I'm also thinking of putting the whole downloads directory up on git so there's a mirror.

+1. I think this would be also beneficial for mirror websites (see [this reddit post](https://www.reddit.com/r/Monero/comments/8tio53/monero_really_needs_a_mirror_eepsite_like_right/)) who will be able to just link to the downloads directory, so that users will feel more confortable downloading from a repo maintained by the core team and not some random.

**Comment by fluffypony** [comment]
@erciccione we can just CNAME media.getmonero to downloads.getmonero if we need to retain some links

**Comment by erciccione** [comment]
Then i don't see any other problem with that. yep, opening an issue right now @fluffypony

**Comment by erciccione** [comment]
@fluffypony #780

**Comment by erciccione** [comment]
This was tracked and then closed on gitlab.
