### ISSUE TITLE
Please add InvestmentArt.org under goods and services

### ISSUE THREAD

**Issue by gideonlouw** [monero-project/monero-site#258]
Hello,

Will you please add InvestmentArt.org as a provider of goods - 

InvestmentArt.org is now accepting Monero as payment currency!

**Comment by erciccione** [comment]
Hello @gideonlouw , the link has been added to the website, please close this Issue

**Comment by rehrar** [comment]
@gideonlouw hey man, just reiterating that this has been added. Can we get this issue closed? Thanks.

**Comment by gideonlouw** [comment]
Thank you.
