### ISSUE TITLE
Please add Nutritional Therapy Services to Good and Services

### ISSUE THREAD

**Issue by ealderson** [monero-project/monero-site#259]
Private Nutritional Therapy Practice accepting Monero for Distance Online Consultations, Laboratory Fees, DNA Analysis, Food Sensitivities Testing, and Nutrition Supplements . Website ( www.elisehawkinsnutritionaltherapy.com ) 
![logo-green-and-purple](https://cloud.githubusercontent.com/assets/28361363/25676427/d4808f3e-2ff6-11e7-8d23-3e55a60a68cd.png)

**Comment by rehrar** [comment]
@ealderson hey, your store has been added. Can we close this issue? Thank you.

**Comment by ealderson** [comment]
Perfect! Yes, thank you! 

Elise Hawkins
Nutritional Therapy Practitioner
elisehawkinsnutritionaltherapy.com 



Please excuse typos--this message was sent from my iPhone

**Comment by ealderson** [comment]
Actually, I just saw my business was placed under goods, when it is primarily a consulting service. Is there any way that can be adjusted under services instead? 

Thank you! 

Elise Hawkins
Nutritional Therapy Practitioner
elisehawkinsnutritionaltherapy.com 



Please excuse typos--this message was sent from my iPhone

**Comment by ealderson** [comment]
Also, the link to my business is not working. Can you make sure it's the correct address? See below: www.elisehawkinsnutritionaltherapy.com


Elise Hawkins
Nutritional Therapy Practitioner
www.elisehawkinsnutritionaltherapy.com 





Please excuse typos--this message was sent from my iPhone

**Comment by ealderson** [comment]
The link is still not working, fyi

**Comment by QuickBASIC** [comment]
![Seems to be working fine.](https://user-images.githubusercontent.com/7226914/30092802-16a97be6-928f-11e7-9514-2c40d0b618fa.png)

**Comment by QuickBASIC** [comment]
Forgive me, I misunderstood your comment initially.The update to the link for your business had been made, but it had not yet been messaged with the currently hosted site. Many contributers request changes and then they are merged by the maintainer... That hasn't happened yet. You can check the PR #374 for any updates, but it usually won't get merged in less than a week. Once again, sorry about the we adding it the first time.
