### ISSUE TITLE
Nerdzy Lawn Care Accepts Monero

### ISSUE THREAD

**Issue by Nerdzy** [monero-project/monero-site#264]
Please add Nerdzy Lawn Care, based in Charlotte, North Carolina, to the list of merchants which accept Monero XMR. Our lawn care page may be accesses at [Nerdzy.net](http://www.nerdzy.net/index.php/lawn-care/) Please note our online sales do not take Monero as a form of payment, our lawn care branch will, however, accept Monero onsite as a form of payment. For more info, please email our sales team at Nerdzy.sales@gmail.com Thanks!

**Comment by tokjingga** [comment]
maybe you want to remove bitmonero to avoid confusion

**Comment by erciccione** [comment]
Hello @Nerdzy  , the link has been added to the website, please close this Issue

**Comment by Nerdzy** [comment]
@erciccione Thank you for adding us to your page, however, after our team reviewed the page we realized the link was actually broken and would prevent anyone from accessing our website- we believe the link simply lacked a  colon in the http:// area. Thanks again for your help!

**Comment by anonimal** [comment]
https://github.com/monero-project/monero-site/pull/277/files#r123584326

**Comment by erciccione** [comment]
yes, my mistake. Just opened a PR to fix it
 https://github.com/monero-project/monero-site/pull/284

**Comment by rehrar** [comment]
@Nerdzy @erciccione  can we close this issue? was everything fixed ok?

**Comment by erciccione** [comment]
@rehrar yes, fixed and merged
