### ISSUE TITLE
New Merchant: cloakVPN.com

### ISSUE THREAD

**Issue by pwrcycle** [monero-project/monero-site#268]
Please add cloakVPN.com to the Monero Merchants and Services Directory
Users are automatically provisioned based on the Payment_ID sent in the Monero transaction.

[http://cloakVPN.com/monero](http://cloakVPN.com/monero)

Twitter announcement
[https://twitter.com/cloakVPN/status/861638668909334528](https://twitter.com/cloakVPN/status/861638668909334528)
Reddit announcement
[https://www.reddit.com/r/Monero/comments/6cpfd2/cloakvpncom_now_accepts_monero_using_payment_id/](https://www.reddit.com/r/Monero/comments/6cpfd2/cloakvpncom_now_accepts_monero_using_payment_id/)

contact admin@cloakVPN.com

**Comment by rehrar** [comment]
@pwrcycle can we close this issue? :) It's done.

**Comment by pwrcycle** [comment]
Resolving :)
