### ISSUE TITLE
monerobase

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#27]
Add https://monerobase.com/ in the "Tools" section.

**Comment by fluffypony** [comment]
Done

**Comment by davidlatapie** [comment]
Since I can't find it either, I suppose this is because syncing is not done yet?

**Comment by fluffypony** [comment]
Done here: https://github.com/monero-project/monero-site/commit/043722447022b736c6f7096b582d7083553beff2

Don't worry about the live site, that isn't always synced up immediately
