### ISSUE TITLE
New merchant

### ISSUE THREAD

**Issue by FlokiNET** [monero-project/monero-site#276]
Hello,

please add https://flokinet.is to the list, we also accept Monero for all services.

Thanks!

**Comment by erciccione** [comment]
Hello,
I noticed that you have small banners on the bottom of the front page but i don't see the "Monero" one, can you add it please?

**Comment by FlokiNET** [comment]
Our development team was slower then this post :) Banner has been added.

**Comment by erciccione** [comment]
Great! Thank you

**Comment by erciccione** [comment]
Hello @FlokiNET  , the link has been added to the website, close this Issue please
