### ISSUE TITLE
Payment Gateway Paybee Changed

### ISSUE THREAD

**Issue by craig-st** [monero-project/monero-site#281]
Payb.ee is now live (no longer beta) and has rebranded as GloBee with a new url:  http://globee.com/

**Comment by QuickBASIC** [comment]
At the moment globee.com seems to be re-directing to payb.ee.

**Comment by w104tcl** [comment]
I seem to be having the same issue.  Takes me to pay.ee and states it is still in beta.  Used a few different browsers on my phone.  I can provide screenshots if needed.
