### ISSUE TITLE
Shouldn't Crypto Kingdom be dropped from the directory?

### ISSUE THREAD

**Issue by stoffu** [monero-project/monero-site#283]
I've only created an account but not haven't really gotten into it, so I know hardly anything about it, but it appears that the game turned out to be a scam:

https://bitcointalk.org/index.php?topic=1890786

**Comment by rehrar** [comment]
@stoffu this is now done. We can close this issue. :)

**Comment by stoffu** [comment]
@rehrar Great, thanks!
