### ISSUE TITLE
Add Store to Merchant list

### ISSUE THREAD

**Issue by Synntechgaming** [monero-project/monero-site#285]
Hi, 

I own https://synntechgaming.com and would like to be added to the list of merchants accepting Monero. We build high-end custom desktops and offer professional services based out in NJ and LA. We've just announced that we will be accepting BTC, ETH and XMR as form of payment.

Thanks.

-Synntech

**Comment by rehrar** [comment]
@Synntechgaming seeing as how the store was added, can we close this issue? Thanks.
