### ISSUE TITLE
Website redesign can now bw marked complete :)

### ISSUE THREAD

**Issue by snirp** [monero-project/monero-site#297]
https://getmonero.org/resources/roadmap/

**Comment by xmr-eric** [comment]
There are still a few areas that aren't finished. The forum funding system, for example. Kovri. Reddit styling. Rehrar outlined these recently. But soon! :)

**Comment by rehrar** [comment]
@snirp You can go ahead and close this issue if you'd like. Everything is basically done. :) I will be marking it as complete very soon.
