### ISSUE TITLE
Getting closer to feature parity for the toolbar

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#3]
List of Markdown not yet replicated in toolbar:
* heading 2-6 (heading 1 shall not be used so better not to encourage it - Heading 5 and 6 will probably not be used)
* blockquote
* lists, both ordered and unordered
* code, both block (`<pre><code>`) and inline (`<code>`)
* horizontal rule (I for one use it from time to time but if only HTML input is possible, I won't die, although it would break the principle of feature parity)
* anchor links (probably tricker to handle UX-wise, low-priority)

**Comment by fluffypony** [comment]
Closing this as Monero forum is a different repository, but @SkepticalHippo is already working on additional buttons for it, so I've tagged him in this message

**Comment by davidlatapie** [comment]
Created an issue on the correct forum.
