### ISSUE TITLE
RSS Feed?

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero-site#306]
Is there an RSS feed for https://getmonero.org/blog/ ?

**Comment by mattcode55** [comment]
Are you looking for something like [https://getmonero.org/feed.xml](https://getmonero.org/feed.xml)?

**Comment by phloatingman** [comment]
Yup https://getmonero.org/feed.xml works for me.  Thanks!  Although, I don't know how easy it would be for someone to find the feed.  I don't see a link to the feed on the front page or on https://getmonero.org/blog/ .  Also, my feed reader wasn't able to autodetect a feed on the site.

**Comment by rehrar** [comment]
I will add a link into the footer.
