### ISSUE TITLE
exchanged.i2p

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-site#308]
Please add exchanged.i2p to 

https://getmonero.org/community/merchants/

**Comment by entertheabyss** [comment]
Bitcointalk thread https://bitcointalk.org/index.php?topic=1092682.0

**Comment by QuickBASIC** [comment]
This was added in July and nobody added it to the Merchants page to my knowledge. Can someone confirm it's still up before we add it? I'm wondering if we probably should indicate it's not a clearnet site in the link.

+merchant

**Comment by rehrar** [comment]
Confirmed active. Add it.

**Comment by erciccione** [comment]
Added in #646 

+in progress
