### ISSUE TITLE
Moneros accepted

### ISSUE THREAD

**Issue by AndreKoscianski** [monero-project/monero-site#327]
The following page states that the merchant (in Brazil) accepts Monero (along with Bitcoins and Dash).
You can use Google Translator to read from Portuguese.

https://www.celestionshop.com/pagina/quer-mais-desconto-conheca-nossas-outras-opcoes-de-pagamento.html

By the way, I'd like to make a remark. Check the following page (kidnap + Monero ransom):

http://www.jornalemfoco.com.br/policia-civil-de-sc-da-detalhes-de-sequestro-com-pedido-de-resgate-em-moeda-virtual/

The video on your webpage.. the police guy should mean repression, right? I confess I was (/am) uncomfortable with it. Well, in the case of the second link above, it is just the opposite: monero is associated with crime.
Monero can be secure, untraceable, XMR can be this and that, but if normal people read about Monero only in the 'crime stories' section of newspapers, they will drift away. There's a cultural thing you're not weighting here. No GUI and with ideas about webpages in Esperanto.. sorry guys, real people have bills to pay and must make a living (= accepting money). If grandma can't use Monero, the fault is with the technology: super-advanced-technology should solve problems, not bring new ones. Period.

**Comment by erciccione** [comment]
Added in #320 
About the second part, GitHub is not the place for this kind of discussions. Try on the freenode channel #monero or reddit :)
