### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by binaryFate** [monero-project/monero-site#336]
Buttons are too far up, on top of text.
See screenshot: http://i.imgur.com/zRwVo35.jpeg

Config: Firefox 54, linux Ubuntu 16.04 64bits

**Comment by erciccione** [comment]
I have the same problem. I opened an issue [on rehrar 's fork]() weeks ago, but it probably got lost after the merge

**Comment by MaxXor** [comment]
I can't reproduce this. For me it's looking fine on Windows 7 with Firefox 54.0.1 (on 1920x1080). Maybe this is related to screen resolution or OS?

**Comment by binaryFate** [comment]
I'm on on 1920x1080 too

**Comment by erciccione** [comment]
@MaxXor might be, but  the fix suggested in #342 play around the problem increasing the height of that section of .5
This will fix the problem for Ubuntu users but shouldn't affect in a relevant way windows users

**Comment by jrob-io** [comment]
@binaryFate @erciccione Since this might be a font issue, can anyone test to see if #315 would fix this?

In Firefox, go to Developer Tools > Style Editor > `custom.css`
In Chrome, Developer Tools > Sources > `custom.css` via the file picker on the left
Delete `sans-serif` from lines 32 and 46.

**Comment by erciccione** [comment]
@jrob-io Tested. I can confirm, #315 will fix this issue
