### ISSUE TITLE
Monero Downloads Page link does not redirect

### ISSUE THREAD

**Issue by afighttilldeath** [monero-project/monero-site#341]
There is a link on the Downloads Section of the website that doesn't redirect to appropriate user-guide section. Seen here:

![download page](https://user-images.githubusercontent.com/29437578/28579263-252e915a-712a-11e7-951b-16ff5944c890.png)
 
Recommend either editing link to redirect to appropriate section or deleting applicable section.

**Comment by mattcode55** [comment]
Related to #358

**Comment by erciccione** [comment]
@afighttilldeath #358 has been merged. Can you close this issue?

**Comment by QuickBASIC** [comment]
+bug
+resolved
