### ISSUE TITLE
Telegram link within hangouts page does not work.

### ISSUE THREAD

**Issue by paultheastronomer** [monero-project/monero-site#343]
The link to Telegram does not work: https://getmonero.org/community/hangouts/

It redirects to: tg://resolve?domain=bitmonero

giving the error: The address wasn't understood

**Comment by mattcode55** [comment]
I think that the Monero telegram (or at least the IRC bridge) got closed because of spam from people pumping shitcoins. If it's gone, maybe it should be removed from the page?
