### ISSUE TITLE
Will Accept Monero for Printed Goods.

### ISSUE THREAD

**Issue by thesyndicated** [monero-project/monero-site#346]
500 Business Cards for 1
1,000 Business Cards for 1.5
All manner of business forms, envelopes, copies, large format banners, you name it. Contact Mark@mycopycorner.com

**Comment by cryptochangements34** [comment]
If you have a website then that can be linked on the 'merchants' page but otherwise there isn't really a place for "flyer" type posts

**Comment by thesyndicated** [comment]
Website will be up within 2 to 3 weeks full shopping cart environment
Monero capable at www.mycopycorner.com

**Comment by cryptochangements34** [comment]
ok cool. Leave a comment here once the site is up and running, then it will be added ;)

**Comment by mattcode55** [comment]
@thesyndicated your website still doesn't seem to be up

**Comment by thesyndicated** [comment]
No, right now everything is on fire so the website is not accessible.

**Comment by QuickBASIC** [comment]
@thesyndicated Ping.

+merchant

**Comment by rehrar** [comment]
@thesyndicated please respond soon, if not, this issue should be closed.

**Comment by QuickBASIC** [comment]
@rehrar I think there's been sufficient time for him to respond. We should just mark as `stale` and issue-bot will close it. If anyone disagrees they can say so and we can re-open it.

**Comment by thesyndicated** [comment]
Yes, my apologies for not responding. I have inherited a lot of problems at
this job. We are rolling our office over from a microsoft environment to a
linux environment post fires up here in norcal. The website has been
sidelined as a project financially so we are currently accepting monero in
our store front with limited takers. I will be sure to post another request
to be added to your list of vendors when the webcart project is developed
to a workable mature state.
Regards
-Mark

**Comment by QuickBASIC** [comment]
@thesyndicated Thanks for your quick reply. I'll go ahead and close the Issue. You're definitely welcome to open a new request when it's functional.

(Closing as stale since `resolved` doesn't seem appropriate given that it's still not added.)

+stale
