### ISSUE TITLE
Typo in FAQ

### ISSUE THREAD

**Issue by Hl2run** [monero-project/monero-site#349]
Hello,

there is a typo in the word WINCE instead of SINCE.

monero-site/get-started/faq/index.md

**Comment by QuickBASIC** [comment]
I'm not able to find the typo in that file. I searched the repo for the word 'wince' and don't see it in any files.

**Comment by Hl2run** [comment]
Weird, somebody fixed it. Anyways, thanks for your time.

**Comment by QuickBASIC** [comment]
No problem. It happens. Thank you for closing the issue.

**Comment by mattcode55** [comment]
Not important anymore, but just for completeness sake, it was fixed in #333.
