### ISSUE TITLE
Typo in whitepaper review

### ISSUE THREAD

**Issue by GovanifY** [monero-project/monero-site#352]
Yes I actually read this [whitepaper](https://downloads.getmonero.org/whitepaper_review.pdf) and yes I am indeed nitpicking but hey, better than leave it alone!

I haven't been able to find the pdf on this repository though so I am unable to make a pull request to edit the pdf, so here is an issue.
Page page 6/8, 3.2 New Algorithm, quote:
```
3.2.
New Algorithm.
Van  Saberhagen  makes  excellent  points  that  cost  of  in-
vestment should grow faster than linearly with power, and ge describes a perfect
```
`ge` should be replaced by `he`

**Comment by mattcode55** [comment]
I think that this is an issue for [the MRL](https://github.com/monero-project/research-lab). See the `whitepaper` folder in there (although I don't see the source for the PDF).

**Comment by GovanifY** [comment]
Indeed is, didn't realized this rpeo existed, thanks!
