### ISSUE TITLE
Add our site Koddos.net to the merchants list

### ISSUE THREAD

**Issue by koddos** [monero-project/monero-site#354]
Hello,

We have started to accept Monero on our site for all our hosting and DDoS protection services. 

The website is http://koddos.net

Thank you
Martin

**Comment by koddos** [comment]
We are still not visible on merchants page. Is there any reason?

**Comment by mattcode55** [comment]
Looks like it was accidentally removed again.

**Comment by koddos** [comment]
I opened a new case for it https://github.com/monero-project/monero-site/issues/449
