### ISSUE TITLE
Adding monero merchant: NiceVPS.net

### ISSUE THREAD

**Issue by nicevps** [monero-project/monero-site#360]
Hi, would love to be added to the Monero merchants list. NiceVPS.net - VPS & Hosting (https://nicevps.net)
We already have a forum topic: https://forum.getmonero.org/3/merchants-and-marketplace/88159/nicevps-cheap-anonymous-monero-hosting-fast-protected-vps-starting-1-99-mo-1gbps

Thanks

**Comment by SamsungGalaxyPlayer** [comment]
@nicevps this has been added in #364 and will be pushed when the next round of updates come
