### ISSUE TITLE
Please add MSvB HW Design to Services

### ISSUE THREAD

**Issue by michaesc** [monero-project/monero-site#375]
Please add the following two lines of text to:

https://getmonero.org/community/merchants/

---- Begin text ----
MSvB Hardware Design
Using a secure element
---- End text ----

The hyperlink should navigate to:

"mailto:monerodev+sitesvcs@encambio.com?subject=Monero Services Hardware Design Request"

The code might resemble:

```
<div class="col-md-4 col-sm-6 col-xs-12">
    <a href="mailto:monerodev+sitesvcs@encambio.com?subject=Monero Services Hardware Design Request">MSvB Hardware Design,<br />Using a secure element</a>
</div>
```

Reasoning: Current efforts at creating custom Monero hardware designs such as a wallet or ATM machine. Requests are outstanding, so it would be good to have a place of contact on the site.

Thank you.

**Comment by QuickBASIC** [comment]
@michaesc Can you clarify? You're a merchant selling something that people can pay for in Monero or you're a company developing hardware for Monero? Do you have a website for the project so we can link to that?

**Comment by michaesc** [comment]
I'm not a merchant, but rather a computer scientist that can provide the service of hardware design. This is relevant and a bit hard to find, so you might find it's a good fit for the Monero website. It happens that I've had folks from the Monero community approach me with their ideas requiring hardware design.

Yes, I and the customer exchange in XMR.

My website is a bit too general (since hardware design is a recent development for me) and that's why I'd rather provide a contact point through email. This might change once I can put specifics of secure element hardware in the documentation (website and mailing lists.)

**Comment by QuickBASIC** [comment]
Okay. Thank you. I've added it to PR #374 and it should be merged relatively soon.
