### ISSUE TITLE
XMR Lottery

### ISSUE THREAD

**Issue by xmrlotto** [monero-project/monero-site#390]
Hi!  I am looking to get listed on the "Merchants & Services" page under entertainment.  I've built a lotto website here: https://www.xmrlotto.com.

Please let me know if there is anything I need to do!

Thanks!

**Comment by QuickBASIC** [comment]
Added in my existing PR. Should be updated whenever @fluffypony merges. (With the Monero 0.11.0.0 release it's likely he's busy tying up loose ends, so might not be right away.)
