### ISSUE TITLE
Migrating docs to Slate

### ISSUE THREAD

**Issue by lessless** [monero-project/monero-site#391]
Hello team,

Last month I complete migrating current docs to slate https://github.com/lessless/lessless.github.io
The feedback was good and we started to discuss with @rehrar how we can integrate it in the Monero website. 

So far I see 2 options: 

- Dissect docs project and integrated in the current website. According to  my investigation that should be possible  because both of the projects are using very similar static site generators written in Ruby. Monero Website use Jekyll and Slate uses Middleman. Thee  obvious paint points here are  differences in template language (Liquid vs ERB) (particularly loops that outputs content - https://github.com/lessless/lessless.github.io/blob/ad3c55a793332177b2c9a793d71e7d3ddbaa1444/source/layouts/layout.erb#L55, that guy got me stuck) and in how project settings are set up (footer/header inclusion, layout, assets processing, etc). Most work & time intensive way and also will break compatibility with Slate, means no bug fixes and updates. 

- Generate static content and upload them either to the current location https://getmonero.org/resources/developer-guides/ or as https://docs.getmonero.org

I'm 100% for the later option since docs looks quite different from the main website.  Also ERB (template language that Slate is using) is much less secure and allows arbitrary code execution on the static content generation stage.  Because of that it can make sense to host them on the different host or carefully review PR's :) 

If needed we can sponsor Scaleaway host for 3-5 years, they're starting from 3 eur/month, lol.

**Comment by serhack** [comment]
I'd like to have a domain like docs.monero.org with slate! Keep Your good work @lessless

**Comment by lessless** [comment]
thanks @serhack!  I'm also working on the updating docs with calls from the recent update by @cryptobadger https://github.com/monero-project/monero-site/pull/377

**Comment by lessless** [comment]
@rehrar after https://github.com/monero-project/monero-site/pull/399 docs are much more readable (or at least I don't have a problems with them anymore).

I'm not sure if this issue still holds.

**Comment by anonimal** [comment]
Slate requires browser enabled javascript? Monero-site is supposed to be functional without javascript.

**Comment by lessless** [comment]
@anonimal exactly: search and menu expanding / collapsing requires JS

**Comment by anonimal** [comment]
>I'm not sure if this issue still holds.

Considering the amount of API documentation in monero which is already covered by Doxygen, and the amount of non-C++ documentation which is very minimal by comparison, and since monero-site is *supposed* to be functional without javascript, then yes: this issue may no longer be applicable (nice idea though if there were a pressing need (maybe there is?)).

**Comment by QuickBASIC** [comment]
@anonimal @lessless 

It seems like the consensus is that this issue can be closed, but I wanted to check before we closed the issue.

+improvement
+guide

**Comment by lessless** [comment]
Confirming

**Comment by QuickBASIC** [comment]
Thank you.

+resolved
