### ISSUE TITLE
Consider putting downloads in a separate submodule?

### ISSUE THREAD

**Issue by hyc** [monero-project/monero-site#393]
This repo is particularly huge and slow to clone. Is it because the downloads/binaries are part of the repo?

**Comment by fluffypony** [comment]
@hyc Huh? They're not at all; total size is 104mb including full git history, actual data size is 56mb. The offending folder is the ```media``` folder, which has the 4 Monero videos in.

**Comment by mattcode55** [comment]
Would it be worth looking at [git-lfs](https://git-lfs.github.com/) for storing the videos?

**Comment by hyc** [comment]
OK. Didn't actually look to see where the space was going, but it was a lot longer to download than I expected.

**Comment by fluffypony** [comment]
@mattcode55 if the videos get larger, sure, but seeing as how the site is well under half the size of the CLI project I don't think we need to worry about it.

**Comment by rehrar** [comment]
I have compressed the videos. I experiment with compressing further while testing to see when there is great loss of quality. The choice to keep the media files on the site itself is for Tor-friendliness.

**Comment by QuickBASIC** [comment]
+suggestion

**Comment by QuickBASIC** [comment]
+discussion

**Comment by rehrar** [comment]
This may still be something worthwhile to do. This would allow all of the sensitive links to be controlled by the Core Team, while it may allow additional collaborators on the site repo if it was ever called for in the future.

**Comment by QuickBASIC** [comment]
While I agree with you, @rehrar, I don't know if it's worth the added complexity at the moment. As long as maintainers don't merge things willy-nilly, collaborators do a fine job of reviewing changes to the site. (I for one check the diffs religiously if it's the Downloads page with hashes or the one with the dev donation address.)

**Comment by rehrar** [comment]
Indeed. Key wording there being "in the future". Don't see it as being needed right now, as Luigi gets into the swing of things.

**Comment by erciccione** [comment]
What is the feeling about this at the moment? Is a submodule needed at this state of things?
If not i would close this issue, a new one can be opened if necessary

**Comment by fluffypony** [comment]
@erciccione see my comment on the podcasts issue - I'd vote for moving the videos on to downloads.getmonero.org and having a repo for that.

**Comment by erciccione** [comment]
> I'd vote for moving the videos on to downloads.getmonero.org and having a repo for that.

+1
see [my comment in #249](https://github.com/monero-project/monero-site/issues/249#issuecomment-399910088)

**Comment by erciccione** [comment]
This issue was discussed and closed on gitlab.
