### ISSUE TITLE
Download link broken for MacOS GUI client on official website

### ISSUE THREAD

**Issue by evantbyrne** [monero-project/monero-site#395]
Not sure if this is the appropriate place to report this, but the download link for the MacOS GUI client is broken.

https://downloads.getmonero.org/gui/mac64

– Evan

**Comment by QuickBASIC** [comment]
Yes, this is the correct place. It's currently being worked on.

**Comment by dEBRUYNE-1** [comment]
Should be fixed now. 

+resolved

**Comment by QuickBASIC** [comment]
@dEBRUYNE-1 The bot isn't implemented here on monero-site.

**Comment by QuickBASIC** [comment]
@evantbyrne The download is up. Can you please close this issue?

**Comment by evantbyrne** [comment]
Looks like it working now. Thanks everyone!

**Comment by dEBRUYNE-1** [comment]
@QuickBASIC I'll page pigeons. I thought it was working here already :-P
