### ISSUE TITLE
'naked" URLs are not converted into links

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#4]
`https://en.wikipedia.org/wiki/Swoosh` will not turn to [https://en.wikipedia.org/wiki/Swoosh](https://en.wikipedia.org/wiki/Swoosh), which is the expected behaviour for most.

Example: https://forum.monero.cc/20/general-discussion/162/who-is-our-carolyn-davidson

**Comment by fluffypony** [comment]
That's by design: http://daringfireball.net/projects/markdown/syntax#autolink

Also forum issues don't go here, they go on the Monero forum repository.

**Comment by davidlatapie** [comment]
Link to monero forum repository? Could not find it on https://github.com/monero-project/ or Google

**Comment by fluffypony** [comment]
@davidlatapie it's a private repository, per my comment on IRC
