### ISSUE TITLE
Add HitBTC to exchanges list

### ISSUE THREAD

**Issue by NickSonJon** [monero-project/monero-site#401]
Hello!

Please add a HitBTC exchange on your exchanges list on this page: https://getmonero.org/community/merchants/
Here are the links to monero markets, please use one of them: 
https://hitbtc.com/exchange/XMR-to-BTC
https://hitbtc.com/exchange/XMR-to-ETH
https://hitbtc.com/exchange/XMR-to-USDT

Thank you!
You can easilly contact me via email: nickhitbtc@protonmail.com

**Comment by mattcode55** [comment]
-1, HitBTC is listed as an exchange to avoid on the [/r/monero scam list](https://www.reddit.com/r/Monero/wiki/avoid#wiki_exchanges).

**Comment by QuickBASIC** [comment]
This issue has been open for 12 days and it seems the consensus is to not add HitBTC for reasons noted on the Reddit /r/Monero scam list.

@fluffypony Can we please close this issue?

**Comment by QuickBASIC** [comment]
A few have voiced our concerns and there's been no reply from OP. Not to mention, it is listed on the /r/Monero scams list.

Given that community members have also used 👍👎emojis to signal their opinion in this regard, I'm going to assume that the community does not wish to list this exchange at this time.

+merchant
+wontfix

**Comment by NickSonJon** [comment]
As far as I know, all issues, which were on monero scam page were solved. Our support team is always opened for conversation, they even talk in specified threads, dedicated to those issues on community forums, trying to solve those issues.
