### ISSUE TITLE
Addition for Merchants List: TheBigCoin.io

### ISSUE THREAD

**Issue by TheBigCoin** [monero-project/monero-site#406]
TheBigCoin.io - a great new service which helps spend Monero and other cryptocurrencies anywhere online.
 
At the moment 99% of the web still doesn’t accept digital currency like Monero as a form of payment. And we solve this big problem by buying the product on customer behalf, while at the same time receiving from the customer an equivalent amount of cryptocurrency. Our main difference compared to Bitcoin Debit Cards is that our service is fully anonymous, we never ask you to provide any personal information and don't require to sign up.

Link: https://www.thebigcoin.io/

Would it be possible to list our website in Services list? Thank you.

**Comment by mattcode55** [comment]
Hey, I've submitted #407 so your site will appear on getmonero.org when that gets merged.

Going out of the scope of this issue but do you support GBP? I pasted in an Amazon UK link but the price came up in dollars and euros instead of pounds.

**Comment by TheBigCoin** [comment]
Hello!

At the moment, we support only EUR and USD. USD is set as a primary currency. But we are planning to make some improvements in nearly future.
