### ISSUE TITLE
Issue with FAQ section

### ISSUE THREAD

**Issue by keatond** [monero-project/monero-site#408]
Was looking some info up for a friend and when I went to the FAQ section the last question was a bubble check box instead of a drop down. Is this on purpose? When you click the column it opens the item above it.
![capture6](https://user-images.githubusercontent.com/428041/30692862-3b370c9a-9e9b-11e7-8fab-57550648fede.JPG)

**Comment by QuickBASIC** [comment]
That one is my fault. related #397 

It just hasn't been merged yet. @fluffypony if you're not busy can you merge @cryptochangements34 fix for the FAQ?

**Comment by QuickBASIC** [comment]
+bug
+resolved
