### ISSUE TITLE
Addition for Merchants List: LocalMonero.co

### ISSUE THREAD

**Issue by applebaum** [monero-project/monero-site#410]
Hello, Monero team!

Would be nice to see [LocalMonero.co](https://localmonero.co/) on the exchanges list. 

LocalMonero is a Monero P2P exchange, a Monero's equivalent of LocalBitcoins.com. Unlike centralized cryptocurrency exchanges, you make a trade directly with another person. This makes the process lean and fast, as there is no corporate overhead. You get your Monero instantly. Also, LocalMonero.co can support every payment method its user community supports, making it possible for users without access to traditional banking to also be able to buy or sell Monero. For every transaction, LocalMonero.co offers escrow or transaction service to protect the buyer of Monero.

**Comment by erciccione** [comment]
Added in #420

**Comment by applebaum** [comment]
@erciccione Thank you!
