### ISSUE TITLE
Reddit icon messed up on Hangouts page.

### ISSUE THREAD

**Issue by applebaum** [monero-project/monero-site#411]
Noticed that in Firefox and Chrome reddit social icon is displaying incorrectly on https://getmonero.org/community/hangouts/.
![getmonero-hangouts](https://user-images.githubusercontent.com/26916516/30745934-a78c3bc0-9fb0-11e7-97c8-fe7f643ef9c3.png).

**Comment by mattcode55** [comment]
How long has it been like that? [Git blame shows that this stuff hasn't been touched for a few months](https://github.com/monero-project/monero-site/blame/master/css/custom.css#L3232).

**Comment by applebaum** [comment]
@mattcode55 can't say, first time I've visited that page.

**Comment by rehrar** [comment]
Everything was working correctly when I put it up the first time. I am aware of the issue, and I've fixed it. I will be putting out a Spring Cleaning patch in a couple days or so. It will address this.

**Comment by erciccione** [comment]
+bug
