### ISSUE TITLE
Provide better tutorials / info on cli tools

### ISSUE THREAD

**Issue by jonathancross** [monero-project/monero-site#414]
RE: https://github.com/monero-project/monero/issues/985

We should provide better documentation and examples of cli tools, options and how to use.
I'm assuming this would go here : https://getmonero.org/resources/user-guides/ but maybe there is a better location?  Something like "How to use monero in a terminal" with very basic examples and linking off to details about configuration of `monerod`, `monero-wallet-cli` options, etc.

**Comment by QuickBASIC** [comment]
> I'm assuming this would go here : 

The README for monero-site has directions for adding a user guide. If you feel so inclined, follow those directions.

**Comment by mattcode55** [comment]
There's a guide for the wallet cli at https://getmonero.org/resources/user-guides/monero-wallet-cli.html

**Comment by jonathancross** [comment]
Makes sense.  I'll look into it setting up locally and making the change myself.

**Comment by QuickBASIC** [comment]
Awesome. From the way you phrased the issue it sounded like you intended on fixing it yourself. Make sure you use issue keywords 'fixes #blah' in a commit message or PR to close the issue when it gets merged.

**Comment by erciccione** [comment]
+improvement

**Comment by jacklenox** [comment]
Having recently been through this, I'd be happy to try to help here. Are we talking about literally just setting the daemon going and opening up the wallet?

**Comment by jonathancross** [comment]
@jacklenox Contributions welcome! I kinda dropped the ball and got distracted with other things.

Idea is just to add examples and explanations for common use cases here: https://getmonero.org/resources/user-guides/

The [monero-wallet-cl](https://getmonero.org/resources/user-guides/monero-wallet-cli.html)i example is great, would be nice to have a similar document for the daemon.  Here are a few ideas:

* How to securely allow remote connections (and considerations)
* How to only allow rpc from localhost
* username / password considerations (eg: can't use `#` in the password or it is interpreted as a comment and will strip all characters after that in the bitmonero.conf)
* _some_ commandline arguments work inside `bitmonero.conf`, others do not. A few example that don't:
  * `no-igd`
  * `confirm-external-bind`
  * `restricted-rpc`
  * `rpc-bind-ip` - works, but cannot be specified more than once

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
