### ISSUE TITLE
New website for Monero Merchants & Services page

### ISSUE THREAD

**Issue by shubidoo** [monero-project/monero-site#429]
Hey guys :) 

Would it be possible to add our shop to the Monero Merchants & Services page? We are selling handmade organic clothing and other goods in our shop and have recently started to accept Monero amongst a handful of other selected cryptocurrencies (only 10 so far as we only support the coins we truly believe in as to guide people new to the space to solid projects that are well established or have exciting new features). 

Here is our site: https://xusah.boutique

Thanks a lot for considering and if there are any other questions, feel free to shoot them over and I will try to answer them as good as I humanly can! 

All the best and have a great weekend,
shu

**Comment by erciccione** [comment]
Hi, i see under "payments + shipping" that you have a list of cryptocurrencies you accept, but monero is not listed. Could you add it pls?

**Comment by shubidoo** [comment]
Thanks for spotting that. It has in fact already been added and will be pushed with the next cache flushing that happens at midnight :)

**Comment by erciccione** [comment]
Thanks for the clarification, added in #430

**Comment by shubidoo** [comment]
Thanks a lot @erciccione cache was updated and everyone can see the orange M successfully now! https://xusah.boutique/payments-and-shipping/
