### ISSUE TITLE
Being listed as a Monero exchange

### ISSUE THREAD

**Issue by khashmeshab** [monero-project/monero-site#431]
Hello,

I am Masoud Gheysari, the president and CEO of Karsha Business & Technology Inc. (karsha.biz). We have recently added Monero to the list of our supported cryptocurrencies and have started exchanging it. It would be an honor for us to get listed as one of Monero exchanges at https://getmonero.org/community/merchants/. Please inform me about the required documents and information and its procedure.

Best regards.

**Comment by mattcode55** [comment]
Hi Masoud, your site will get added to the list when #432 gets merged :)

**Comment by khashmeshab** [comment]
Thank you.
