### ISSUE TITLE
Add KoDDoS.net to merchants & services page 

### ISSUE THREAD

**Issue by koddos** [monero-project/monero-site#449]
Hello,

We started to accept Monero on our site back in August for all our hosting and DDoS protection services.

The website is http://koddos.net

Thank you
Martin

**Comment by MaxXor** [comment]
Monero is not added to your [list of payment methods](https://koddos.net/payment-methods.html).

**Comment by koddos** [comment]
It is fixed. Somehow it was not published but we received already payments using Monero with coinpayments.

**Comment by erciccione** [comment]
+merchant
