### ISSUE TITLE
Add me to merchats

### ISSUE THREAD

**Issue by MarcosAguayo** [monero-project/monero-site#451]
I accept Monero as payment.
Programmer and Web Developer
Website: marcosaguayo.com

Thanks

**Comment by mattcode55** [comment]
Hi Marcos, I don't see anything on your website mentioning Monero.

+merchant

**Comment by MarcosAguayo** [comment]
@mattcode55 Sorry I've restarted the cache. Take a look now please.
Thanks

**Comment by mattcode55** [comment]
It'll get added when #452 gets merged :)
