### ISSUE TITLE
Alternate Language Translations

### ISSUE THREAD

**Issue by tyrionmcmaster** [monero-project/monero-site#453]
We need translations of the site for non-English speakers. The will increase exposure to Monero and drive awareness of the project.

**Comment by mattcode55** [comment]
It looks like getkovri.org has things set up to be translated into other languages, maybe we could do something like that, or [something different](http://polyglot.untra.io/)?

**Comment by erciccione** [comment]
Localizing the website is in the scope. Personally, I'm waiting to get the localization platform ready, until that, translations in general are proceeding slowly. IMO once the platform is ready we can decide the best way to localize the website

**Comment by erciccione** [comment]
+feature

**Comment by tyrionmcmaster** [comment]
Updates and/or progress made on this?

**Comment by erciccione** [comment]
@rehrar is almost done implementing this feature, i've seen a preview and it is basically done. Soon out!

**Comment by erciccione** [comment]
+resolved
