### ISSUE TITLE
Categorize/Declutter Moneropedia Articles

### ISSUE THREAD

**Issue by QuickBASIC** [monero-project/monero-site#463]
Even though Kovri is going to be integrated into Monero in the future, I feel like having a lot of stub articles about Kovri topics in the Moneropedia is detrimental to it's function as instructional for new users. (Currently 34.9% of articles are Kovri-based.)

I'm not as familiar with I2P or Kovri, so I don't feel equipped to make the change myself. I think a lot of this information can be moved copied over to [monero-project/kovri-site](https://github.com/monero-project/kovri-site) eventually, but for now I think we should consolidate it into one article. (Another possibility I've considered is to expand Moneropedia to include categories, and categorize these in a way that it's easier to navigate Monero specific topics seperate from Kovri topics.)

I believe these are all the articles that are currently Kovri related:

[Base32-Address](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/base32-address.md)
[Base64-Address](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/base64-address.md)
[Canonically Unique Host](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/canonically-unique-host.md)
[Clearnet](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/clearnet.md)
[Destination](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/destination.md)
[Eeepsite](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/eepsite.md)
[Floodfill](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/floodfill.md)
[Garlic Encryption](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/garlic-encryption.md)
[Garlic Routing](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/garlic-routing.md)
[i2np](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/i2np.md)
[i2p](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/i2p.md)
[i2pcontrol](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/i2pcontrol.md)
[java-i2p](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/java-i2p.md)
[Jump Service](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/jump-service.md)
[Kovri](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/kovri.md)
[Lease](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/lease.md)
[Network Database](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/network-database.md)
[Router Info](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/router-info.md)
[SSU](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/ssu.md)
[Subscription](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/subscription.md)
[Transports](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/transports.md)
[Tunnel](https://github.com/monero-project/monero-site/blob/master/resources/moneropedia/tunnel.md)

+moneropedia
+enhancement

**Comment by anonimal** [comment]
Bad idea to merge into a single article. Good idea to have top-level categories.

**Comment by QuickBASIC** [comment]
> Bad idea to merge into a single article. Good idea to have top-level categories.

I kinda agree with you, but with Kovri having it's own site, I think we don't have to have individual articles for things that could be categorized under a particular article. Wikipedia does this somewhat and uses section headers for each bit of information, so it's still possible to link directly to a particular subject in the article. The articles should have magnet links to jump to each section. 

For instance:

Kovri
*Top level information of what Kovri is and does. Explaining the difference between it and I2P. (C++ vs Java, etc).*
_I2P (subsections explaining each of these things specifically how their implemented in Kovri)
__Tunnel
__Transport
__Jump Service
__Subscription
__Garlic Encryption
__Garlic Routing
__EEP Site

**Comment by erciccione** [comment]
I agree that many of those terms may create confusion, but I also agree that merge everything in one article is not optimal and dispersive. What about make a 'Kovripedia' on getkovri where pull this terms? IMO they are enough and they will increase with time, it would be needed in future anyway

**Comment by QuickBASIC** [comment]
+moneropedia
+enhancement

@danrmiller Any idea why the bot didn't pick up the labels from the OP?

**Comment by anonimal** [comment]
I think monerpedia could use more work and be given more exposure once that works done. I'm agreeing with all the issues here.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
