### ISSUE TITLE
MegaChange.is exchanger listing

### ISSUE THREAD

**Issue by MegaChange** [monero-project/monero-site#466]
Hello

can you list https://www.megachange.is/ p2p exchange platform in here https://forum.getmonero.org/8/funding-required

**MegaChange.is the p2p(Over-the-counter) platform where 2 parties can trade without any limitations**

Here is simple example of how it works
_Lets say You need to exchange bitcoin to Skrill(Alipay, Neteller and etc.) or Skrill(Alipay, Neteller and etc.) to bitcoin or anything else.

I this case MegaChange.is doesn't operate as a standard centralised exchange provider and We don't hold any Skrill(Alipay, Neteller and etc.) or bank account at all.

What we do is provide the facility in which you and other person can be connected to each other and send too each other Skrill(Alipay, Neteller and etc.) or bank transfer_

We act as guarantor of the safety of your funds when two parties trades to each other.
This service allows people from all over the world to pay to each other with the lowest fee possible. Using this scheme you save up to 50% on exchangers fees and save your preserouse time
Do you want to be ripped of by some unknown exchanger or bestchange monitoring? We don't think so

- - - - - - - - - - - - - - - - - - 
**Example:**
_John need to exchange 1 Bitcoin to Skrill 3500usdс(it means that John wants to get paid 3500usd via Skrill) - John creates a trade deal, pays it then wait untill someone will accepts his trade and pay him 3500 usd.
1 BTC which was paid by John is securely stored in our facility and treated as a secure deposit to his trade deal.

After some time Bob visited MegaChange.is in order to exchange Skrill into Tether and he is willing to pay 3500usd

Our p2p(Over-the-counter) platform connects John and Bob for mutual settlement and Bob pays 3500usd into John's Skrill wallet at this moment John will receive an email notification about his trade has been accepted and paid and He(John) needed to confirm that He(John) got paid 3500usd into his Skrill wallet.
in the end of the day: John got his 3500usd on his Skrill and Bob gets usd into his Tether account. 
Everyone is happy and carries on with their lives knowing that they was not ripped of or overcharged._
- - - - - - - - - - - - - - - - - - 

**Your benefits:**
_1. The lowest fees on the market.
2. fraud protection_

We can confirm that your payment is accepted and waiting for counter offer.
As soon as someone accepts it you will receive an email asking you to realize your secure deposit in order to be send to the other party

**Comment by erciccione** [comment]
Hi, The 'Funding Required' section is for projects who are waiting to be funded by the community. Merchants are listed in [getmonero.org/community/merchants/](https://getmonero.org/community/merchants/). Should this be listed as service or exchange?

+merchant

**Comment by MegaChange** [comment]
> Should this be listed as service or exchange?

MegaChange.is Exchanges

the name is exactly MegaChange.is
do not remove ".is" from the end

**Comment by erciccione** [comment]
Added in #464

**Comment by erciccione** [comment]
Monero.how is not maintained by the community. You need to contact the developer directly

**Comment by MegaChange** [comment]
apart from https://getmonero.org/community/merchants/
is there other places where exchangers are listed?

**Comment by erciccione** [comment]
No, the list on the website is the only "official" one

**Comment by MegaChange** [comment]
when do you this our website will be listed?

**Comment by QuickBASIC** [comment]
Whenever the Maintainer merges #464.

**Comment by erciccione** [comment]
I didn't notice that Monero wasn't listed, thanks @mattcode55 for pointing that out (referencing #464 ). I removed your exchange from #464 , please communicate us when you'll be accepting Monero and your platform will be added

**Comment by MegaChange** [comment]
Monero has been added, pls processed with listing

**Comment by mattcode55** [comment]
@MegaChange Will get added when #490 gets merged

**Comment by MegaChange** [comment]
Please make the text of the link "MegaChange.is (P2P exchange)"

**Comment by MegaChange** [comment]
please change the title from MegaChange.is -> MegaChange.is (P2P exchange)
It is important people to know that it is p2p trading

**Comment by SamsungGalaxyPlayer** [comment]
@MegaChange it seems like your service provides both automatic conversion and P2P conversion.

**Comment by erciccione** [comment]
@MegaChange  could you clarify  please? ^

**Comment by chinfomail** [comment]
MegaChange.is - Site-scammers. Exchange ID 13378.  On the exchange. Declared 5% + 2 eur in fact 13.5%. After 20 days, just completed Change   and closed the exchange direction.  The money is appropriated.

**Comment by mattcode55** [comment]
@chinfomail Sounds similar to #421 (but with a different merchant).
Listings are not an endorsement, it's a shame you got scammed but
there's not really anything anybody here can do.
