### ISSUE TITLE
Add gameofcryptos.com

### ISSUE THREAD

**Issue by serhack** [monero-project/monero-site#472]
The owner contacted me. They actually can accept monero via third-party. Should we add to merchants directory?
http://gameofcryptos.com/

**Comment by QuickBASIC** [comment]
As long as they have the ability to accept Monero, I don't see any reason why not.

I did add a disclaimer to the merchant page, so we're not really vetting merchants other than "do they accept it?".

+merchant

**Comment by erciccione** [comment]
Added in #464

**Comment by erciccione** [comment]
@serhack Can you confirm they accept Monero as payment? ref [comment](https://github.com/monero-project/monero-site/pull/464#discussion_r152252836)

**Comment by serhack** [comment]
They are using coinpayments that can accept various cryptocurrencies, included Monero. That's why I asked you if they can be added to Monero merchant page.
