### ISSUE TITLE
Request for merchants & services page

### ISSUE THREAD

**Issue by walletmonero** [monero-project/monero-site#473]
We would like to add WalletMonero to your services list on the page: https://getmonero.org/community/merchants/

Previously we introduced our service to Monero community, which resulted in good reviews: https://www.reddit.com/r/Monero/comments/78nvn6/walletmonero_new_monero_light_wallet/

Kindly use the following link: https://walletmonero.com?utm_source=getmonero_org&utm_medium=list&utm_content=monero_list&utm_campaign=getmonero_org

In case of any questions don't hesitate to contact me: support@walletmonero.com

**Comment by QuickBASIC** [comment]
+merchant

**Comment by erciccione** [comment]
Added in #464
