### ISSUE TITLE
New channel #monero-hardware missing from page footers

### ISSUE THREAD

**Issue by michaesc** [monero-project/monero-site#474]
Please add #monero-hardware to the page footers, where other channels are found like #monero-community and #monero-translations. Thanks!

**Comment by mattcode55** [comment]
Are you sure it's necessary to be in the footer and not just the 
community/hangouts page?

**Comment by mattcode55** [comment]
Actually, I'm not sure why the IRC channels in the footer are different 
to the ones on the hangouts page. I must've missed that.
