### ISSUE TITLE
Add a link to getmonero taiga on the homepage

### ISSUE THREAD

**Issue by cryptochangements34** [monero-project/monero-site#476]
I think taiga should be more visible on the site. Looking at the homepage now it looks like there is no reference to it at all. A link at the top, like the forum link, or perhaps under the "community" tab i think would be a good way to show that we are a true grassroots community and maye even get some people involved

**Comment by rehrar** [comment]
I'm torn here. I would like to see Workgroup Resources potentially get its own area of the site, but I need to give more thought as to how it would visibly be different than the 'Hangouts' page, as there is considerable overlap.

On its own, Taiga is just one of several resources we are trying to provide to workgroups, so giving it its own place I don't think is justified unless it is the primary resource (which I don't think it is). As well, more resources should be coming along at some point. I'll think about a way to place it into the home page elegantly.

**Comment by el00ruobuob** [comment]
@rehrar Why not a "help monero community" section with:
- Workgroups:
  - Help others on slack/mattemost
  - Contribute to localization on Taiga
- Projects:
  - propose your improvements on FFS
  - submit PR on GitHub

**Comment by erciccione** [comment]
>giving it its own place I don't think is justified unless it is the primary resource (which I don't think it is)

I think it is one of the primary resources. it became one of the most used tools we have for coordination inside the projects. For example, it's foundamental for the localization workgroup and the monero hardware wallet team, but many other projects use it as the main coordination platform. I think we should add it. 

+discussion
+improvement

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
