### ISSUE TITLE
Request for merchants & exchanges

### ISSUE THREAD

**Issue by ChangeNOW-Exchange** [monero-project/monero-site#483]
We would like to add ChangeNOW to your exchanges list on the page: https://getmonero.org/community/merchants/

Kindly use the following link: https://changenow.io?utm_source=monero&utm_medium=link&utm_term=merchants&utm_campaign=monero

In case of any questions don't hesitate to contact me: info@changenow.io

**Comment by QuickBASIC** [comment]
+merchant

**Comment by erciccione** [comment]
Added in #464
