### ISSUE TITLE
Request for merchants for JuditMatyus.com

### ISSUE THREAD

**Issue by lehelmatyus** [monero-project/monero-site#491]
Hi there!
www.juditmatyus.com now officially accepts Monero as a form of payment. Please add it to your list.
More info here 
www.juditmatyus.com/monero

Thanks!

**Comment by QuickBASIC** [comment]
+merchant

Your site will be added when PR #493 gets merged.

Thanks for including the link for information on how you accept Monero on your site. If you need help with integration, you should contact @serhack who is a resident expert at website integration for Monero. (He's on IRC or Reddit.)

**Comment by serhack** [comment]
Hello @lehelmatyus 
I've developed a monero payment gateway for woocommerce based e-shop.

https://github.com/monero-integrations/monerowp

Please let me know about your questions

**Comment by lehelmatyus** [comment]
@QuickBASIC Thanks for the add!
@serhack Thanks for reaching out, we will try out the plugin some time this week or next week. Looks really promising, thanks!

**Comment by lehelmatyus** [comment]
@QuickBASIC Would you be so kind to add "- Jewelry" after the name so it's clear to potential buyers. Like so "Judit Mátyus - Jewelry".
Much appreciated, Thanks!

**Comment by serhack** [comment]
@lehelmatyus if you have some problems, write me :)

**Comment by QuickBASIC** [comment]
Done.
