### ISSUE TITLE
Create ATM section on https://getmonero.org/community/merchants

### ISSUE THREAD

**Issue by amochkin** [monero-project/monero-site#492]
Hi, please create an ATM section on https://getmonero.org/community/merchants
Also you could put a link to https://trovemat.com/ that can sell Monero for Fiat Cash. And soon will be able to dispence Fiat Cash for Monero. 
Thank you!

**Comment by QuickBASIC** [comment]
+merchant

I'm not certain that we need a whole section for ATMs yet considering you'd be the only listing. Would it be okay if we listed it in Exchanges as `Trovemat.com (ATM)`?

**Comment by amochkin** [comment]
I guess no problem if you add it to exchange.

**Comment by Sifrqitt** [comment]
Hi @amochkin Your ATMs and website look amazing! What a great product to offer! I'm reaching out to speak with you about adding a cryptocurrency to your ATM programming...could you send me a message 😄 Cheers! 🍻 I've already shared your link with a friend, and the crypto group thinks it's a great idea! ATMS support organic growth and develop the infrastructure that crypto is built upon!
