### ISSUE TITLE
Trojan JS:ScriptIP-Inf [Trj] found on "moneropools.com" by Avast

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [monero-project/monero-site#495]
So I don’t know what it is but when clicking on the link in:
`Pools A listing of trusted Monero pools is found here.`
on https://getmonero.org/get-started/mining/ page.

Avast claims to block an infection which is: `JS:ScriptIP-Inf [Trj]`

A quick search gave me ([source](https://www.im-infected.com/trojan/jsscriptip-inf-trj.html)):
```
JS:ScriptIP-Inf [Trj] is a dangerous computer infection that comes in a Java Script file. It can do many bad things to a computer once it gains an access.
```
That does not seem very trustworthy. I could not find the corresponding github page to look into that sites code. So maybe someone could check it out or we could find another site listing pools that does not contain the trojan…

**Comment by cleanforestco** [comment]
Hi @ThibaultJanBeyer, 

Can you try another web browser and see if you get the same Avast warning?

Sucuri Website Scanner, GravityScan.com and OpenDNS did not detect any issues with moneropools.com.

**Comment by ThibaultJanBeyer** [comment]
Same result
I tried in Chrome `Version 62.0.3202.94 (Official Build) (64-bit)`.
I tried in Firefox `Version 57.0`
on `Mac OS 10.13.1`.
With Avast `Version 13.2`

Do you know where it comes from? Maybe it’s some kind of weird tracker implemented…

**Comment by mattcode55** [comment]
Some desktop anti-virus packages/firewalls are starting to block Monero pools.

There's nothing wrong with moneropools.com, it just makes requests to pool servers to gather statistics.

Please could you try http://preview.moneropools.com/ and tell me if that gets blocked by Avast too? All of the data is gathered centrally instead of being polled from all of the pools to reduce load (and hopefully get around the annoying firewalls).

**Comment by mattcode55** [comment]
+invalid

**Comment by ThibaultJanBeyer** [comment]
yes, I can reach http://preview.moneropools.com/ .
Yes, it’s a better approach like that anyways.

**Comment by mattcode55** [comment]
>Please use that link instead of the other one.

No need to update the link, moneropools.com will be updated with the new site "Soon™" 👍

**Comment by ThibaultJanBeyer** [comment]
Ok then let’s close this
