### ISSUE TITLE
Add Printing Company: Ink Rebels

### ISSUE THREAD

**Issue by InkRebels** [monero-project/monero-site#497]
Hello Monero community!

I finally convinced our CEO to accept Monero on our new printing storefront: I invested a small amount early and have been dying to get involved with the community - I figured this was the best way! 

I would be honored if you could add: https://ink-rebels.com

We have successfully integrated the Globee payment gateway and are an established printing company - we hope to bring high-quality, affordable printing to the Monero marketplace!

Many thanks in advance,
Gradivis

**Comment by erciccione** [comment]
+merchant

Spreading the word and facilitating the mass adoption is a very good way to get involved, thank you!
Added in #498

**Comment by MaxXor** [comment]
Just a general tip: your website got huge images which take like ~5sec to load. Images can be reduced in size by optimizing them for web without losing lots of quality.

**Comment by InkRebels** [comment]
Whoops - slipped in a couple of images intended for our print ads. 300dpi files on the front page of a printing website...don't tell my colleagues, I won't hear the end of it! Thanks!
