### ISSUE TITLE
Add Merchant: Hammock Universe - Now fully integrated with Globee

### ISSUE THREAD

**Issue by johnking7** [monero-project/monero-site#499]
Please add the following new merchant to the Goods section.

New Merchant: [Hammock Universe USA](https://www.hammockuniverseusa.com)

Product: Hammocks, Hammock Chairs, Hammock Stands & Accessories

Background: Trading since 2001. I've been working with the company since 2015. Good team and good products from my experience.

Monero Integration Info: Site uses Shopify, so we have integrated the GloBee app, and that's now live.

**Comment by erciccione** [comment]
+merchant

Added in #498
