### ISSUE TITLE
Menu doesn't work with JS disabled

### ISSUE THREAD

**Issue by fluffypony** [monero-project/monero-site#5]
Bootstrap dropdown button menu should work with JS disabled, but it doesn't. @SkepticalHippo is looking at this, options are basically:
1. Replace the entire menu with a pure CSS variant
2. Have pure CSS handlers as a fallback in <noscript> tags

**Comment by rehrar** [comment]
@fluffypony Close this issue. Website redesigned and everything works without JS since there is none.
