### ISSUE TITLE
torrent magnet link?

### ISSUE THREAD

**Issue by phloatingman** [monero-project/monero-site#508]
Any plans on having a torrent magnet link as an option to download the gui and cli?

**Comment by erciccione** [comment]
+feature

**Comment by QuickBASIC** [comment]
Generally the slow part isn't the download it's the verification. Importing the blockchain with verification set to true can be a very slow process... I'm not sure we want to encourage people to download and import a blockchain any other way than a direct download from the site. (I believe Fluffy updates the blockchain.raw direct download at the moment.) I'm afraid some might be tempted to use verify=0 to make the import faster and have possibly compromised data.

The blockchain changes each block and while conceivably we could add SHA256 hashes and GPG sign it say once a month, people aren't good at checking hashes against downloads anyway.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
