### ISSUE TITLE
Add my EComm Store to Site

### ISSUE THREAD

**Issue by johngrefe** [monero-project/monero-site#513]
Type: Physical Goods
Products: E-Cigarrete products, designed and manufactured by Congrevape (I am the designer, John Grefe)
Site Address: https://Congrevape.com/shop
Monero Integration Status: Completed and transactions tested live
Perk for using Monero: 25% Discount on entire order
Give Back to community: Fully hosted Node to add support to network

+merchant

**Comment by erciccione** [comment]
+merchant
+in progress

Added in #517
