### ISSUE TITLE
Add all the recent artists through GloBee to the list

### ISSUE THREAD

**Issue by snirp** [monero-project/monero-site#516]
Some 50 artists were recently added. It seem like none have made the list.

**Comment by ordtrogen** [comment]
Just curious, what artists are you referring to? Have a link?

**Comment by snirp** [comment]
https://www.reddit.com/r/Monero/comments/7hore1/project_coral_reef_furthering_mainstream_adoption/

**Comment by erciccione** [comment]
+in progress
+merchant

https://github.com/monero-project/monero-site/pull/494

**Comment by erciccione** [comment]
+resolved

In #523
