### ISSUE TITLE
How can we become your reseller in India?

### ISSUE THREAD

**Issue by manmeetsanghera** [monero-project/monero-site#518]
We would like to become your reseller in India so that Indian can buy Monero easily.

**Comment by mattcode55** [comment]
Just like Bitcoin, Monero has no central authority to issue you coins to sell. [There are a list of exchanges on getmonero.org that will sell you Monero which you can resell](https://getmonero.org/community/merchants/), [you could mine Monero and sell it](https://getmonero.org/get-started/mining/) or you could obtain it some other way.

+invalid
+resolved
