### ISSUE TITLE
Merchant Add: Services

### ISSUE THREAD

**Issue by luechtefeld** [monero-project/monero-site#533]
Please add to Services: "Ray Luechtefeld, PhD, Leadership & Team Coaching and Development" linked to https://clarity.fm/rayluechtefeld

**Comment by mattcode55** [comment]
I don't see anywhere on your page that says you accept Monero, would you 
be able to add that? :)

+merchant

**Comment by erciccione** [comment]
Added in #530 

+in progress

**Comment by luechtefeld** [comment]
I have added that I accept Monero.
