### ISSUE TITLE
Add label 'Uses converter' for merchants in our list who don't directly accept Monero

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#534]
Some merchants in our list use external converters that usually work with bitcoin (like shapeshift, coinpayments, changelly etc..). That means an user must send money to a third part when making a transaction with the vendor. The resulting transaction didn't happen completely inside the Monero network, making the exchange of money between parts not completely private, since this "mediators" can log valuable informations.

The user should be aware of this when choosing a merchant, an [Uses Converter] label on the side of the merchant's name easily notify this and push vendors to adopt Monero directly.

**Comment by erciccione** [comment]
+low priority
+improvement

**Comment by bill-mcgonigle** [comment]
I happen to take Monero directly on my site, but if I were taking it via a converter that only provided me with a reusable address, how would anybody know (aside from asking the merchant to make said declaration).  I just want to be careful no guarantees are being implied here that aren't certain.

**Comment by erciccione** [comment]
As @bill-mcgonigle explained, this is very hard to implement and verify, closing this issue for now.
