### ISSUE TITLE
https://getmonero.org/knowledge-base/projects = 404 error

### ISSUE THREAD

**Issue by dewdeded** [monero-project/monero-site#535]
https://getmonero.org/knowledge-base/projects = 404 error

**Comment by rehrar** [comment]
This page is no longer a thing, but it should redirect elsewhere, I agree.

**Comment by rehrar** [comment]
@fluffypony can you set up a redirect for this page? There's no equivalent page (maybe Merchants is most similar?). Probably going back to the home page of the site is the best way to go.

**Comment by fluffypony** [comment]
@rehrar do it in the nginx.conf in _config and I'll pull it in

**Comment by dewdeded** [comment]
bonus: https://forum.getmonero.org/22/completed-tasks/87652/hire-phd-mathematician-to-look-into-post-quantum-crypto-zk-protocols-blockchain-bloat ==
"Whoops, looks like something went wrong."
