### ISSUE TITLE
Please Add Ablative Hosting to the Merchants Page

### ISSUE THREAD

**Issue by BrassHornComms** [monero-project/monero-site#541]
Hello,

[Ablative Hosting](https://ablative.hosting) is a startup UK Web Hosting company _(Company registered in England and Wales no. 10602465 )_ that specialises in dual homing websites on the clearnet and as a Tor Project .onion 'Hidden Service'.

As part of it's commitment to preserving anonymity (e.g. https://ablative.hosting/multi-hop-onion-hosting/ or https://ablative.hosting/faq/ ) Ablative [has announced today that they will be accepting Monero](https://twitter.com/AblativeHosting/status/950358935113932800)

_(on behalf of Ablative Hosting)_

**Comment by mattcode55** [comment]
Looks great! Should get added whenever PR #542 gets merged.

+merchant

**Comment by BrassHornComms** [comment]
Excellent, thank you.
