### ISSUE TITLE
adding inst.us to the merchants accepting Monero

### ISSUE THREAD

**Issue by johnsonek** [monero-project/monero-site#544]
Hi,
as Monero is my favourite crypto which I promote (and sometimes mine) on every occasion since May 2017, I've decided to accept it (and only it from cryptos) as a payment for my services. 
The first one concerns support in getting real followers on Instagram: http://inst.us/
Its name: INST.US.
I would like it to be listed at Merchants & Services site.
Great work, guys!
Kind regards,
johnsonek

**Comment by mattcode55** [comment]
Looks good :)

Should get added whenever PR #545 gets merged.

+merchant

**Comment by johnsonek** [comment]
Thank You :)
I keep my fingers crossed for Monero (greater) success and I hope I may contribute to that ;)
