### ISSUE TITLE
Add  Jeffscondos.com Vacation Rentals as Merchant

### ISSUE THREAD

**Issue by jeffscondos1** [monero-project/monero-site#549]
Can you please add Jeffscondos.com to your list of merchants under Travel & Lodging.
Please let us know what additional information is needed.

Thanks

Jeffscondos

**Comment by mattcode55** [comment]
Looks great! However I don't see Monero mentioned anywhere on your site 
:(, only Centra, DASH, BTC, ETH and LTC.

+merchant

**Comment by erciccione** [comment]
Please add a reference to Monero on your website. 
Added in #551 

+in progress

**Comment by jeffscondos1** [comment]
Monero I there, is there also  link you would like me to attach to the image?
Thank you, Jeff Rose 919-469-3254   You can TEXT ME NOW AT 9193895806www.JeffsCondos.com - Myrtle Beach & Disney World RESORT  Vacation Rentals =

**Comment by jeffscondos1** [comment]
Monero I there, is there also  link you would like me to attach to the image?
Thank you, Jeff Rose 919-469-3254   You can TEXT ME NOW AT 9193895806www.JeffsCondos.com - Myrtle Beach & Disney World RESORT  Vacation Rentals =

**Comment by SamsungGalaxyPlayer** [comment]
@erciccione now includes a Monero logo on the site

**Comment by erciccione** [comment]
thanks @SamsungGalaxyPlayer, don't know what happened up there :p
