### ISSUE TITLE
Typo on technical specs

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-site#554]
https://getmonero.org/resources/technical-specs/

then --> than

![skarmklipp](https://user-images.githubusercontent.com/15184875/34930380-7b6199e6-f9c9-11e7-89de-79b79730b1fb.PNG)

**Comment by leonklingele** [comment]
Hi @ordtrogen, it's quite easy to fix typos on Github, even without using any kind of command line interface. I've created a little tutorial on how I created the fix: https://giant.gfycat.com/SpicyMinorHeifer.webm

**Comment by erciccione** [comment]
+grammar
+in progress

**Comment by ordtrogen** [comment]
Thanks @leonklingele 

I know the process you're showing but have always done it by cloning my fork to my local machine and editing it there. This time I was at work when I caught the typo and didn't have that opportunity.

Thanks to your example, I'm now aware simple edits can be done through the web interface!
I'll try to find another typo to hone my skills on :-)

Your video would be very useful in general. Maybe it (or something like it) could be incorporated into some Guide/knowledgebase to encourage more people to fix small issues they find? @erciccione  ?

**Comment by erciccione** [comment]
@ordtrogen that's actually a very good idea
@leonklingele what do you think about making some how-to-contribute mini-guides ? This coiuld be very helpful for non techy people who would like to contribute and are scared of git/github

**Comment by leonklingele** [comment]
@erciccione indeed, that would be awesome. I have other priorities at the moment but am willing to help asap. This is now tracked in https://github.com/monero-project/monero-site/issues/567.

**Comment by rehrar** [comment]
+resolved
