### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero-site#558]
.. for obvious reasons. Not that mostly everyone isn't already using a proper adblocker, it should be done for the sake of our ideology, to give a statement.

Here are some examples of what _could_ be done by a 3rd party on your website (if the script is not src'ed via [SRI — Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)):

- Modify content (e.g. adjust / add donation addresses)
- Censorship
- Tracking. You're feeding the biggest tracking company with even more data and help them to create a fine-grained user profile
- Redirect to other websites
- Execute arbitrary JavaScript to e.g. enable the camera (ask for permissions first), use geolocation, run crypto miners
- .. complete takeover

Also see https://github.com/mymonero/mymonero-app-js/issues/143 which nobody did reply to nor remove the spyware so far.

I guess this is @fluffypony 

There are some self-hosted, open source analytic services available. I'm not an expert but a lot of people are using Piwik (now known under the name »Matomo«).

__EDIT__:
Forgot to mention the most obvious reason: Tracking.

__EDIT 2__:
Why does there even have to be any kind of tracking? What do you currently do with the analytics data? How does it help you / the project?

**Comment by erciccione** [comment]
Hi we already agreed all referral should be removed from the website, you can find the discussion in #546 

+in progress

**Comment by rehrar** [comment]
I too think Piwik/Matomo would be a better alternative, although some might argue this gives the Core Team control over a large amount of data on users.

**Comment by mattcode55** [comment]
Could the data from Piwik/Matomo be made public?

**Comment by philiparthurmoore** [comment]
Coming in on this a little late, but I'm here because I also was curious why tracking is on your site. Question: is the only official Monero site https://getmonero.org/ or do you also own https://monero.org/? The tracking on both sites bothers me for somewhat obvious reasons. :-)

**Comment by philiparthurmoore** [comment]
@rehrar Thank you very much for the heads up about monero.org, as well as the tracking issue.

**Comment by rehrar** [comment]
@leonklingele @philiparthurmoore @mattcode55 @erciccione 

#680 is ready for review and merge
