### ISSUE TITLE
Crypto Kingdom synopsis and links for External Project's page

### ISSUE THREAD

**Issue by generalizethis** [monero-project/monero-site#56]
# CRYPTO KINGDOM

Crypto Kingdom is MMORPG with a real-world economy. You can make trades, start an in-game company or develop real estate on your path to becoming a land baron. And when you're done building your empire, you can sit back, pour a beer and chat with your friends. It's Second Life, Wall Street and social networking rolled into one game.

[Crypto Kingdom](http://cryptokingdom.me/)
[Bitcointalk](https://bitcointalk.org/index.php?topic=819073.0)
[Reddit](https://www.reddit.com/r/cryptokingdom/)

**Comment by rehrar** [comment]
@generalizethis let's go ahead and close this issue.
