### ISSUE TITLE
»How to contribute?« mini guide series

### ISSUE THREAD

**Issue by leonklingele** [monero-project/monero-site#567]
It would be quite helpful to create some animated mini guides (something similar to https://github.com/monero-project/monero-site/issues/554#issuecomment-357645259) to get more people into contributing to the project, especially those new to programming / Git.

Let's use this issue to track possible ideas.

- __How to fix a typo?__
- __How to add & update translations?__
- __How to help by testing new pull requests?__

**Comment by erciccione** [comment]
+guide

**Comment by mattcode55** [comment]
I think that the README of this project is quite good. Maybe short videos could be made of everything it includes?

**Comment by rehrar** [comment]
We have just soft-launched media.getmonero.org @erciccione @mattcode55 and @leonklingele. A place where we can get videos of these things in one place for people to look.

Please feel free to make something about how to do anything and everything on the site and upload it. .mp4 files only for now.

**Comment by serhack** [comment]
@uncagedpotential yes, Mastering Monero goal is approaching people to the Monero world, especially developers.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
