### ISSUE TITLE
Add Kidsweet to Merchants Page

### ISSUE THREAD

**Issue by bill-mcgonigle** [monero-project/monero-site#573]
Hi!
Please add Kidsweet to the Merchants page:  

Kidsweet - All-Natural Zero-Calorie Sweetener
https://www.kidsweet.com

We take Monero directly.  Our crypto page is at:
https://www.kidsweet.com/crypto/

Thanks!

**Comment by mattcode55** [comment]
Hi, it should get added to the merchants list when PR #576 gets merged :)

**Comment by erciccione** [comment]
+merchant
+in progress
