### ISSUE TITLE
Please add Rohan Law to those business accepting Monero

### ISSUE THREAD

**Issue by RohanLaw** [monero-project/monero-site#577]
Criminal defense firm in Atlanta, Georgia USA accepting Monero for Payment of services to defend clients in maters pending in the State of Georgia.  www.rohan.law

**Comment by erciccione** [comment]
Hello! thanks, your service was added in #579 

+merchant
+in progress

**Comment by RohanLaw** [comment]
Updated Monero wallet address for business payments…
monero: 49qAa59VfVn7eZksq7CWm6TeiiC152S2MT6cbt7vV3VYXk5vVg4uPhuLE5sKvt1E13CFpDGcbEFXWi6VNf3Eoq8h3ngxTyT

Kind regards,
Douglas Brooks Rohan,   		Esq. 	
Tu mejor opción legal  	
	
t.	(404) 923-0446 
e.	doug@rohan.law <mailto:doug@rohan.law> 
w.	www.rohan.law <http://www.rohan.law/> 
s.	375 Northridge Road, Suite 120, Atlanta, GA 30350 
 <https://www.facebook.com/RohanLawPC>		 <https://www.facebook.com/AbogadoRohan/>		 <https://twitter.com/RohanLawPC>		 <https://twitter.com/AbogadoRohan>		 <https://www.instagram.com/explore/locations/163770873671772/rohan-law-pc-injuries-criminal-defense/>		 <http://instagram.com/abogadorohan>		 <https://www.linkedin.com/company/rohan-law-pc/>		 <https://www.youtube.com/channel/UCkLVYgh-EblFl9zykZ5nNww>	
		 <https://www.avvo.com/attorneys/30341-ga-douglas-rohan-502591.html>
