### ISSUE TITLE
Please add Loja do Cabelo as a business/merchant accepting XMR for goods

### ISSUE THREAD

**Issue by rmbb** [monero-project/monero-site#581]
Loja do Cabelo is a Portuguese online store in a niche market dealing with Virgin Human Hair in bulk and human hair extensions. 
Site is in Portuguese but we support English through e-mail, Facebook messenger and instagram messages. We ship worldwide registered mail or FedEx.

https://lojadocabelo.com

**Comment by erciccione** [comment]
Hi. Added in #579 

+merchant
+in progress
