### ISSUE TITLE
Please add MetaDope as a merchant & service accepting XMR

### ISSUE THREAD

**Issue by ametadope** [monero-project/monero-site#582]
We now accept XMR. We offer patch & lapel pin manufacturing services, and we sell our own goods as a brand (patches, lapel pins, clothing, accessories). www.patchcult.com

Thanks!

**Comment by erciccione** [comment]
Hi, can you add somwhere in the website that you accept Monero for payments? Wasn't  able to find any reference to it.
Added your business in #579 

+merchant
+in progress

**Comment by ametadope** [comment]
Done. Added to the "About" page.

**Comment by erciccione** [comment]
@ametadope Thanks!
