### ISSUE TITLE
Please add FRANC VILA as a business/merchant accepting XMR

### ISSUE THREAD

**Issue by FVl12** [monero-project/monero-site#585]
FRANC VILA is a Swiss independent brand of fine Watchmaking and Jewelry.
The company is based in the canton of Geneva. 

Our speciality is customized jewelery for our clients in pure precious metals: Gold, Silver or Platinum. All our products are guaranteed SWISS MADE and are accompanied by certificates of materials

More Informations:
http://www.francvila.com
Mail: info@francvila.ch

Our store:
Boutique Franc Vila
Quai du Mont Blanc 21
1201 Genève
Phone: +41 22 731 88 08

**Comment by erciccione** [comment]
Hi! thank you for the accurate description. Added in #579 

+merchant
+in progress
