### ISSUE TITLE
Could you please add onestopny.com as a merchant on your site

### ISSUE THREAD

**Issue by dannyoh726** [monero-project/monero-site#596]
Looking to add our services to monero. We do development and production in fashion for high end women's and men's clothing. Any designers looking to create their own line or even people wanting to custom make their own clothing can contact us.

Thanks!

**Comment by erciccione** [comment]
Couldn't find any reference to Monero in your website. Do you already accept it as form of payment or are you going to do it in the future?

+merchant

**Comment by dannyoh726** [comment]
Oh i don't have any reference was expecting any interested parties to call in. Is there some kind of standard seal or something that other merchants use to show they accept monero?

**Comment by rehrar** [comment]
Something like this? https://www.themonera.art/2017/09/22/monero-promotional-graphics-badges-and-stickers-for-websites/

**Comment by dannyoh726** [comment]
Thanks added it to the footer of our all our webpages.

**Comment by erciccione** [comment]
Thank you. I added your website in #602 

+in progress
