### ISSUE TITLE
Proposed improvements for podcast software

### ISSUE THREAD

**Issue by davidlatapie** [monero-project/monero-site#6]
1. timer (example: I cannot understand what is said about "association by ???? problems" and I cannot link to the exact minute and second where it happens
2. time-anchoring, à la YouTube (http://youtu.be/F17_KiAZOxg?t=13m29s)

**Comment by fluffypony** [comment]
It's not our player, [libsyn](http://libsyn.com) provide it as part of their podcast hosting package, so we can't modify it.
