### ISSUE TITLE
Partnership offer

### ISSUE THREAD

**Issue by Check-coin** [monero-project/monero-site#605]
Greetings.

We want to officially introduce you to our two online stores:

-          check-coin.com

-          max5dollars.com

The shops offer a great variety of products!

-          Cell Phones
-          Cases & Leather
-          Samsung accessories
-          3D Glasses
-          Access Control
-          Measurement & Analysis Instruments
-          Professional Tools
-          Video Games Accessories
-          Keyboards & Mouse
-          Laptops
-          Laptops accessories
-          Smart Watch & Band
-          Android Tablet
-          Tablet Accessories
-          and much more…

 The online stores accepts two payment methods:

-          Paying through / PayPal

-          Paying with Cryptocurrency through  www.coinpayments.net 

Do you want to join our partners?

Best regards!

Liubomir Marinkov 
liubomirmarinkov@gmail.com

Founder of: 

check-coin.com                     
check.coin.shop@gmail.com

max5dollars.com 
max5dollars.shop@gmail.com

**Comment by erciccione** [comment]
Hi! What do you mean for join our partners? Would you like to become a [Monero sponsor](https://github.com/monero-project/monero#supporting-the-project) or you wish to be added to our merchant list?

**Comment by Check-coin** [comment]
Greetings.

I wish my sites to be added to your merchant list if possible!
If there is something I have to add to my sites you can inform me to do it!

Thanks for your time!
Best regards!

Liubomir Marinkov
liubomirmarinkov@gmail.com

Founder of:

check-coin.com
check.coin.shop@gmail.com

max5dollars.com
max5dollars.shop@gmail.com

![check-coin](https://user-images.githubusercontent.com/36534425/36739615-0798562a-1be9-11e8-8cbe-8124a0a7dd6b.png)

![max5dollars](https://user-images.githubusercontent.com/36534425/36739616-07ba296c-1be9-11e8-98da-d1cdd9a17896.png)

**Comment by erciccione** [comment]
I added your merchants in #620 
i see you show the logo of some cryptocurrencies, please add Monero. Some examples for the logo: https://www.themonera.art/2017/09/22/monero-promotional-graphics-badges-and-stickers-for-websites/

+merchant
+in progress

**Comment by Check-coin** [comment]
Greetings.

In the attached links you will see all the positions of your logo:

https://check-coin.com/
https://check-coin.com/coins-that-we-support/
https://check-coin.com/monero/

https://www.max5dollars.com/shop/
https://www.max5dollars.com/cryptocurrency/
https://www.max5dollars.com/monero/


Thanks for your time!
Best regards!

Liubomir Marinkov
liubomirmarinkov@gmail.com

Founder of:

check-coin.com
check.coin.shop@gmail.com

max5dollars.com
max5dollars.shop@gmail.com
