### ISSUE TITLE
Privacy policy doesn't exist

### ISSUE THREAD

**Issue by wgx** [monero-project/monero-site#606]
The link to privacy policy on the legal page doesn't go anywhere. As the beginning of GDPR looms, would be good to get the Monero privacy policy sorted. 👍

**Comment by mattcode55** [comment]
The privacy policy is at the bottom of the [legal page](https://getmonero.org/legal/). The old pages were removed a while ago https://github.com/monero-project/monero-site/pull/455#issuecomment-339360972.

Where did you find a link to one of the old pages?

**Comment by wgx** [comment]
@mattcode55 The legal page doesn't have a privacy policy on it, it instead has a paragraph which links to a non-existent page (with an #anchor). Please go and look: https://getmonero.org/legal/

**Comment by rehrar** [comment]
Yes, it does not link to a different page, it links to a different part of the same page. Scroll the bottom of the Legal page and you will see a Copyright segment and a Privacy Policy segment after the long Terms of Service section. 

Everything is as it should be.

**Comment by SamsungGalaxyPlayer** [comment]
@rehrar with the current version of the site, I only see the copyright section. Not the privacy policy section.

![capture](https://user-images.githubusercontent.com/12520755/36355274-5ff4d59a-14a6-11e8-9758-0135b06331c8.PNG)

**Comment by rehrar** [comment]
Check on mobile? Checking desktop.

**Comment by SamsungGalaxyPlayer** [comment]
@rehrar yes, I see it one mobile right now.

**Comment by rehrar** [comment]
Will fix.

**Comment by mattcode55** [comment]
I can see it on desktop just fine ![Screenshot](http://www.enlightenment.org/ss/e-5a89c56abe74c0.27184876.jpg)

**Comment by SamsungGalaxyPlayer** [comment]
@mattcode55 weird, I reset my cache right before viewing it :/

**Comment by rehrar** [comment]
It's too private for some to be able to see.

**Comment by mattcode55** [comment]
[I just archived the site on archive.is and I can see it there](http://archive.is/aUBrq) so it isn't a caching thing, it also is there when I use my phone. Very spooky.

**Comment by rehrar** [comment]
After a good amount of testing, I simply cannot reproduce the Privacy Policy not appearing. @wgx can you share your OS and browser? Try on another computer as well. Still the same problem? Mobile?

**Comment by wgx** [comment]
Firefox 58, MacOS 10.13

<img width="1128" alt="screen shot 2018-02-20 at 09 44 43" src="https://user-images.githubusercontent.com/930099/36417041-c293ecd6-1622-11e8-8dd6-e9436a2706b9.png">

**Comment by wgx** [comment]
@rehrar if I view source, I can see the policy is in the markup but a CSS rule is likely preventing it being shown for some reason.

**Comment by erciccione** [comment]
Is this issue still relevant?

**Comment by wgx** [comment]
Still not fixed for me - no privacy policy visible in firefox

**Comment by erciccione** [comment]
I can see it properly on Linux with Firefox 60.0.2 64-bit. Anybody else able to test this on MacOS?

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
