### ISSUE TITLE
User guide -> how to buy monero 20150920

### ISSUE THREAD

**Issue by Gingeropolous** [monero-project/monero-site#61]
http://imgur.com/a/ElVrq
# How to obtain monero

This is a guide to obtain your own Monero as of 20150919. This is perhaps the easiest way to purchase and hold Monero. 
## Step 1: Buy bitcoin

There are many ways to buy bitcoin. Perhaps the easiest way is through circle.com. Once you have purchased some bitcoin, you are ready to buy some Monero! Buying bitcoin is straightforward. Please goto circle.com and just follow the instructions there. 
## Step 2: Set up a mymonero.com account

MyMonero.com is an online wallet for Monero, maintained by Monero Core Developer Ricardo Spagni (fluffpony). It is the easiest wallet to use. Simply go to [MyMonero.com](https://mymonero.com) and click on the "Create an Account" button. 

![MyMonero!](http://imgur.com/WxFWigW.png)

After clicking the button, you will see your private key. This key is what gives you access to your funds. Never share this key with anyone! 
### WRITE DOWN THIS KEY IMMEDIATELY!

![private key](http://imgur.com/fnKPHmf.png)

Type in your private key in the box below, and click the button.

On the next page, you will see your address.

![copy address](http://imgur.com/So59m9J.png)

Copy your address to the clipboard by highlighting the whole thing and hitting ctrl+c (or edit menu, copy), or clicking the little icon next to your address. Save your address somewhere. This is how others will send Monero to you, and what you will use to deposit Monero into your account!
## Step 3: Buy monero and transfer the monero to your new address

Go to www.shapeshift.io . On the righthand side, of the screen, click icon under "Receive" to select Monero. 

![Select Monero](http://imgur.com/oc2WRQK.png)

![MONERO!](http://imgur.com/oFddOSU.png)

Paste your address into the field under the Monero logo. Select the "agree to terms" button, then hit "Start"

![Paste monero address](http://imgur.com/YPPdBpB.png)

In the new screen that pops up, copy the Deposit Address into your clipboard (select and hit ctrl+c or edit-copy)

![Copy this address](http://imgur.com/G4b6xW0.png)

Go back to your circle.com page, hit the "transfer" button, and paste the bitcoin address into the field
Enter the amount of bitcoin you would like to spend.

![Select transfer on circle.com](http://imgur.com/WZgpyrc.png)

![paste address](http://imgur.com/agDWCRm.png)

You will get a text message verification code. Enter code and hit send.

![enter code](http://imgur.com/5oLrZlM.png)

You will see the shapeshift change to "awaiting exchange"

![moneys coming](http://imgur.com/SBHRnjv.png)

Then it will change to COMPLETE!

![MONEY CAME](http://imgur.com/EH2xqvq.png)

After a while you will see it in your Monero account

![You did it. Have a cookie](http://imgur.com/6ZGtbFV.png)

**Comment by rehrar** [comment]
@Gingeropolous we can add this User Guide to the User Guide's page as shown in the README of the website. But some things will need to be updated and/or changed.

**Comment by SamsungGalaxyPlayer** [comment]
@Gingeropolous @rehrar in general, the guides on the website should not tell people to use specific unofficial wallets or exchanges. This is definitely a helpful user guide, but the place for it may be on a blog or unofficial website instead.

**Comment by anonimal** [comment]
I agree, @SamsungGalaxyPlayer.

**Comment by QuickBASIC** [comment]
@Gingeropolous @rehrar @SamsungGalaxyPlayer @anonimal I agree that we shouldn't direct people to specific non-free services. Can we close this issue?

**Comment by QuickBASIC** [comment]
We seem to be in agreement, that the user guide needs to be updated to not send people to specific services (the `Using` page directs them to the exchanges on the merchants page at the moment, which may be sufficient). Closing this issue for now.

+stale
+resolved
