### ISSUE TITLE
Please add this function monero calculator to merchants

### ISSUE THREAD

**Issue by arizona77** [monero-project/monero-site#616]
Hi. Can you add this link to your monero merchants? http://atomox.net/1/XMR/USD you can convert monero amount for amount of another coins or USD,GBP etc. It's useful real-time calculator. Thank you.

**Comment by erciccione** [comment]
I'm having troubles using the website. Is it up and running correctly?

**Comment by arizona77** [comment]
Yep, there was one issue. All works now right, check and add :) thank you

**Comment by erciccione** [comment]
Now looks ok. Added in #620 

+merchant
+in progress
