### ISSUE TITLE
Links to 0.0.7.226 in "Latest News" at index

### ISSUE THREAD

**Issue by rgtk** [monero-project/monero-site#617]
1. Go to https://getmonero.org/
2. Scroll to "Latest News" section visible on the right.
3. Links to news targets `0.0.7.266` instead of `getmonero.org` (eg. https://0.0.7.226/02/11/PoW-change-and-key-reuse.html)

**Comment by erciccione** [comment]
+bug
+in progress

**Comment by rehrar** [comment]
+resolved
