### ISSUE TITLE
Add URL to Merchants & Services page

### ISSUE THREAD

**Issue by pierrek87** [monero-project/monero-site#622]
Hi,

We do now accept Monero as payment!

I would like to highlight that https://www.webbdo.se/webbhotell/ (Swedish site) do accept Monero as payment for hosting and domains.

Could it be added to https://getmonero.org/community/merchants/ ?

Best Regards
Pierre

**Comment by mattcode55** [comment]
Should get added to the site when #623 gets merged :)

+in progress
+merchant

**Comment by pierrek87** [comment]
Appreciate it!
