### ISSUE TITLE
Business listing request

### ISSUE THREAD

**Issue by dpowert2** [monero-project/monero-site#643]
Hi there,

My company makes an email client called Hiri. We now accepts Monero! I would appreciate it if you could list us on the following page:
https://getmonero.org/community/merchants/

You can buy Hiri using Monero here:
https://www.hiri.com/crypto/currency/XMR/

Cheers!
Dave
Founder
@hiri

**Comment by erciccione** [comment]
Hi. Added your service in #645 

+merchant
+in progress
