### ISSUE TITLE
Add Bitsler to Merchants page

### ISSUE THREAD

**Issue by GustavoBitsler** [monero-project/monero-site#648]
Hello Monero Team,

We would like to inform you that Bitsler, which is an online Casino, has added Monero today.

We are currently one of the biggest Dice websites using cryptocurrencies and with over 2 years of existence we have built a fun and entertained community around it. We have millions of players accounts and we will reach our 24th billionth bet very soon! 

It would be great for us and for your community to let them know that they will have a new place where they can use Monero. We would love to be listed on your website.

![monero_launched_banner](https://user-images.githubusercontent.com/37350123/37370279-9499af4a-2703-11e8-86f5-612a4c22e096.png)

Hope to hear from you soon! 

Regards,
Gustavo, Bitsler.com

**Comment by erciccione** [comment]
Hi, i added your website in #650 . Please check everything is correct. Thanks

+merchant
+in progress
