### ISSUE TITLE
User guide still refers to "mixin" (deprecated, right?)

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-site#651]
On

https://getmonero.org/resources/user-guides/monero-wallet-cli.html

the transfer command is described as 
"transfer MIXIN ADDRESS AMOUNT"
but as I understand "mixin" is now called "ring size" since 0.11?

I don't know if it's enough to just s/mixin/ring size on the page.

**Comment by erciccione** [comment]
ring size = mixin + 1
So yeah, it definitely needs to be corrected. Thanks for spotting it, i guess all user guides need to be reviewed, we got some massive updates lately

**Comment by erciccione** [comment]
+in progress
