### ISSUE TITLE
Map Decor Web Site Accepts Monero as Payment

### ISSUE THREAD

**Issue by Cactii1** [monero-project/monero-site#652]
Hello,

I just wanted to see if this web site: http://www.CityMapDecor.com could be added to the merchants list on the GetMonero.org web site. It's a web site that specializes in city map themed home decor.

Please and thanks!

**Comment by erciccione** [comment]
Hi! Are you the owner of this business? if not, are you sure they wish to be listed on our merchants list?

+merchant

**Comment by Cactii1** [comment]
I am the owner, yes.

**Comment by erciccione** [comment]
Added in #653 
Thank you!

+inprogress

**Comment by Cactii1** [comment]
Thank you.

**Comment by erciccione** [comment]
No problem

+in progress
