### ISSUE TITLE
Add Cake Wallet for iOS to Downloads section?

### ISSUE THREAD

**Issue by loganmarchione** [monero-project/monero-site#681]
Should [Cake Wallet](https://www.cakewallet.io/) by @fotolockr for iOS be added to the [Mobile/Light](https://getmonero.org/downloads/#mobilelight) Downloads section?
The source is on [Github](https://github.com/fotolockr/CakeWallet) and the developer is active on Github and [reddit](https://www.reddit.com/user/pinkphloid/posts/). However, you're putting your trust in the fact that the file uploaded to Apple is the same as the source on Github.

**Comment by SamsungGalaxyPlayer** [comment]
We could link the Github page directly if this is a concern.

The application has been around for a while and has received positive reception from [several](https://www.reddit.com/r/Monero/comments/83nu7u/cake_wallet_my_thoughts/) [longtime](https://www.reddit.com/r/Monero/comments/8b7ha6/say_hi_to_the_monero_ecosystem_project_a/dx4op3i/?context=10000) community members.

While these should not be treated as comprehensive audits, the application seems to have received a similar amount of scrutiny as Monerujo.

It's concerning that Apple doesn't allow people to run build apps like you can do with android .apks, but someone with an Apple developer account can run from their own builds from source iirc.

**Comment by loganmarchione** [comment]
@SamsungGalaxyPlayer, I agree that the Github link is a good idea. iOS users are definitely looking for a mobile app and this fills that position.

I don't have an Apple developer account but believe you are correct.

**Comment by fotolockr** [comment]
Hi All, 

Thank you for the comments. Yes, we think it should be listed there.  Our app has been reviewed by user John_alan.    A link to Github AND a link to the App Store or our website for less sophisticated users would good.

**Comment by cake-tech** [comment]
By the way, we will be moving this repo to our official Cake Technologies account within Github shortly.  Will keep all posted.

**Comment by erciccione** [comment]
+resolved
