### ISSUE TITLE
Polski 404 not found

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#686]
Hi guys.

I'm getting a 404 not found when trying polski translation. At least on index and user guides pages.
@erciccione @rehrar did you notice?

**Comment by el00ruobuob** [comment]
It's not on user guides pages but on user guide head page

**Comment by el00ruobuob** [comment]
Also download, about, tech-specs pages...

**Comment by erciccione** [comment]
@el00ruobuob This was fixed by #682. Everything will show correctly once the server will be updated

**Comment by el00ruobuob** [comment]
Sorry for the disturb.
