### ISSUE TITLE
Create API to get funding information from getmonero forum

### ISSUE THREAD

**Issue by onodera-punpun** [monero-project/monero-site#689]
I'm working on a self-hosted web wallet for monero. I'd like to display the projects that have been funded or required funding with some information like the amount required, the current amount funded, the amount of donations.

At the moment I'm using a web-scraper to obtain this information, which is kind of hacky. An API to easily get this information in JSON or something would be really great :).

**Comment by erciccione** [comment]
The forum will be completely refactored soon, but this is actually a good idea. Let's keep this issue open for when the new forum will be ready

+enhancement

**Comment by erciccione** [comment]
ehm ehm... the "enhancement" label doesn't exist on this repo

+feature
