### ISSUE TITLE
Document subaddress RPC calls

### ISSUE THREAD

**Issue by coneiric** [monero-project/monero-site#694]
Subaddresses have now been merged into master via [monero-project/monero#2056](https://github.com/monero-project/monero/pull/2056)

Any RPC calls that have been created to support this feature should be documented in the [wallet-rpc.md](https://github.com/monero-project/monero-site/blob/master/resources/developer-guides/wallet-rpc.md) file.

**Comment by erciccione** [comment]
+improvement
+in progress

**Comment by erciccione** [comment]
Resolved by #702 

+resolved
