### ISSUE TITLE
Moneropedia localization

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#700]
Hi everyone,

I wonder how Moneropedia works, so that i could work on the localization correctly.
First, i can see that links to moneropedia articles are done with \"\@article-name\" and shows as \"\@article name\". I'm i correct?
On each article, the Entry is the title (as shown in the index and article), and to me the terms seems to be what is looked up by the script to generate the links. I'm i correct?

So the terms should be always \"minus\", \"dash\" or `\"hippen\" joined? as in \"unlock-time\" for instance? I'm i correct?

Thanks for clarifications.

**Comment by el00ruobuob** [comment]
+moneropedia
+question

**Comment by el00ruobuob** [comment]
Any clue @rehrar and @erciccione ?

**Comment by el00ruobuob** [comment]
And should we keep the original terms for upward compatibility? (i mean if a new guide is added, which refer to the term in english...)

**Comment by erciccione** [comment]
@el00ruobuob Avoid the translations of the moneropedia for now. We need to fix the script who manage that part, because all links in the new translations will result broken (and would be necessary to fix them one by one)

**Comment by el00ruobuob** [comment]
Ok, i put it in standby for the moment.
However, when doing this script fix, please consider having apostrophes in the items, like in \"\@clef-d\'audit\" for \"\@view-key\"

**Comment by erciccione** [comment]
We still need to find a rubyst able to fix that

+bug

**Comment by el00ruobuob** [comment]
I'm not a rubyist, but after diving into the script, and thinking, rethinking, overthinking, i am testing something.
I do not say it will work for sure, but at least my new ruby script does not crash and site is building.

**Comment by el00ruobuob** [comment]
first tests are satisfying...

**Comment by el00ruobuob** [comment]
I respond to my OP:

- The terms **must** be hyphened, always
- The english terms **must** be kept before adding the localized terms

**Comment by el00ruobuob** [comment]
to be put +inprogress @erciccione

**Comment by el00ruobuob** [comment]
This could be closed

**Comment by el00ruobuob** [comment]
Fixed
