### ISSUE TITLE
Daemon RPC outdated

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#709]
Daemon RPC is out of date, it's obvious to everyone.

I propose to update it, using the files in monero/src/rpc as a reference.

**Comment by el00ruobuob** [comment]
I'll start by adding all the missing calls and options, and will try to comment them when possible.

**Comment by el00ruobuob** [comment]
+guide

**Comment by erciccione** [comment]
+improvement
+in progress

**Comment by erciccione** [comment]
+resolved
