### ISSUE TITLE
Request for merchants & exchanges

### ISSUE THREAD

**Issue by SimpleSwap** [monero-project/monero-site#719]
We would like to add SimpleSwap to your exchanges list on the page: https://getmonero.org/community/merchants/

Kindly use the following link: https://simpleswap.io?utm_source=xmr&utm_medium=link&utm_term=xmr&utm_campaign=link_xmr_website

Also we are already in dialogue with the Monero community in Reddit: https://redd.it/8dh5vw

In case of any questions don't hesitate to contact me: hello@simpleswap.io

**Comment by erciccione** [comment]
Hi @SimpleSwap , i can add your exchanges to the list, but not the referral link (for privacy reasons). Is it ok for you if we just use https://simpleswap.io? 

+merchant

**Comment by SimpleSwap** [comment]
Hi @erciccione , of course, if this affects your privacy policy you can use a simple link: https://simpleswap.io

**Comment by erciccione** [comment]
Perfect. I added your exchange to #721 
Thank you :)

+in progress

**Comment by SimpleSwap** [comment]
@erciccione,  thank you
