### ISSUE TITLE
Request to add us to the merchants page

### ISSUE THREAD

**Issue by snelcom** [monero-project/monero-site#720]
We are an dedicated and VPS hosting company and we also accept monero

 as a payment method, can you add us to the list?

Snel.com delivers fast, simple and smart Dedicated and VPS hosting services with a focus on great customer experience.The simplicity of our services and treating customers as friends sets us apart from the competition. 

![logo_150x56](https://user-images.githubusercontent.com/35103205/39623950-a621056c-4f97-11e8-8e38-052e88ee7435.png)

**Comment by erciccione** [comment]
Hi @snelcom I added you service to #721 
I see you have a 'bitcoin accepted' badge. Would be very nice to see also a Monero one on your website. You can find some cool badges here: https://www.themonera.art/2017/09/22/monero-promotional-graphics-badges-and-stickers-for-websites/
Thank you!

+merchant
+in progress
