### ISSUE TITLE
Request To Be Listed As A Monero Merchant

### ISSUE THREAD

**Issue by TheBitAdviser** [monero-project/monero-site#726]
I would like for my eCommerce shop, [cryptoclothing.org](https://cryptoclothing.org), to be listed as an official merchant which accepts Monero as payment on [this list](https://getmonero.org/community/merchants/).

[Crypto Clothing](https://cryptoclothing.org/) has been operational for nearly 1 year and has been accepting Monero since its creation. If there are questions/comments please let me know.

Thank You

**Comment by el00ruobuob** [comment]
I'm on it.

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by erciccione** [comment]
+resolved
