### ISSUE TITLE
Monero accepted for cufflinks at urbandetail.com.au 

### ISSUE THREAD

**Issue by activillain** [monero-project/monero-site#727]
urbandetail.com.au sells high quality cufflinks. Monero is an accepted currency on checkout. 

Requesting it to be listed!

**Comment by el00ruobuob** [comment]
I'm on it

**Comment by el00ruobuob** [comment]
You'r monero logo at the botom of the page has issues:
![image](https://user-images.githubusercontent.com/37215310/39753267-7785c506-52be-11e8-8273-67efe9e60933.png)

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by activillain** [comment]
The issue seems to stem from the globee shopify integration. I'll follow up with globee.

**Comment by erciccione** [comment]
+resolved
