### ISSUE TITLE
Update user guides with 0.12.0.0 GUI screenshots

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [monero-project/monero-site#729]
Several guides should be updated for the latest 0.12.0.0 release.

The following need their screenshots updated:

https://getmonero.org/resources/user-guides/solo_mine_GUI.html
https://getmonero.org/resources/user-guides/remote_node_gui.html

The following need to have a section for using the GUI, including screenshots:

https://getmonero.org/resources/user-guides/view_only.html
https://getmonero.org/resources/user-guides/prove-payment.html
https://getmonero.org/resources/user-guides/restore_from_keys.html

**Comment by erciccione** [comment]
Maybe we can just point from those articles to the guide instead of create a dedicated part for the GUI? See https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/monero-GUI-guide.md

+improvement

**Comment by SamsungGalaxyPlayer** [comment]
@erciccione I suppose it depends on what sort of resource Monero should provide.

If we want to have references but use StackExchange for most things, then we can simply reference this guide.

If we want to replicate a lot of StackExchange content including common questions, I recommend we take components of the GUI guide (which is excellent btw) and include the relevant parts in these website guides.

**Comment by el00ruobuob** [comment]
Personnaly i think we should update user-guides (in a best effort way) AND add a "more official" user-guide for the GUI, based on the gui guide which must be updated (and localized) in a short timeframe (a week or two) after a new version is released.
In this way, could we enhance the screenshots from the GUI guides? I mean, we could have "gimp layers" with the numbered bullet, so we could easily localized the screenshots. otherwize have a "screenshot toolkit" with all the things ready to be pasted on new screenshots, so everything is coherent across all languages and versions.

**Comment by el00ruobuob** [comment]
View-only is ready on my side.
I'll go with restore from keys now.

Regarding the prove payments, i'll need to run as testnet or a stagenet node and make transactions between wallets to be able to document it.

**Comment by el00ruobuob** [comment]
There's also https://getmonero.org/resources/user-guides/restore_account.html to improve with the GUI part.
And https://getmonero.org/resources/user-guides/restore_from_keys.html should be moved to the Recovery section of user-guides, along with the "restore account" one.

**Comment by el00ruobuob** [comment]
Done with restore from keyx on my side. I'll continue with restore account, as i only have one screenshot to change.

**Comment by el00ruobuob** [comment]
I'm now private-testnet rich and stagenet rich.
Will do the screenshots and update the prove payment guide soon.

**Comment by el00ruobuob** [comment]
Done.

**Comment by erciccione** [comment]
Is this issue completely resolved?

**Comment by erciccione** [comment]
+resolved
