### ISSUE TITLE
Localized user-guides not using local png folders

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#735]
I was testing the #734 i made to partially close #729 and figured out the screenshots were not updated.
It was because i only updated the /_i18n/XX/ressources subfolder and not the /ressource subfolders.

So it means, our screenshots, localized or not, are not beeing used in the user guides.

That's too bad, because it make sense to have the screenshot in the right language.
I.e., i re-did most of the screenshots of #649 in #697 as the Windows UIs are displaying differently in french.

Is it a known issue @erciccione & @rehrar?

**Comment by el00ruobuob** [comment]
As a woraround, i believe you are copying the png folders each time you build the site? Couldn't it be automated by Jekyll, or any ruby script?

**Comment by el00ruobuob** [comment]
@rehrar & @luigi1111 The current build of getmonero.org is not using the localized screenshot.
Jekyll is not using the _i18n/***/png folders by himself.
Could you apply the workaround above so that readers will have their localized version of screenshots?

**Comment by el00ruobuob** [comment]
@erciccione its +improvement + in progress through #798

**Comment by erciccione** [comment]
+improvement
+in progress

**Comment by el00ruobuob** [comment]
This could be closed

**Comment by el00ruobuob** [comment]
Fixed
