### ISSUE TITLE
Add kovri channels to hangouts

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero-site#742]
https://getmonero.org/community/hangouts/

**Comment by el00ruobuob** [comment]
Shouldn't it be on kovri site?
Or will kovri site link to monero channels?

**Comment by el00ruobuob** [comment]
I'll PR something, but we'll have to wait for the multilanguage reimplementation to touch the hangout page itself.

**Comment by erciccione** [comment]
+improvement
+in progress

**Comment by el00ruobuob** [comment]
+resolved

**Comment by erciccione** [comment]
+resolved
