### ISSUE TITLE
CSS collision between roadmap and team pages

### ISSUE THREAD

**Issue by el00ruobuob** [monero-project/monero-site#750]
Since #575 has been merged, the team page has a CSS glitch:
![image](https://user-images.githubusercontent.com/37215310/40701352-e6be0700-63dd-11e8-9dd1-26184181b6bd.png)

CSS needs to be split in two for both pages to display correctly.
I'll PR a correction in the day if none has written a thing yet.

**Comment by erciccione** [comment]
+bug
+in progress

**Comment by el00ruobuob** [comment]
CSS glitch is in production...
![image](https://user-images.githubusercontent.com/37215310/41110350-7351b418-6a79-11e8-999d-949c6eceddf8.png)

@rehrar @luigi1111, could you please merge #751 (and #749 if you have time) before rebuilding the site to correct this?

**Comment by el00ruobuob** [comment]
+resolved

**Comment by erciccione** [comment]
@el00ruobuob you can just close the issue if it's resolved, only few contributor s have acces to the 'issue helper' at the moment :) 

+resolved

**Comment by el00ruobuob** [comment]
Ok. Noted
