### ISSUE TITLE
Should we translate the README?

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#753]
Talking with @rehrar and @el00ruobuob this came out as an option. It sounds like a good idea since many non english speaker would have the opportunity to contribute. In case I think the best way would be to add the translations in the same README file, but with a small Table Of Content at the top, so that contributors can choose their favourite language. The README doesn't get changed often, so shouldn't be too much a pain to keep it updated in every language.

Would this be useful or it's not perceipt as something needed at the moment? Looking for opinions

**Comment by erciccione** [comment]
+discussion
+localizations

**Comment by el00ruobuob** [comment]
I think this is a great idea. Contributions may come from non English speakers and therefore English should not be the default language it is actually.

**Comment by ProkhorZ** [comment]
How could you contribute without speaking English? Just making a pull request without communicating wouldn't work very well.

**Comment by erciccione** [comment]
@ProkhorZ I think a non-english contributor could help in many ways, like creating guides or as @el00ruobuob says, even just adding their service to the website. It's also true that it's not a short text and most of it is about actual developing, and if you don't know even just a bit of english you would be stuck soon. Let's wait some more inputs about this

**Comment by anonimal** [comment]
Referencing https://github.com/monero-project/kovri-docs/issues/47#issuecomment-393756702 (before this issue was opened) and https://github.com/monero-project/kovri-docs/issues/51.

>a small Table Of Content at the top, so that contributors can choose their favourite language.

I think this is a useful idea.

**Comment by rehrar** [comment]
This would make the README get incredibly long, especially since the English is long enough. My suggestion would be to make the README as a page in the site and link to it in the footer. Then the README in the repo can be shrunk down significantly to just copyright and licensing information with links to the site README proper in the various languages. 

This is also not dependent on the website being up, since the various localization links can point to the translated READMEs in the github code and not the site getmonero.org.

**Comment by erciccione** [comment]
>the various localization links can point to the translated READMEs in the github code and not the site getmonero.org.

At this point wouldnt be better to just have a single README here in the repo and point to the translated ones in a folder in this repo? something similar to monero-project/kovri#906
