### ISSUE TITLE
Store ECOSYSTEMS Retail  - Accepting Monero

### ISSUE THREAD

**Issue by labradorcode** [monero-project/monero-site#758]
Hi,
Please add our store to your merchants listing.  We are selling new & refurbished it equipment like pc's laptops and network stuff. 

https://store.ecosystems-group.co.uk

**Comment by erciccione** [comment]
Hi @labradorcode! I added your store in #760 

+merchant
+in progress

**Comment by el00ruobuob** [comment]
Your too fast @erciccione. I was painting all day and didn't see This!
