### ISSUE TITLE
Display descriptive titles on guide pages

### ISSUE THREAD

**Issue by ProkhorZ** [monero-project/monero-site#765]
The Developer Guides and many of the User Guides do not show at the top of the page which question they're answering. They start either without any heading, with a subheader like **Introduction** or with a summary of the question, like **Prove payments**. It's confusing that these pages don't clearly show what they're about, especially when new users are given a direct link to one of these pages to answer a question.

There is a title element which is used for the `<TITLE>` tag, but this is hardly visible in a modern tabbed browser or a mobile browser. @rehrar Could you use the same text in a visible `<H1>` or `<H2>` tag at the top of each page?

Such a change is conveniently beyond my capabilities, but I guess I could clean up any duplicate titles that resulted from this.

**Comment by el00ruobuob** [comment]
It could be usefull. That's something to add into the layout i believe, as it is done for blog posts. I could try to look at this later.

**Comment by rehrar** [comment]
This will require a separate layout. I'll work on making it happen.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's still relevant.
