### ISSUE TITLE
Description of IRC channes in 'Hangouts' page not translatable

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#768]
It's not possibe to transate the descriptions of the IRC channes. At the current state, they are shown in engish for all languages.
Screenshot taken from #764 
![irc_channels](https://user-images.githubusercontent.com/28106476/41507487-db048044-723b-11e8-8b43-5694a57137b7.png)
ping @rehrar

**Comment by erciccione** [comment]
+locaizations

**Comment by el00ruobuob** [comment]
I suggest we change the IRC stuff to include them in the localized yaml, like i did with library page on #772 
The inconvenient here is that yaml files should be regularly checked for inconsistency.

Would you like me to code it?

**Comment by erciccione** [comment]
Sounds like a great idea. If you want to work on it would be great, thanks :)

**Comment by el00ruobuob** [comment]
Enjoy!
![image](https://user-images.githubusercontent.com/37215310/41800662-c66ce1fa-7676-11e8-8646-7c13b6bc48e6.png)

**Comment by erciccione** [comment]
that was quick. Thanks @el00ruobuob

**Comment by erciccione** [comment]
thanks @el00ruobuob  :)
