### ISSUE TITLE
Downloads page should be more clear

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-site#770]
The download page can be quite ambiguous for new users as it does not make reference to a wallet anywhere on the page in relation to the GUI and CLI applications. 

I know the GUI and CLI are much more than wallets but majortiy of users who visit this site, well I would presume, are there to download a monero wallet. 

An example of a minor improvement:
The links to download such as 'Windows, 64-bit' should say 'Windows, 64-bit Graphic User Interface.' As well as specify that this application can be used as a wallet somewhere.

**Comment by el00ruobuob** [comment]
I don't see the benefit of adding "Graphic User Interface". By oposition, the CLI is reference as "Command-Line tool only". So the average user should not want to download this one and will choose the "Windows, 64-bits".
However, i do agree regarding adding the wallet term somewhere, maybe in the header, just below Download:
> Below is a list of applications containing both the Monero core application, and the wallet you will use to manage your monero accounts. You can either choose the Graphical application, or the command-line tools only. See [using](https://getmonero.org/get-started/using/) page for basic concept, and the [GUI guide](https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/monero-GUI-guide.md) for detailed informations.

**Comment by Electricsheep01** [comment]
Well it simply gives more clarity. A a link saying 'Windows 64-bits' does not indicate what so ever what you are downloading it should say 'Windows, 64-bit Graphic User Interface.' 

People just want a wallet, if you had no idea what CLI or a GUI even was and you visited the downloads page for said wallet you would have no idea what to download. 

I'd also reccomend indicating that the command-line tools are just for developers to prevent new users accidently downloading this. 

Also +1 for adding a link to a guide somewhere on this downloads page or at least a link to Resources/user guides.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab.
