### ISSUE TITLE
Request to add MoneroVision.com as a resource

### ISSUE THREAD

**Issue by jspence425** [monero-project/monero-site#777]
MoneroVision.com is a recently-launched open-source Monero explorer. It's the first of its kind in that it has a modern design & branding, has estimated transaction timers, and more detailed here: https://medium.com/mycrypto/introducing-monerovision-com-ee0c9656dd3a

I'm submitting this request to get MoneroVision added to the site where appropriate.

Any consideration is appreciated. :)

**Comment by jspence425** [comment]
Mmm, that’s odd and definitely shouldn’t be happening. Have you tried in a different browser or with a clear cache?

**Comment by UkoeHB** [comment]
Firefox, Safari, and Opera don't work. It may be my outdated OSX- mountain lion.

**Comment by erciccione** [comment]
Yes, monerovision not working. No reason to add it until it's fixed

**Comment by erciccione** [comment]
+merchant

**Comment by erciccione** [comment]
Actually now it's working properly. Adding it right now

**Comment by erciccione** [comment]
Added in #779 
Thanks :)

+in progress

**Comment by jspence425** [comment]
Thank you @erciccione! Much appreciated.

**Comment by UkoeHB** [comment]
Browser console:
SyntaxError: missing = in const declaration main.bundle.js:13:7724
