### ISSUE TITLE
BitDials. The Crypto-Only Luxury Boutique

### ISSUE THREAD

**Issue by BitDials** [monero-project/monero-site#783]
BitDials is the world's first crypto-only luxury boutique that provides original and unique luxury watches and fine jewelry to the crypto community since 2016.

We are accepting Monero (XMR) from now on, as well as further crypto-currencies (BTC, BCH, ETH, LTC, DOGE and DCR) with our new payment processor which is GLOBEE.

We are offering new/unworn and also pre-owned luxury watches from Rolex, Audemars Piguet, Roger Dubuis, Breguet, Cartier, Chopard, Omega, Hublot, Breitling, Tag Heuer and lot of other brands as well as fine jewelry from Chopard and Bvlgari (more to come).

We will offer certified diamonds as an alternative cash-out option soon.
In a few weeks we will also expand our project and offer luxury cars (old timers and premium sport cars).

You are most welcome to visit us at https://www.bitdials.eu

We would kindly ask you for adding us to the merchant site on getmonero.org

Thank you!
André Shevá for BitDials

**Comment by erciccione** [comment]
Added in #784 

+resolved

**Comment by BitDials** [comment]
Will we be added?

**Comment by erciccione** [comment]
@BitDials You are already added (by #784 ). You will see your service online once the server hosting the website will be updated

**Comment by BitDials** [comment]
Great! Thank you!
André
