### ISSUE TITLE
New merchant

### ISSUE THREAD

**Issue by FatBirdie** [monero-project/monero-site#795]
Monero has been added as payment option to your online store.
I'm not sure if I did it correctly (never used GitHub before) so I'll drop this comment here as well, but I did modify the https://github.com/monero-project/monero-site/blob/master/_data/merchants.yml file and tried adding the website there, but don't know if it was rejected or if there is just a lack of oversight on progress.

I'd be happy if we could get some help getting listed.
https://www.gemma-led.com

Thanks !

**Comment by el00ruobuob** [comment]
@FatBirdie Aparently you forked the site and did your change correctly in the merchants file. However you should now "pull request" your branch "patch 1" to this repo. Open your branch in GitHub and you'll find an option to do it. Then write a nice title and an explanation telling it solves #795.

**Comment by FatBirdie** [comment]
Thank you.

Ok, still a bit confused on how GitHub works, but I think I found it and hopefully did it correctly. If not, please do correct me.

**Comment by el00ruobuob** [comment]
You created the pull request on your own fork. Do it again and in the option for target branch select upstream/master

**Comment by FatBirdie** [comment]
@el00ruobuob silly me,
I've re-submitted it now.

Thank you again!

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by FatBirdie** [comment]
Hello again
Just curious, what is the estimated time for website to update after the git has been updated?

**Comment by el00ruobuob** [comment]
Usually weeks

**Comment by FatBirdie** [comment]
Many thanks clarifying @el00ruobuob
