### ISSUE TITLE
Request to add BITEXBOOK crypto exchange to the merchants page.

### ISSUE THREAD

**Issue by cvnghv** [monero-project/monero-site#803]
Dear Monero Team,

Can you add BITEXBOOK crypto exchange to the merchant list as XMR/BTC pair has been recently added?
Here is the link: https://bitexbook.com/trading/xmrbtc

Please, feel free to ask for any additional information if necessary.

Thank you!

**Comment by cvnghv** [comment]
Dear Monero Team, 

There is an answer from you for a long time. 

Is something wrong?

**Comment by el00ruobuob** [comment]
Sorry to have let this behind.
I'll take care of your request.

**Comment by el00ruobuob** [comment]
Done.

**Comment by cvnghv** [comment]
Thank you!

**Comment by erciccione** [comment]
Totally missed this one, sorry @cvnghv 

+merchant
+in progress

**Comment by erciccione** [comment]
+resolved
