### ISSUE TITLE
Add Bulletproofs to roadmap

### ISSUE THREAD

**Issue by Onefox** [monero-project/monero-site#805]
we should add something about the bulletproof status to the roadmap over here:
https://getmonero.org/resources/roadmap/

The reviews are going good and the plan as fare as I know is to enable it in the next protocol upgrade.

**Comment by el00ruobuob** [comment]
In fact it is "More efficient range proofs for RingCT to reduce transaction sizes" but I reckon it's not really obvious.

**Comment by SamsungGalaxyPlayer** [comment]
I believe I made that sentence @el00ruobuob before the bulletproof paper was released. It can be changed to mention bulletproofs.

**Comment by Onefox** [comment]
Also it should be marked as Ongoing task.

**Comment by SamsungGalaxyPlayer** [comment]
@Onefox can you take the initiative on this? It should be trivial to update, and it should be able to be completed entirely from within the browser.

**Comment by el00ruobuob** [comment]
And off topic there is and update to push for kovri alpha version on 8/1 and upcoming beta.

**Comment by el00ruobuob** [comment]
This could be closed since #806 is merged. @erciccione?

**Comment by erciccione** [comment]
+resolved
