### ISSUE TITLE
AppleBitz New Crypto Market

### ISSUE THREAD

**Issue by clarencerobinsonpy** [monero-project/monero-site#812]
https://applebitz.org/

**Comment by el00ruobuob** [comment]
First of all, hi.
I see you offer bitcoin but I can't see monero listed as a mean of payment.
Could you clarify?

**Comment by el00ruobuob** [comment]
Please clarify how you support XMR @AppleBitz

**Comment by el00ruobuob** [comment]
The website is not accessible anymore, and the submitter has not respond in a month. This should be closed. @erciccione? @SamsungGalaxyPlayer?

**Comment by erciccione** [comment]
+resolved
