### ISSUE TITLE
Update hardware section on the downloads page

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-site#814]
Currently the hardware section on the downloads page states "As well, Ledger is working on integrating Monero into their hardware wallets." whilst both the CLI and the GUI are currently able to directly generate a Ledger Monero wallet. Thus, the hardware section basically needs an update.

**Comment by el00ruobuob** [comment]
You are correct.

**Comment by el00ruobuob** [comment]
This could be closed, since #815 is merged. @erciccione?

**Comment by erciccione** [comment]
+resolved
