### ISSUE TITLE
Forum funding contribute page has no integrated addresses

### ISSUE THREAD

**Issue by Onefox** [monero-project/monero-site#816]
At the moment there is only a address and payment-ID option when contributing to a funding request.

Since integrated addresses are over all better and more human error resisted we should use the also here or?

**Comment by el00ruobuob** [comment]
The FFS wallets are under the core team responsibilities. So even if I agree to your suggestion, I'll pass it over to @luigi1111

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab.
