### ISSUE TITLE
ChangeHero - get listed at the list of exchanges

### ISSUE THREAD

**Issue by ChangeHero** [monero-project/monero-site#818]
Hello,

I am Monika from the ChangeHero. We are a new instant crypto exchange platform for the fastest assets swap with the best rates. Please, check our website: https://changehero.io/

Our platform allows customers to make crypto-to-crypto transactions and buy crypto with the credit card, including Monero.

We are working hard to develop our network and partnership It would be really helpful if you include our logo to the list of exchanges on your website here: https://getmonero.org/community/merchants/
 
Among all of different instant exchanges, we have some significant advantages:
- a brand new trading engine - to find the best rate at multiple exchanges (in ex. Binance, Bittrex, Poloniex, HitBTC, etc.) and operate through high frequency near spread trading;
- buying cryptocurrency with credit card and bank transfer;
- new decentralized trading platform will be launched in the nearest future.

Would you please guide us through the procedure?

Looking forward to hear from you soon.
Best regards, Monika Helme
monika.helme@changehero.io
Business Development Manager, ChangeHero
Telegram: @monika_ch 
Skype: Monika Helme   
Website: https://changehero.io/

**Comment by el00ruobuob** [comment]
Hello @ChangeHero is your platform really allowing to buy XMR with credit card? Buying BTC seems to work (but expansive), but for XMR:
![image](https://user-images.githubusercontent.com/37215310/43398514-99226990-9408-11e8-96b3-3af4f222a261.png)

**Comment by ChangeHero** [comment]
Hello!
It is working correctly no, please try one more time.
Thank you!

Best regards,
[image: photo]
*Monika Helme*
Business Developer Manager, Change Hero

+37256763409 | monika.helme@changehero.io

https://changehero.io/ | Skype: Monika Helme
<https://mail.google.com/mail/u/1/#m_-4449889987911043574_>
<http://www.linkedin.com/in/monika-helme-a07aa9166/>
<http://twitter.com/Changehero_io>




2018-07-30 15:56 GMT+03:00 el00ruobuob <notifications@github.com>:

**Comment by el00ruobuob** [comment]
Yes it is.
On my way to add you.

**Comment by ChangeHero** [comment]
Hello!

Could you please notify me once you add our logo on your website?
I attached it to this letter.

Also, we would like to make a post in twitter. Would you please repost it?
Here is the text:

We are excited to start the collaboration with @Monero
<https://web.telegram.org/#/im?p=%40Monero>. From now on, you can get #XMR
on changehero.io. Buy it with a credit card or exchange with the best
rates, fast and anonymous. See you at changehero.io!


2018-07-30 16:52 GMT+03:00 el00ruobuob <notifications@github.com>:

**Comment by ChangeHero** [comment]
Hello!

It is a week since we talked last time about listing. Could you please tell
me when can we expect listing on your website?

Also, we would like to make a post on twitter. Would you please repost it?
Here is the text:

We are excited to start the collaboration with @Monero
<https://web.telegram.org/#/im?p=%40Monero>. From now on, you can get #XMR
on changehero.io. Buy it with a credit card or exchange with the best
rates, fast and anonymous. See you at changehero.io!

Appreciate your reply.
Thank you!

[image: photo]
*Monika Helme*
Business Developer Manager, Change Hero

+37256763409 | monika.helme@changehero.io

https://changehero.io/ | Skype: Monika Helme <#>
<http://www.linkedin.com/in/monika-helme-a07aa9166/>
<http://twitter.com/Changehero_io>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

2018-08-01 18:07 GMT+04:00 Monika Helme <monika.helme@changehero.io>:

**Comment by el00ruobuob** [comment]
You have been added to the code. Please wait for the site to be rebuild.  
We do not add any merchants or exchanges logo. Only list them.  
I have no idea who handle the tweeter account, so I can't guarantee it will be repost.

**Comment by ChangeHero** [comment]
Ok, I see

Could you possibly give me the contact of a person from marketing?
We would also like to discuss marketing opportunities.

Thank you!


[image: photo]
*Monika Helme*
Business Developer Manager, Change Hero

+37256763409 | monika.helme@changehero.io

https://changehero.io/ | Skype: Monika Helme <#>
<http://www.linkedin.com/in/monika-helme-a07aa9166/>
<http://twitter.com/Changehero_io>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

2018-08-08 13:45 GMT+04:00 el00ruobuob <notifications@github.com>:

**Comment by el00ruobuob** [comment]
Marketing contact from an open source project?? @SamsungGalaxyPlayer could you help here?

**Comment by ChangeHero** [comment]
Hello!

Could you please tell me, when your website will be updated? We want to
make a post about our listing on your website.

Thank you!

[image: photo]
*Monika Helme*
Business Developer Manager, Change Hero

+37256763409 | monika.helme@changehero.io

https://changehero.io/ | Skype: Monika Helme <#>
<http://www.linkedin.com/in/monika-helme-a07aa9166/>
<http://twitter.com/Changehero_io>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

2018-08-08 17:34 GMT+04:00 el00ruobuob <notifications@github.com>:

**Comment by erciccione** [comment]
Hi @ChangeHero 
Your service has been added with #819 you'll see your website listed once getmonero.org will be updated.

+merchant
+resolved

**Comment by ChangeHero** [comment]
Hello!

We are happy to inform you that our instant exchange WIDGET is available
now:

You can integrate our widget to your website or app and make your visitors
buy with the credit card or exchange XMR with no redirect.
In comparison with other widgets Changehero widget it totally adaptable
with any device and deliver the best user experience. It could be installed
as a button as well.

Would you be interested in installing our widget? I will send you all
necessary information about it.

Moreover, we are preparing articles about our partners and want to write
the article about Monero as well. We are going to distribute them through
our partner's news websites. Here is a link to the list of questions to
answer:
https://docs.google.com/document/d/1DHhKzd7f6jbhjIZbUexo83l_b1ckBiS9ssUQRFRF1bs/edit?usp=sharing



We would appreciate if you answer 5-10 questions, at least 2 of them should
be related to our collaboration (last section). We are ready to post it as
soon as we receive your answers.

Please let me know about your decision.
Thank you and best regards,



[image: photo]
*Monika Helme*
Business Developer Manager, Change Hero

+37256763409 | monika.helme@changehero.io

https://changehero.io/ | Skype: Monika Helme <#>
<http://www.linkedin.com/in/monika-helme-a07aa9166/>
<http://twitter.com/Changehero_io>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

2018-08-08 13:45 GMT+04:00 el00ruobuob <notifications@github.com>:
