### ISSUE TITLE
Proof reading ledger-wallet-cli.md guide - 2. Mac OS X

### ISSUE THREAD

**Issue by lh1008** [monero-project/monero-site#821]
Hi @el00ruobuob,
 
In the file [user-guides/ledger-wallet-cli.md](https://github.com/monero-project/monero-site/blob/master/_i18n/en/resources/user-guides/ledger-wallet-cli.md), section 2. Mac OS X where it says:

"Where the full path is, intuitively, the actual path on your Mac OS X.

The CLI will, after executing aforementioned command, prompt your for a password. Make sure to set a strong password and confirm it thereafter."

I think the word "**your**" is not used correctly o mistakenly written (I'm sure is "you"), "...prompt **you** for a password. 

"The CLI will, after executing aforementioned command, prompt **you** for a password. Make sure to set a strong password and confirm it thereafter."

:)

**Comment by el00ruobuob** [comment]
Yes, this is a typo copied from @dEBRUYNE-1 stack exchange. Do you want me to correct it in a new PR? Or are you already doing it.

**Comment by lh1008** [comment]
I'll do the PR. Let me update the fork I have, and submit it. :)

**Comment by lh1008** [comment]
Here it is #822.
