### ISSUE TITLE
Fix typo in CLI Windows 64-bit SHA256 hash

### ISSUE THREAD

**Issue by dEBRUYNE-1** [monero-project/monero-site#823]
Site (downloads page) lists:

`5c06097acebf643857672e673258d16d66a71de504377399b7407318f9887ee3s`

Hashes.txt lists:

`5c06097acebf643857672e673258d16d66a71de504377399b7407318f9887ee3`

The latter is correct.

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab.
