### ISSUE TITLE
Proof-reading mining_with_xmrig_and_docker.md guide "Why Docker" section

### ISSUE THREAD

**Issue by lh1008** [monero-project/monero-site#828]
Hi, 

Not sure of the word "an".

"The container I **an** using is alpine-xmrig as per the name it is built on the Alpine Linux image".

Should it be **"am"**.

**Comment by ordtrogen** [comment]
seems obvious to me. Go ahead and create a PR!

**Comment by lh1008** [comment]
@ordtrogen thank you. Made the PR #832.
