### ISSUE TITLE
The Language Dropdown Should Show a Flag Instead of "English"

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-site#829]
Just a thought -- I'm not sure how many foreigners wouldn't be able to tell what it means, but I don't think a flag representing the US would be too high-contrast and it's pretty universally known as a "What language am I on" type thing.

**Comment by el00ruobuob** [comment]
I'm not sure about that. It's limiting the language to one country, when we try to be decentralized. What about UK, Canada or Australia?

**Comment by dginovker** [comment]
That was my first thought for sure. Perhaps there's a better move -- default language in the region that the IP originates, or the slightest popup?

I did notice, depending on the browser size it has a little image of letters instead of writing English however. That was neat.

**Comment by erciccione** [comment]
This is a discussione we already had some months ago. Flags should be avoided when dealing with translations. The GUI wallet is in the process of being refactored to raplace flags with a text-based page (see monero-project/monero-gui#1092)

**Comment by ordtrogen** [comment]
Unless you can find a country-neutral flag for English ... no flag
