### ISSUE TITLE
Roadmap | Monero shows Kovri Alpha as unreleased

### ISSUE THREAD

**Issue by dginovker** [monero-project/monero-site#835]
https://getmonero.org/resources/roadmap/

Should say completed, as per 1 Aug 2018: https://twitter.com/getkovri/status/1024863651487010816

Edit:
I'm looking at the roadmap.yml right now and it shows that Kovri Alpha Release was completed, and Kovri Beta release is upcoming, but that does not reflect what's shown on the website. Does anyone have any insight?

Edit2: My local version shows the update. I guess master is behind and I'm a fool. This can be closed

**Comment by dginovker** [comment]
I would like to fix this myself but the Readme says you edit the roadmap in _data/roadmap.yml -- but such a file does not exist. Perhaps the readme needs an update too?

**Comment by SamsungGalaxyPlayer** [comment]
@dginovker you can close it, or else someone else with access to the bot tools can. It often takes a few days for the actual website source to be updated with the changes on Github.
