### ISSUE TITLE
merchant listing request

### ISSUE THREAD

**Issue by monovm** [monero-project/monero-site#842]
dear support 
please add us in merchant list 
we have 2 brands
https://monovm.com
https://1gbits.com

regards

**Comment by el00ruobuob** [comment]
Hello @monovm, could you clarify how you support XMR as payment method?
Both the sites says you support cryptocurrencies, but there is no list. Is it through a payment gateway? Which one?

**Comment by monovm** [comment]
Thanks we use coinpayments.net
Regards

**Comment by el00ruobuob** [comment]
Done in #844

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by monovm** [comment]
thanks 
i wan to follow up the matter
regards

**Comment by erciccione** [comment]
+resolved

**Comment by monovm** [comment]
dear  erciccione 

you mean sites are listed ?

**Comment by el00ruobuob** [comment]
They are in codebase. Kindly wait for a site rebuild.

**Comment by monovm** [comment]
;) thanks
