### ISSUE TITLE
Establish and implement consistent capitalization of the word "monero" across projects

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/monero-site#850]
I'm looking at the monero-gui project English source and it appears that in every occurrence, 'Monero' is capitalized.

At least when it's used as a currency name/unit of account, it should not be. Just like "ten dollars" or "fifty yen", it should be written as "twenty monero" with a lower case "m".
Here's a reference:
https://ell.stackexchange.com/questions/17517/why-arent-currency-names-capitalized

The rule probably is as simple as the unit of account, as per the SE question, being the only occurrence that should be lower case. All other references - to the project, the network, protocol, community etc - should be capitalized.

Each language has their own convention regarding this. German, for instance, capitalizes currency names, whereas Swedish does not.

I'm opening this as an issue so it can be discussed, rules for individual languages can be added, etc before opening any PRs.

Please also make any suggestions as to where this should be documented. I'd like to see a Moneropedia entry where it's explained.

**Comment by el00ruobuob** [comment]
I like the moneropedia entry idea. We could also use it to clarify the esperanto plural `Moneroj`, as it is not widely used or understood today.

**Comment by erciccione** [comment]
This issue is easy to implement, but require time and i don't know if it worth it. Since it's old and has stalled, if nobody picks it up i will just close it soon.
