### ISSUE TITLE
Monero payments

### ISSUE THREAD

**Issue by Herroo** [monero-project/monero-site#852]
What can we do to help simple retailers and others to implement Monero payments on their websites? Would it make sense to add a section of "how to get paid in Monero" on the official website and have super simple video guides for how to get it implemented on e.g. your wordpress site? 

Maybe here: https://getmonero.org/get-started/accepting/

How can I/we non-techies help out? Is there someone pedagogic from the core team or a regular contributor to the project who is interested in doing something like this as an FFS? I for one would be interested in funding something like this as it would increase the overall demand for Monero.

Just by looking at the 24h volumes of the top 15 market cap coins it is apparent that Monero is well behind the others, which is worryingSource: https://imgur.com/a/XpahLW1

**Comment by el00ruobuob** [comment]
I believe we should create a user guide for this (or several) "how to integrate globee to wordpress" for instance. But I'm not sure an FFS might be needed on this. We could write it with the help of payment gateways whom interest is to be used, so they should collaborate easily. Any thoughts from globee perspective @fluffypony ?

**Comment by ordtrogen** [comment]
I seem to recall there was a lot of work done on Wordpress <--> Monero maybe a year ago? 
Maybe it was @serhack who was doing it, or maybe he remembers.

Unless I misunderstand the topic on this thread, what you're asking for could already be available.

**Comment by serhack** [comment]
Hi @Herroo, welcome to Github and Monero community!

I am the lead developer of [Monero Integrations project](https://github.com/monero-integrations). This project aims to give to merchants the most private payment gateway compatible with CMS (Content Managment System). At the moment we have Woocommerce, OpenCart, Prestashop, WHMCS payment gateways.

One year ago I opened a FFS to started work about this. At the moment I am a little busy with another project, [Mastering Monero](https://masteringmonero.com). But when I will release that resource, I'll work fully on Monero Integrations. 

Probably I and @cryptochangements will ask for FFS since we have a couple of ideas to develop, expecially marketing. Why marketing? Well, it seems a lot of people could not looking for our project. I don't know really the reason for that. We'll do some maintenance for all plugins :- ) 

Let me know about any idea!

**Comment by el00ruobuob** [comment]
So I suggest we simply add a user guide which point to the different repositories with a few wording around, as well as a link to it in "accepting"

**Comment by serhack** [comment]
> So I suggest we simply add a user guide which point to the different repositories with a few wording around, as well as a link to it in "accepting"

Well, I was thinking to write a resource for developers so they could write own private payment gateway too!

**Comment by Herroo** [comment]
All of this sounds very promising, especially @serhack 's dedication for the question in the Integrations Project. Special thanks for that!

I am for any suggestion which make the information available, in a VERY pedagogic format and is simple to find for those seeking information about Monero. In an ideal world I believe that the official Monero website should be the single source of information you would need to get up and running - and there would be video guides so that we can start attract non-techie people. Whether it is if you would want to learn about the project, start spend, collect, get payments in, mine or exchange Monero. I do however understand that it might be a utopia.

I do like the point made by @el00ruobuob that we do not need to write/make everything ourselves but there might be other parties interested in getting that information on "our" website - for example Globee, monerujo or XMR-stak. We would then just need to invite them to it and to post their material on a logic place once it is up to standards.

**Comment by serhack** [comment]
I agree with @Herroo . At the moment, the getmonero.org website is bare. Definitely, we need more content! 😄

**Comment by el00ruobuob** [comment]
Damned, i think i responsed to it, but with my country-side internet, it has been lost.
So i suggest to:
- add each existing guides from the repo to a new "merchants" section within user-guide page;
- thanks and cheers @serhack for this dev-guide idee, which will be great to integrate.

If we have consensus on this, i can start with user-guides right away.

**Comment by senangonline** [comment]
Is this where we submit info on merchants accepting monero?

Or is there any form somewhere? TIA..

**Comment by rehrar** [comment]
The Accepting page needs to be completely rewritten to talk about how people (businesses and users) can start accepting Monero. It should highlight things like Monero Integrations and Globee.

**Comment by el00ruobuob** [comment]
Let's do a poll:

Do we add all the monero-integrations how-to to a new user-guide section?

* **Yes, we need more content**
* Only a link to github
* No, don't even pronounce its name

**Comment by Herroo** [comment]
Great idea to have a vote. My vote falls on:
**Yes, we need more content**

**Comment by directdepot** [comment]
The reason a lot of small merchants do not accept Monero is because of the price functions.  They sell a product and then have to purchase more of that product in their fiat currency.  So you not only need to provide an easy way to accept Monero, the merchant needs an easy way to quickly convert the currency  so they can purchase more product to sell.

**Comment by el00ruobuob** [comment]
@directdepot this is exactly what Globee and other payment gateway are for. Globee allow you to accept XMR and hold in as fiat. That's why we need @fluffypony support to help user to integrate them from our website itself, or at least explain the concept.

**Comment by cryptochangements34** [comment]
I am 100% in favor of explaining how to easily accept Monero. However, if it is going to highlight certain services then I vote for Monero-Integrations as opposed to Globee because Monero-Integrations only supports Monero and is 100% free (both libre and gratis) while Globee is a for-profit company

**Comment by erciccione** [comment]
This issue is old and was discussed and closed on gitlab. Please reopen if you feel it's worth it.
