### ISSUE TITLE
Add ATM XMR provider

### ISSUE THREAD

**Issue by cryptodiggers** [monero-project/monero-site#862]
Please add CryptoDiggers.eu as XMR ATM provider for buying XMR anonymously with cash <5000eur per transaction in Slovakia Bratislava

**Comment by SamsungGalaxyPlayer** [comment]
@cryptodiggers your website refers to Monero as `MNR` under the donation section: https://cryptodiggers.eu/#atms

Can you please refer to Monero by its ticker `XMR`?

Also, I recommend adding the following wallets under the suggested wallets for Monero:

**Android**

* [Monerujo](https://monerujo.io)

**iOS**

* [Cake Wallet](https://cakewallet.io/)

* [X Wallet](https://xwallet.tech/)

**Comment by el00ruobuob** [comment]
Nice catch!

**Comment by erciccione** [comment]
+merchant
+in progress

**Comment by cryptodiggers** [comment]
Hi,Perfect, thanks for feedback .. it was done almost 1 year back. BuggieS pozdravom / Best regardsCryptoDiggers Team-------- Original Message --------Subject: Re: [monero-project/monero-site] Add ATM XMR provider (#862)From: Justin Ehrenhofer To: monero-project/monero-site CC: cryptodiggers ,Mention @cryptodiggers your website refers to Monero as MNR under the donation section: https://cryptodiggers.eu/#atms
Can you please refer to Monero by its ticker XMR?
Also, I recommend adding the following wallets under the suggested wallets for Monero:
Android

Monerujo

iOS


Cake Wallet


X Wallet



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/monero-project/monero-site","title":"monero-project/monero-site","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/monero-project/monero-site"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SamsungGalaxyPlayer in #862: @cryptodiggers your website refers to Monero as `MNR` under the donation section: https://cryptodiggers.eu/#atms\r\n\r\nCan you please refer to Monero by its ticker `XMR`?\r\n\r\nAlso, I recommend adding the following wallets under the suggested wallets for Monero:\r\n\r\n**Android**\r\n\r\n* [Monerujo](https://monerujo.io)\r\n\r\n**iOS**\r\n\r\n* [Cake Wallet](https://cakewallet.io/)\r\n\r\n* [X Wallet](https://xwallet.tech/)"}],"action":{"name":"View Issue","url":"https://github.com/monero-project/monero-site/issues/862#issuecomment-418004967"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/monero-project/monero-site/issues/862#issuecomment-418004967",
"url": "https://github.com/monero-project/monero-site/issues/862#issuecomment-418004967",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [monero-project/monero-site] Add ATM XMR provider (#862)",
"sections": [
{
"text": "",
"activityTitle": "**Justin Ehrenhofer**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@SamsungGalaxyPlayer",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"monero-project/monero-site\",\n\"issueId\": 862,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"monero-project/monero-site\",\n\"issueId\": 862\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/monero-project/monero-site/issues/862#issuecomment-418004967"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 373685673\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by cryptodiggers** [comment]
We are also supporting payments with XMR on CDPAY.eu , could somehow arrange for us also adding to payment gateways please ? 

 

Buggie
