### ISSUE TITLE
Add merchant

### ISSUE THREAD

**Issue by senangonline** [monero-project/monero-site#863]
Been accepting Monero since JAN 2017

1oasis.net @ senang.online

SERVICES:
Registration for generic top-level and ccTLD domain names plus web+email hosting & cloud services including Google Suite, Weebly sitebuilder and Comodo SSL certificates for personal or business use. Stay anonymous as long as no abuse complaints.

http://1oasis.net 

Thank you!

**Comment by erciccione** [comment]
+merchant
+in progress
