### ISSUE TITLE
Roadmap | Monero shows inaccurate Kovri Beta

### ISSUE THREAD

**Issue by anonimal** [monero-project/monero-site#876]
https://getmonero.org/resources/roadmap/

Whoever added that wasn't paying attention to the fact that integration will come *before* Beta. Beta is just a name. Someone replace "Beta" with "Integration".

**Comment by el00ruobuob** [comment]
I did this, sorry for my misunderstanding. I will correct it right away.

**Comment by el00ruobuob** [comment]
Corrected in #877 @anonimal
