### ISSUE TITLE
Why is megachange.is a scam site listed in the site as a merchant?

### ISSUE THREAD

**Issue by sakibarifin** [monero-project/monero-site#882]
This site is a known scammer with complains all over the internet. He stole 31 dollars from me (I was lucky to send only the minimum amount).

Here are some of the links to complains:

https://bitcointalk.org/index.php?topic=2946755.0

https://www.trustpilot.com/review/megachange.is

https://alternativeto.net/software/megachange-is/reviews/

**Comment by erciccione** [comment]
Well, the amount of complaints cannot be ignored. Merchant listed on our website are not endorsed by the community in any way, but in cases like this, where the scam seems objective, i think there are all the basis to remove them from our list. opened #883
Thanks @sakibarifin :)

+merchant removal
+in progress
