### ISSUE TITLE
Ownbit wants to be listed

### ISSUE THREAD

**Issue by jtomtan** [monero-project/monero-site#893]
Hi Menero team,

Ownbit wants to be listed as one of 3rd wallets that support XMR. As one of the mobile wallets that support XMR, Ownbit implemented BulletproofV2 in JS by its own.

Website: https://ownbit.io

Thanks for the help.

**Comment by erciccione** [comment]
Please follow the instructions at the top of the merchants page to add a new merchant: https://web.getmonero.org/community/merchants/

This repository is not active yet.

**Comment by erciccione** [comment]
Opened on gitlab: https://repo.getmonero.org/monero-project/monero-site/-/issues/1079
