### ISSUE TITLE
Make getmonero.org/community/sponsorships list what the sponsors did

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#896]
*Issue originally created by @OsrsNeedsF2P*

*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/981*

---
This was brought up in the Monero Coffee Chat (Aug 24th), and some ideas were thrown around about how it would be done. Discuss?

**Comment by erciccione** [comment]
This is blocked until we get to know what each sponsor did, so that we cann add it to the page. I don't know who has these info.

**Comment by SamsungGalaxyPlayer** [comment]
I'll update this chart if people can tell me how to fill it in.

| Sponsor | Benefit |
| --- | --- |
| MyMonero | |
| JetBrains | |
| Dome9 Security | |
| Kitware | |
| Fork Networking | |
| Araxis | |
| Navicat | |
| Symas | |

**Comment by erciccione** [comment]
@SamsungGalaxyPlayer see https://github.com/monero-project/monero-site/issues/1168#issuecomment-684792450 for updates reguarding the list of sponsors.

**Comment by hyc** [comment]
Symas pays for my time when I do development on Monero code.

**Comment by erciccione** [comment]
#1174 

Thanks @hyc, i added a description of symas' sponsorhip terms. Please let me know if you prefer to use different wording.

**Comment by hyc** [comment]
That's probably too specific at this point. After all, I've worked on the wallet, the daemon, the PoW algo, etc. etc.

**Comment by erciccione** [comment]
My intent was to specify the sponsored work you have done, differentiating it from your work as a "free" contributor. That might just be me misunderstanding the terms of the sponsorship. If you prefer, i can write something more general.

**Comment by erciccione** [comment]
@hyc i changed the text to `Symas sponsors its CTO Howard Chu (hyc) for his work on the Monero codebase.`.

**Comment by hyc** [comment]
Thanks.
