### ISSUE TITLE
Create a .onion mirror of the site

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#904]
*Issue originally created by @Electricsheep01*

*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/958*

---
It is quite probable that the FATF is going to start cracking down on privacy focused projects like Monero soon. We should really have .onion mirror(s) of getmonero.org for those who need that extra layer of protection.

**Comment by erciccione** [comment]
@danrmiller Please let us know when there are progresses on this :)

**Comment by erciccione** [comment]
ping @danrmiller

**Comment by garlicgambit** [comment]
Any updates on this issue?

**Comment by erciccione** [comment]
We are finalizing the last details. The onion address will be published soon. (related: https://github.com/monero-project/monero-site/pull/1458)

**Comment by garlicgambit** [comment]
Nice  
  
Are the .onion domains using the single hop/non-anonymous mode?  
Will the CCS also become available as an .onion service?

**Comment by erciccione** [comment]
> Are the .onion domains using the single hop/non-anonymous mode?

I'm not sure, but that would be ok. We don't really need anonymity in this context.

>  Will the CCS also become available as an .onion service?

There are no plans for this currently.
