### ISSUE TITLE
Update press kit quick facts pdf

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#906]
*Issue originally created by @SamsungGalaxyPlayer*

*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/1029*

---

The press kit quick facts PDF has not been updated since May 2018. Several items have changed, including the market cap and network info (maybe remove?), bulletproofs, Kovri, and the Monero Outreach workgroup name.

**Comment by erciccione** [comment]
To my Knowledge the Outreach workgroup is working on this. Is it still the case @xmrhaelan?

**Comment by erciccione** [comment]
If this isn't resolved in a reasonable time, will probably make sense to remove the 'quick facts' document from getmonero. No point in giving users an outdated document.

**Comment by xmrhaelan** [comment]
Yes we are updating. Had some issues with bugs trying to automate data from our node, but we’ll push an update soon while we keep ironing out the bugs to make this more automated in the future.

**Comment by lh1008** [comment]
Hey everyone,

Updated :)

https://www.monerooutreach.org/quick-facts.html

**Comment by erciccione** [comment]
Nice, thanks :) Do you have a PDF version that we can upload on getmonero?

**Comment by erciccione** [comment]
For some reason i thought we were offering a PDF, when instead we simply link to the monerooutreach website. This issue is resolved.
