### ISSUE TITLE
Add to FAQ why Monero is "reasonably" private

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#914]
*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/1045*

---
see https://repo.getmonero.org/monero-project/monero-site/merge_requests/1136#note_7452

**Comment by SamsungGalaxyPlayer** [comment]
I think this should be closed, since we should instead remove the word "reasonably" in my opinion. It doesn't actually convey the nuances it intends to convey, and we should point people to other resources (like the MRL papers and Breaking Monero) for specific questions.

**Comment by erciccione** [comment]
This is blocked until #971 is resolved.

**Comment by erciccione** [comment]
We are removing 'reasonable' from the homepage (#1032). This is not needed anymore
