### ISSUE TITLE
Signed checksums for pdfs

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#923]
*Issue originally created by @koe*

*This issue was created on gitlab and then migrated here. Only the original post was migrated, not the comments. Please take a look at the discussions on the original Gitlab issue before commenting here: https://repo.getmonero.org/monero-project/monero-site/-/issues/1081*

---
Following [this comment on ztm2](https://www.reddit.com/r/Monero/comments/fvk68v/zero_to_monero_second_edition_published/fmm2tc2?utm_source=share&utm_medium=web2x), it seems wise to add a signed checksum for all pdf documents hosted on the site (and other non-software downloads). This includes all the MRL files, and everything in the library. There are also some .ai files in the Press Kit.

Given the amount of files (about 18), I think it would be helpful to have a separate page for all of them.

**Comment by garlicgambit** [comment]
Having (unsigned) sha256sums available on the website and in the wild would be a start. Lets make it a habit to post checksums of files.

**Comment by erciccione** [comment]
This is not planned.
