### ISSUE TITLE
Add iCryptoNode to the merchants page

### ISSUE THREAD

**Issue by jseibel-circle** [monero-project/monero-site#955]
#### What's the name of your business?

iCryptoNode

#### What's the URL of the website?

https://icryptonode.com/

#### Write a brief description of your business/service (max 50 characters)

Seller of Raspberry Pi Monero Nodes and open source software provider.

#### Enter the URL where a Monero mention can be found

https://icryptonode.com/products/monero-icryptonode-raspberry-pi-device

"We accept Monero as a payment option at checkout."

#### How do you accept Monero? *(choose only one option)*

- [ X] Native wallet

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [X ] Goods
- [ ] Entertainment

#### Comment

This business is very focused on Monero.

**Comment by erciccione** [comment]
Legit.
