### ISSUE TITLE
Add AnonAddy to merchants

### ISSUE THREAD

**Issue by sylph1o** [monero-project/monero-site#960]
#### What's the name of the business?

AnonAddy

#### What's the URL of the website?

[anonaddy.com](https://anonaddy.com)

#### Write a brief description of the business/service (max 50 characters)

Anonymous email forwarding service.

#### Enter the URL where a Monero mention can be found

[https://anonaddy.com/help/category/subscriptions](https://anonaddy.com/help/category/subscription)

#### How does it accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [X] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize the business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [X] Service
- [ ] Goods
- [ ] Entertainment

#### Comment

My only affiliation with this service is that I am a customer. I have paid my subscription with Monero. I will let the business owner know about this issue once it is created.

**Comment by erciccione** [comment]
> https://anonaddy.com/help/category/subscriptions

This page doesn't seem to exist

**Comment by willbrowningme** [comment]
@erciccione I've just added a short article there. I'll be adding more details and an automated option for cryptocurrency subscriptions in the future.
