### ISSUE TITLE
Replace integrated address with subaddress for Donations

### ISSUE THREAD

**Issue by Sunray-Nucleon** [monero-project/monero-site#985]
There are still several 4... addresses, for example on https://web.getmonero.org/get-started/contributing/ should we replace with 8... addresses?

In my understanding Subaddresses are principally preferable before 4...main-addresses. So is it possible to replace it, also here on Github and other places like https://revuo-monero.com/issue-60.html

We would want to propagate the use of 8... addresses, right?

**Comment by erciccione** [comment]
From @binaryfate on `#monero-site`:

> Yes that's a good idea
 I'll make a PR to replace address for general fund (44AFFq...)

**Comment by binaryFate** [comment]
Also see https://repo.getmonero.org/monero-project/ccs-front/-/merge_requests/30 fixing same issue on the CCS repo
