### ISSUE TITLE
CryptoFlooring

### ISSUE THREAD

**Issue by cryptoflooring** [monero-project/monero-site#991]
#### What's the name of your business?

CryptoFlooring

#### What's the URL of the website?

cryptoflooring.com

#### Write a brief description of your business/service (max 50 characters)

We sell plank flooring that is shipped by freight to local terminals across the U.S. We accept cryptocurrency as payment, including monero.

#### Enter the URL where a Monero mention can be found

https://www.cryptoflooring.com/contact

#### How do you accept Monero? *(choose only one option)*

- [ ] Monero integrations *(github.com/monero-integrations)*
- [ ] Globee
- [ x] Native wallet
- [ ] Other payment gateaway (Coinpayments, Morphtoken, etc. *Please specify*)

#### How would you categorize your business? *(choose only one option)*

- [ ] Exchange
- [ ] Block Explorer
- [ ] Payment Gateway
- [ ] Library and Helper
- [ ] Tool
- [ ] Service
- [ x] Goods
- [ ] Entertainment

**Comment by erciccione** [comment]
Looks legit.
