### ISSUE TITLE
Link visible to Zero-to-Monero-2-0-0.pdf

### ISSUE THREAD

**Issue by Sunray-Nucleon** [monero-project/monero-site#998]
Link to the Paper https://web.getmonero.org/library/Zero-to-Monero-2-0-0.pdf 'zero to monero second edition v2.0.0' preferably at a visible place like https://getmonero.org/resources/research-lab/ (Coinbase is linking to that page as whitepaper-page) and/or https://web.getmonero.org/blog/tags/community.html

**Comment by erciccione** [comment]
I don't know if would make sense to move zero to monero to the research lab page. We would need to create a dedicated section only for that. Personally, i think it's fine where it is. We could link to it from other parts of the website, but i wouldn't do more than that.

**Comment by erciccione** [comment]
Do we want to have that file somewhere else? Otherwise i would just close this issue.

**Comment by erciccione** [comment]
We will link to the Library from the MRL page with #1409. That will make zero to monero and other resources easier to find. I'm closing this.
