### ISSUE TITLE
Poke owner of website or replace Link - getmonero.org/resources/user-guides

### ISSUE THREAD

**Issue by Sunray-Nucleon** [monero-project/monero-site#999]
https://web.getmonero.org/resources/user-guides/mine-to-pool.html
 certificate of moneropools.com is over three years expired and the quality of the content of the website is questionable! miningpoolstats.stream/monero has been a way more reliable source, i don't know if we should or can link there?

**Comment by Sunray-Nucleon** [comment]
just a few minutes after writing this here the 'let's encrypt' certificate ended - i think it was 20 March 2018 - seem to got removed, very fast.

**Comment by Sunray-Nucleon** [comment]
just a few minutes after writing this here the 'let's encrypt' certificate (ended - i think it was 20 May 2018) seem to got removed, very fast.

**Comment by erciccione** [comment]
@Sunray-Nucleon This can be closed in favour of #1005
